README.md
=> update README to reflect loading changes from #104

README.md, src/features/ar.js, src/test/features/ar-spec.js
Here are the aggregate issues, let me know what's missing!
#145 
#152 
#144 
#135 
#134 
#118
=> Update docs for release, fixes #152, #145, #144, #135, #134, #118

src/three-components/ModelScene.js, src/three-components/Renderer.js, src/three-components/TextureUtils.js
=> Do not set gammaInput=true, and ease back the ambient lighting a bit.

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md
=> add templates and update the contributing guide

README.md
=> add a link to the project board to the top of the README

src/features/magic-leap.js
=> Tweak Magic Leap hologram config

src/model-viewer-base.js, src/test/model-viewer-base-spec.js, src/three-components/ModelScene.js
=> Dispatch an error event for invalid source

package-lock.json, package.json
=> Use polling when watching changed files in "npm run watch" on linux

POLYFILLS.md, src/template.js
=> Alt text for Enter AR button

README.md
I know that competent web developers will be able to figure this out on their own, but communication should always be frictionless. @johnpallett
=> Add instructions for running the examples.

package-lock.json, package.json
=> Upgrade three r98 -> r99

src/test/three-components/ARRenderer-spec.js, src/three-components/ARRenderer.js
Pulled out from #265 which has some other issues. Fixes #269
=> When placing a model in WebXR, the model now faces the viewer rather than scene origin

src/three-components/ARRenderer.js
Support new changes to WebXR API in Chrome M73 with introduction of makeXRCompatible, requestReferenceSpace, and getViewerPose, as well as support the functions they've deprecated.
Tested in both Chrome Canary (73.0.3666.0), which uses the 3 above APIs, and Chrome Dev (73.0.3643.0), which uses the previous shape of all 3 features.
In the future, maybe we can use the [webxr-version-shim](https://github.com/immersive-web/webxr-samples/blob/spec-update/js/webxr-version-shim.js) being developed against the latest spec (which is only paritally implemented in Chrome, hence this issue), or a smaller bespoke abstraction once things stabilize, similar to #281.
Fixes #291
=> Support new changes to WebXR API in Chrome M73

examples/accessibility.html, examples/accessibility/auto-rotate.html, examples/accessibility/controls.html, examples/accessibility/multiple.html, examples/accessibility/poster.html, examples/accessibility/reveal.html, examples/loading.html
Leverage the existing demos where possible, otherwise create specific pages to exercise accessibility scenarios for basic usage of `<model-viewer>`.
This will allow further investigation of the accessibility of the component, to see if there are areas we can continue to improve.
Part of #295
=> exercise specific accessibility scenarios

examples/styles/examples.css, package-lock.json, src/documentation/components/example-snippet.ts
This change fixes HTML examples showing empty quotes on boolean attributes, as well as layout weirdness on some of the examples.
=> Fixes some content flow, and ExampleSnippet bug

examples/augmented-reality.html, examples/background-color.html, examples/background-image.html, examples/default.html, examples/list.html, examples/loading.html, examples/multiple-elements.html, examples/pbr.html, examples/sources.html, package-lock.json
=> Fixed return links in example pages.

README.md
=> updated readme link to examples

index.html
=> Fixed favicon url in index.html

examples/format-support.html, examples/lazy-loading.html, examples/lighting-and-environment.html, examples/rendering-showcase.html
@donmccurdy pointed out that some of our docs links are broken. Fixes #412
=> Fix Github corner links in docs

src/test/fidelity/gltf_renderer.cpp
Refactored in: https://github.com/google/filament/commit/7b3475f1da7f07512748681591d2635d8a7be909
=> Stay current with the refactored Filament matrix factory functions

index.html
=> fix the path to node_modules in index.html

examples/styles/examples.css, index.html
=> Added browser support section in docs site

src/test/fidelity/filament.patch
Filament's `samples/CMakeLists.txt` changed slightly
=> update to latest filament

index.html
=> revert back to auto-rotate astronaut in landing

examples/animation.html
=> Updated source link in animation.html

.travis.yml
=> add a VERSION file to the gh-pages deploy

examples/animation.html, examples/augmented-reality.html, examples/lazy-loading.html, examples/lighting-and-environment.html, examples/model-formats.html, examples/staging-and-camera-control.html
=> Fixed return url

README.md, examples/augmented-reality.html, index.html
=> Document the `ar` attribute

index.html
Borrowed language from Polymer/polymer.
=> Docs: Added instructions to main snippet.

POLYFILLS.md
Fix small type in the polyfills documentation.
=> Fix documentation typo

index.html, src/template.ts
Implements #514 
Now you can set a pixel value for the height of the progress bar.
=> Added css property for progress bar height.

POLYFILLS.md, examples/accessibility.html, examples/animation.html, examples/augmented-reality.html, examples/fuzzer.html, examples/lazy-loading.html, examples/lighting-and-environment.html, examples/list.html, examples/model-formats.html, examples/multiple-elements.html, examples/pbr.html, examples/rendering-showcase.html, examples/staging-and-camera-control.html, examples/styles/examples.css, index.html
- Samsung Internet has been added to our compatibility tables
- Language related to Fullscreen API requirements has been updated
Fixes #543
=> Document Samsung Browser requirements

src/three-components/SmoothControls.ts
Fixes #634 
Replaced our linear discrete integration of our second order system of SmoothControls with an exact solution, allowing large time steps to be calculated accurately.
=> exact integration of SmoothControls

examples/accessibility.html
=> removed link to default.html which was a non-existent file

package-lock.json, package.json, src/constants.ts, src/types/offscreencanvas.d.ts
=> Add OffscreenCanvas to ts

package-lock.json, package.json, src/features/ar.ts, src/template.ts
This change brings forward the hotfix address #693 via #698. Since this change was originally applied to the v0.5.0 release branch point, this change applies it to the main lineage.
=> Forward-port v0.5.1 hotfix to master

package-lock.json, package.json, src/types/offscreencanvas.d.ts
update the type script to version 3.5, so it support offscreencanvas
=> update offscreencanvas type script file

src/features/loading/status-announcer.ts, src/template.ts
Fixes #767 
cc @svinkle I might ask for your help verifying the fix :)
=> Ensure status text is hidden in high contrast mode

src/three-components/SmoothControls.ts
This is a small refactor which unifies single touch and mouse interaction logic.
The main reason I'd like to do this is that it's much easier to write code for both single touch and mouse interactions when these logic paths are combined. 
For instance in a subsequent PR I'd like to explore adding a new `interaction-policy` which would toggle interactions on and off whenever a `<model-viewer>` is tapped/touched. So basically tap to enable interactions, tap to disable interactions. (think play pause button for video) It would help with this [issue](https://github.com/GoogleWebComponents/model-viewer/issues/479#issuecomment-490560705) mentioned by @elalish.
During user testing that @pushmatrix ran it seemed that this was the best UX to solve this problem.
- I changed the type of …
=> [Refactor] Unified logic for single touch and mouse pointer

src/test/fidelity/artifact-creator.ts
Looks like upping the timeout that waits for the model to be ready fixes our flake.
=> Fix fidelity flake

index.html, package-lock.json, src/features/controls.ts, src/test/features/controls-spec.ts
Fixes #741 
Also updated the docs.
=> fixed prompt

src/three-components/StaticShadow.ts
I guess I need to make an issue for this. Anyway, this makes our shadows not fight with models that have shadows baked in.
=> fixed shadow fighting

src/features/loading.ts, src/model-viewer-base.ts, src/test/features/loading-spec.ts, test/index.html, test/wct-sauce.conf.json
=> Only load when in render tree

README.md
Very small change, feel free to merge or close!
/cc @cdata
=> Add unpkg link to URL

examples/augmented-reality.html, index.html, src/features/ar.ts, src/test/features/ar-spec.ts
=> Adding ar-scale to control scaling behavior in Scene Viewer.

examples/augmented-reality.html, package-lock.json, package.json, src/features/magic-leap.ts
- Fixes compatibility with Prismatic 2.0.
- Cosmetic changes to Augmented Reality sample
- Include Prismatic module in AR sample
=> Magicleap prismatic 2.0 compatibility

src/features/loading.ts, src/template.ts, src/three-components/EnvironmentScene.ts, src/three-components/ModelScene.ts, src/three-components/PMREMGenerator.ts
Fixes #905 
@svinkle I think I fixed this, but confirmation from someone who knows accessibility better than myself would be great. 
I also took the opportunity to update some three.js methods that were deprecated and were spewing ugly warnings on the console.
=> Fix poster a11y

src/three-components/ModelUtils.ts, src/three-components/shader-chunk/shadowmap_pars_fragment.glsl.ts
Fixes #942 
Fixes #947 
This is a backport of https://github.com/mrdoob/three.js/pull/18328
Some more testing would be great, but this seems to have fixed both issues for me on my Pixel 3.
=> backported soft shadow fix from three

packages/model-viewer/src/features/annotation.ts
Does what it says on the tin 👍 diff is mostly whitespace.
=> Fix IE11 / cleanup formatting

packages/model-viewer/src/template.ts
=> Fix poster alignment when text-align is set

packages/3dom/src/api.ts, packages/model-viewer/package-lock.json, packages/model-viewer/package.json
=> Remove vestigial type dependency, tweak ConstructedWithArguments

packages/3dom/src/api/material-spec.ts, packages/3dom/src/api/material.ts, packages/3dom/src/context.ts, packages/3dom/src/end-to-end-spec.ts, packages/3dom/src/facade/three-js/three-dom-element-spec.ts, packages/3dom/src/facade/three-js/three-dom-element.ts
=> Express material names in the 3DOM scene graph

packages/model-viewer/src/features/animation.ts, packages/model-viewer/src/test/features/animation-spec.ts, packages/model-viewer/src/three-components/Model.ts
Fixes #1113 
Thanks @soraryu, I'm taking over your #1114 so we can get it merged for this release. Let me know if any problems remain!
=> Fix current time when paused

packages/model-viewer/src/styles/parsers.ts, packages/model-viewer/src/test/features/controls-spec.ts, packages/model-viewer/src/test/styles/parsers-spec.ts
Fixes https://github.com/google/model-viewer/issues/1122
=> Fix exponential syntax in parser

packages/model-viewer/src/three-components/SmoothControls.ts
@cdata noticed a small zoom jitter as it slowed to a stop. I believe the problem was we were using the wrong units for normalization (we used degrees, but log(degrees) is unitless).
=> fixed fov normalization

packages/model-viewer/src/three-components/ARRenderer.ts
This fixes a couple of issues where we were not cleaning up webxr properly in the case that the session was cancelled before it could start.
=> Webxr cleanup

CONTRIBUTING.md, README.md, packages/model-viewer/README.md
=> Document our versioning strategy

packages/model-viewer/src/features/ar.ts, packages/model-viewer/src/test/features/ar-spec.ts
Fixes #1194
Fixed according to [this](https://cwervo.com/writing/quicklook-web/).
=> enable fixed scale in quickLook

packages/model-viewer/src/three-components/ARRenderer.ts
=> hide hotspots on entering AR

packages/model-viewer/src/features/controls.ts, packages/model-viewer/src/test/features/controls-spec.ts
=> set far plane based on max radius

packages/modelviewer.dev/index.html
Add meta description tag to index.html for search results page
=> Add meta description tag to index.html

packages/3dom/package-lock.json, packages/3dom/package.json, packages/model-viewer/package-lock.json, packages/model-viewer/package.json, packages/modelviewer.dev/package-lock.json, packages/render-fidelity-tools/package-lock.json
=> update threejs to r117

packages/3dom/package-lock.json, packages/3dom/package.json, packages/model-viewer/package-lock.json, packages/model-viewer/package.json, packages/modelviewer.dev/package-lock.json, packages/render-fidelity-tools/package-lock.json, packages/render-fidelity-tools/test/renderers/model-viewer/index.html
Pulling in three's bugfix and ensuring fidelity tests don't downscale.
=> Update to r117.1

packages/model-viewer/src/test/model-viewer-base-spec.ts, packages/model-viewer/src/three-components/Renderer.ts, packages/modelviewer.dev/examples/tester.html
Fixes #1225 
I don't love that I had to turn on preserveDrawingBuffer to fix this, but no amount of calling render() and gl.finish() inside of ToBlob() would fix it. Very strange.
=> fixed toBlob on Firefox/Safari

packages/model-viewer/README.md
Now the v1 has already been released!
=> Remove status in development note

packages/model-viewer/src/features/ar.ts, packages/model-viewer/src/three-components/ARRenderer.ts
Fixes #1269 
We were failing to properly clean up when the permission to enter webxr was denied.
=> fixed permission denial

packages/3dom/src/api.ts, packages/3dom/src/api/material-spec.ts, packages/3dom/src/api/model-kernel-spec.ts, packages/3dom/src/api/pbr-metallic-roughness-spec.ts, packages/3dom/src/api/pbr-metallic-roughness.ts, packages/3dom/src/context/generate-capability-filter.ts, packages/3dom/src/facade/api.ts, packages/3dom/src/facade/three-js/pbr-metallic-roughness.ts, packages/3dom/src/protocol.ts, packages/3dom/src/test-helpers.ts
Changed source branch, see [PR 1290](https://github.com/google/model-viewer/pull/1290)
=> 3DOM metallicRoughness fix, extensions and tests

packages/model-viewer/src/features/scene-graph.ts, packages/model-viewer/src/test/features/scene-graph-spec.ts, packages/model-viewer/src/three-components/Model.ts, packages/modelviewer.dev/examples/exporter.html, packages/modelviewer.dev/index.html
I replicated the parameters from three's GLTFExporter to exportScene signature.
I also added an example page, let me know if it's useful/needed
=> Added model export to GLB/GLTF formats.

packages/model-viewer/src/test/model-viewer-base-spec.ts
Temporary work-around for #1333
=> Skip flaky idealAspect test

packages/modelviewer.dev/examples/animation.html, packages/modelviewer.dev/examples/augmented-reality.html, packages/modelviewer.dev/examples/customizing-ui.html, packages/modelviewer.dev/examples/exporter.html, packages/modelviewer.dev/examples/lazy-loading.html, packages/modelviewer.dev/examples/lighting-and-environment.html, packages/modelviewer.dev/examples/list.html, packages/modelviewer.dev/examples/model-formats.html, packages/modelviewer.dev/examples/rendering-showcase.html, packages/modelviewer.dev/examples/scene-graph.html, packages/modelviewer.dev/examples/staging-and-camera-control.html, packages/modelviewer.dev/examples/tester.html, packages/modelviewer.dev/examples/webxr.html, packages/modelviewer.dev/index.html
=> updated copyright

packages/model-viewer/src/three-components/SmoothControls.ts
Fixes #1312 
I don't have a great way to repro the problem, so I'm hoping this fixes it.
=> Fix slow scroll of Firefox

packages/space-opera/src/components/materials_panel/materials_panel.css.ts, packages/space-opera/src/components/materials_panel/materials_panel.ts
Update styels for revert buttons.
=> Update styles for revert button

package-lock.json, packages/3dom/package-lock.json, packages/3dom/package.json, packages/editing-adapter/package-lock.json, packages/editing-adapter/src/gltf/gltf_model.ts, packages/editing-adapter/src/gltf/gltf_model_test.ts, packages/model-viewer/package-lock.json, packages/model-viewer/package.json, packages/modelviewer.dev/package-lock.json, packages/modelviewer.dev/package.json, packages/modelviewer.dev/src/tester.ts, packages/render-fidelity-tools/package-lock.json, packages/render-fidelity-tools/package.json, packages/space-opera/package-lock.json, packages/space-opera/package.json, packages/space-opera/src/components/model_viewer_preview/model_viewer_preview.ts, packages/space-opera/src/components/poster_controls/poster_controls.ts, packages/space-opera/src/components/utils/render_model_viewer.ts, packages/space-opera/src/redux/space_opera_base.ts
Fixes #1372 
In addition to cleaning up our dependencies and fixing our "main" pointer, this also ensures the .map files are included for debugging. I've also updated our contributors lists.
=> updated npm package

packages/model-viewer/src/three-components/ModelScene.ts
=> fixed shadow refresh for target motion

packages/space-opera/src/components/camera_settings/camera_settings.ts
add "dragStepSize=0.01" to attribute.
Fixes #1429
=> adjust step size of modelviewer.dev/editor sliders

packages/model-viewer/src/features/ar.ts, packages/model-viewer/src/test/features/ar-spec.ts
Taking over #1456 to fix/add tests. Thanks @hybridherbst!
=> Url params

.github/workflows/deploy-documentation.yml, .github/workflows/fidelity-tests.yml, .github/workflows/unit-tests-third-party.yml, .github/workflows/unit-tests.yml, packages/render-fidelity-tools/src/common.ts, packages/render-fidelity-tools/test/renderers/model-viewer/index.html
The poster bug still exist even if we have already used two raf. I just add code to test whether the golden is semi transparent.
=> more raf, transparent check

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, README.md, packages/model-viewer/POLYFILLS.md, packages/modelviewer.dev/examples/lazy-loading.html, packages/modelviewer.dev/index.html
Fixes #1128
Fixes #1452 
Fixes #1258 
Also updates some links and polyfill info.
=> Docs update

packages/render-fidelity-tools/test/config.json, packages/render-fidelity-tools/test/results-viewer.html
This adds description to our fidelity page and reorders the scenarios a little.
=> Fidelity docs

package-lock.json, packages/editing-adapter/package-lock.json, packages/modelviewer.dev/package-lock.json, packages/render-fidelity-tools/package-lock.json, packages/render-fidelity-tools/package.json, packages/render-fidelity-tools/src/artifact-creator.ts, packages/render-fidelity-tools/src/common.ts, packages/render-fidelity-tools/src/workflows/test-fidelity.ts, packages/render-fidelity-tools/test/renderers/model-viewer/index.html, packages/space-opera/package-lock.json
Since i haven't found a decent solution for the poster bug yet, i make the poster errors into warnings so that it will not fail the fidelity test. The first fidelity test happened to detect both errors and warnings.
=>  track semi transparent pixels

packages/model-viewer/src/features/staging.ts, packages/modelviewer.dev/index.html
=> Add rotation-per-second attribute

packages/model-viewer/src/features/ar.ts, packages/model-viewer/src/test/features/ar-spec.ts
Fixes #1494 
Fixes #1495 
Fixes #1496 
Sorry all, this was just a stupid typo.
=> Fix QuickLook

packages/model-viewer/src/features/controls.ts, packages/model-viewer/src/three-components/SmoothControls.ts, packages/modelviewer.dev/index.html
Fixes #1498 
Does this look like what you're after @FelipeR2U? Maybe just look at the description in index.html; I did a bunch of cleanup that complicates the diff, but the real change was tiny, just the first commit.
=> added orbit-sensitivity attribute

packages/model-viewer/src/three-components/Renderer.ts
Fixes #1503 
Well, I can't repro the issue so I can't be sure, but this seems a likely fix. @hybridherbst Can you verify this fix before I merge?
=> round canvas size

packages/modelviewer.dev/examples/annotations.html, packages/modelviewer.dev/examples/lighthouse.html, packages/modelviewer.dev/examples/webxr.html, packages/modelviewer.dev/index.html, packages/render-fidelity-tools/test/results-viewer.html
This adds an example of best practices for good lighthouse scores. I'm going to make this available, but not link it from modelviewer.dev yet, as I want to get some feedback first on my recommendations first.
=> Lighthouse example

packages/model-viewer/src/three-components/SmoothControls.ts, packages/modelviewer.dev/examples/accessibility.html, packages/modelviewer.dev/examples/add.html, packages/modelviewer.dev/examples/animation.html, packages/modelviewer.dev/examples/annotations.html, packages/modelviewer.dev/examples/augmented-reality.html, packages/modelviewer.dev/examples/customizing-ui.html, packages/modelviewer.dev/examples/fuzzer.html, packages/modelviewer.dev/examples/lazy-loading.html, packages/modelviewer.dev/examples/lighthouse.html, packages/modelviewer.dev/examples/lighting-and-environment.html, packages/modelviewer.dev/examples/list.html, packages/modelviewer.dev/examples/model-formats.html, packages/modelviewer.dev/examples/multiple-elements.html, packages/modelviewer.dev/examples/rendering-showcase.html, packages/modelviewer.dev/examples/scene-graph.html, packages/modelviewer.dev/examples/staging-and-camera-control.html, packages/modelviewer.dev/examples/tester.html, packages/modelviewer.dev/examples/webxr.html, packages/modelviewer.dev/index.html, packages/render-fidelity-tools/test/results-viewer.html, packages/space-opera/editor/index.html
Updating our dev pages to fix accessibility, best practices and SEO scores up to 100.
=> fixed non-performance lighthouse stats

packages/modelviewer.dev/examples/lighthouse.html
Scores of 100 across the board now!
=> lazy load model-viewer for lighthouse example

packages/model-viewer/src/test/three-components/Renderer-spec.ts, packages/model-viewer/src/three-components/Renderer.ts
=> Fix further canvas rounding issues

packages/model-viewer/src/test/three-components/Renderer-spec.ts, packages/model-viewer/src/three-components/Renderer.ts
Reverts google/model-viewer#1542
=> Revert "Fix further canvas rounding issues"

packages/modelviewer.dev/examples/staging-and-camera-control.html
=> fixed pan example errors

packages/modelviewer.dev/examples/lighthouse.html
Example progress bar based on: https://twitter.com/modelviewer/status/1306671314749464578
=> Progress bar updated

package-lock.json, package.json, packages/3dom/package-lock.json, packages/3dom/package.json, packages/editing-adapter/package-lock.json, packages/editing-adapter/package.json, packages/model-viewer/package-lock.json, packages/model-viewer/package.json, packages/modelviewer.dev/package-lock.json, packages/modelviewer.dev/package.json, packages/render-fidelity-tools/package-lock.json, packages/render-fidelity-tools/package.json, packages/space-opera/package-lock.json, packages/space-opera/package.json, packages/space-opera/src/redux/space_opera_base_test.ts
=> update TS to 4.0

packages/editing-adapter/package-lock.json, packages/model-viewer/package-lock.json, packages/modelviewer.dev/package-lock.json, packages/render-fidelity-tools/package-lock.json, packages/space-opera/package-lock.json
Just a test. Looks like my npm had gotten into a bad state, which I believe I've now resolved by deleting all my node_modules folders and doing a fresh npm install and npm bootstrap.
=> small package update

packages/modelviewer.dev/src/docs-and-examples/sidebar.ts, packages/modelviewer.dev/src/docs-and-examples/utils.ts, packages/modelviewer.dev/styles/docs.css
Switch HTML scroll behavior to auto.
* Going to a docs/examples link with a # will now automatically jump you to the section. 
* Jumping between sections is automatic.
looking for a general code review to merge
=> # Jump to Section

packages/modelviewer.dev/examples/accessibility.html, packages/modelviewer.dev/examples/add.html, packages/modelviewer.dev/examples/animation.html, packages/modelviewer.dev/examples/annotations.html, packages/modelviewer.dev/examples/augmented-reality.html, packages/modelviewer.dev/examples/customizing-ui.html, packages/modelviewer.dev/examples/fuzzer.html, packages/modelviewer.dev/examples/lazy-loading.html, packages/modelviewer.dev/examples/lighting-and-environment.html, packages/modelviewer.dev/examples/list.html, packages/modelviewer.dev/examples/model-formats.html, packages/modelviewer.dev/examples/multiple-elements.html, packages/modelviewer.dev/examples/rendering-showcase.html, packages/modelviewer.dev/examples/scene-graph.html, packages/modelviewer.dev/examples/staging-and-camera-control.html, packages/modelviewer.dev/examples/tester.html, packages/modelviewer.dev/index.html, packages/render-fidelity-tools/test/results-viewer.html, packages/space-opera/editor/index.html
Reverts google/model-viewer#1580
We're really just looking for visit counting; something that's adding cookies is much more than we need.
=> Revert "Add Google Analytics tracking code"

packages/modelviewer.dev/data/docs.json, packages/modelviewer.dev/data/examples.json, packages/modelviewer.dev/docs/index.html, packages/modelviewer.dev/examples/animation/index.html, packages/modelviewer.dev/examples/loading/index.html, packages/modelviewer.dev/src/docs-and-examples/create-html.ts, packages/modelviewer.dev/src/docs-and-examples/sidebar.ts, packages/modelviewer.dev/styles/docs.css, packages/modelviewer.dev/styles/examples.css
change hover sidebar, general review
=> change hover sidebar

packages/modelviewer.dev/docs/index.html, packages/modelviewer.dev/examples/animation/index.html, packages/modelviewer.dev/examples/loading/index.html, packages/modelviewer.dev/src/docs-and-examples/create-html.ts, packages/modelviewer.dev/src/docs-and-examples/sidebar.ts, packages/modelviewer.dev/src/docs-and-examples/utils.ts, packages/modelviewer.dev/styles/docs.css, packages/modelviewer.dev/styles/examples.css
Updating CSS to make mobile friendly docs,
Added subcategory to sticky header 
Updated model viewer in top-left of docs to be < model-viewer >
-- general pull request, basic feedback on functionality and code
=> Mobile Friendly & Sticky subcategories

packages/modelviewer.dev/src/docs-and-examples/create-html.ts, packages/modelviewer.dev/src/docs-and-examples/sidebar.ts, packages/modelviewer.dev/src/docs-and-examples/utils.ts, packages/modelviewer.dev/styles/docs.css, packages/modelviewer.dev/styles/examples.css
Sidebar bug fixes and CSS updates to header and layout on mobile.
What's not in this PR:
* Examples header on mobile to flip between sidebar/ no sidebar
* Update toggle button to be it's own column and only on mobile instead of desktop
-- looking for general code review
=> Sidebar clicking on small section bug fix

packages/modelviewer.dev/docs/index.html, packages/modelviewer.dev/examples/animation/index.html, packages/modelviewer.dev/examples/loading/index.html, packages/modelviewer.dev/src/docs-and-examples/create-html.ts, packages/modelviewer.dev/src/docs-and-examples/sidebar.ts, packages/modelviewer.dev/src/docs-and-examples/utils.ts, packages/modelviewer.dev/styles/docs.css, packages/modelviewer.dev/styles/examples.css
* Add header to mobile examples
* Close sidebar, after sidebar click
=> Add header to mobile examples

packages/modelviewer.dev/data/docs.json, packages/modelviewer.dev/data/examples.json, packages/modelviewer.dev/docs/index.html, packages/modelviewer.dev/examples/annotations/index.html, packages/modelviewer.dev/examples/augmentedreality/index.html, packages/modelviewer.dev/examples/lightingandenv/index.html, packages/modelviewer.dev/examples/loading/index.html, packages/modelviewer.dev/examples/scenegraph/index.html, packages/modelviewer.dev/examples/stagingandcameras/index.html, packages/modelviewer.dev/index.html, packages/modelviewer.dev/src/docs-and-examples/create-html.ts, packages/modelviewer.dev/src/docs-and-examples/sidebar.ts, packages/modelviewer.dev/src/docs-and-examples/utils.ts, packages/modelviewer.dev/styles/docs.css, packages/modelviewer.dev/styles/examples.css
Filling in he json files and creating all of the examples files
=> Adding docs

packages/modelviewer.dev/docs/index.html, packages/modelviewer.dev/src/docs-and-examples/create-html.ts, packages/modelviewer.dev/src/docs-and-examples/sidebar.ts, packages/modelviewer.dev/styles/docs.css, packages/modelviewer.dev/styles/examples.css
fix sidebar bug where you click on element in same category and it closes subcategories
=> Sidebar bugs

packages/modelviewer.dev/data/docs.json
I removed 'poster-dismissed' because I'm not entirely sure I want it in the API yet. Everything else looking good?
=> Adding missing descriptions

packages/space-opera/package-lock.json, packages/space-opera/package.json, packages/space-opera/src/redux/space_opera_base.ts
adding redux devtools
--general review of content
=> add redux devtools

packages/modelviewer.dev/data/docs.json, packages/modelviewer.dev/src/docs-and-examples/create-html.ts, packages/modelviewer.dev/styles/examples.css
- update docs with new information
- remove table "type"
- add css for attributes
=> Docs updates

packages/modelviewer.dev/data/docs.json, packages/modelviewer.dev/src/docs-and-examples/create-html.ts, packages/modelviewer.dev/styles/docs.css
=> remove parenthesis from sidebar methods

packages/modelviewer.dev/examples/augmentedreality/index.html, packages/modelviewer.dev/styles/examples.css
update font size for increased readability
=> update font size

packages/space-opera/src/components/shared/expandable_content/expandable_section.css.ts
fix expandable content:
* eases
* properties transition correctly
* content stays hidden when opening
=> fix expandable content

packages/modelviewer.dev/home.html, packages/modelviewer.dev/styles/examples.css
update home page based on new design
=> update home page

packages/model-viewer/src/features/loading.ts, packages/model-viewer/src/test/features/loading-spec.ts, packages/modelviewer.dev/data/docs.json
=> added getDimensions()

packages/modelviewer.dev/scripts/ci-before-deploy.sh
=> deploy home-page

packages/space-opera/src/components/shared/expandable_content/expandable_section.css.ts
=> quick-fix for color picker

packages/modelviewer.dev/data/docs.json
Found some errors and things I wanted to be clearer.
=> various docs edits

packages/modelviewer.dev/scripts/ci-before-deploy.sh
remove html from deploy script
=> remove html from deploy script

packages/modelviewer.dev/data/docs.json, packages/modelviewer.dev/data/examples.json, packages/modelviewer.dev/examples/animation/index.html, packages/modelviewer.dev/examples/annotations/index.html, packages/modelviewer.dev/examples/augmentedreality/index.html, packages/modelviewer.dev/examples/lightingandenv/index.html, packages/modelviewer.dev/examples/loading/index.html, packages/modelviewer.dev/examples/scenegraph/index.html, packages/modelviewer.dev/examples/stagingandcameras/index.html, packages/modelviewer.dev/src/docs-and-examples/create-html.ts, packages/modelviewer.dev/src/docs-and-examples/sidebar.ts
=> Fix updated examples

packages/space-opera/src/components/ibl_selector/ibl_selector.css.ts, packages/space-opera/src/components/ibl_selector/ibl_selector.ts, packages/space-opera/src/components/model_viewer_preview/gltf_edits.ts, packages/space-opera/src/components/model_viewer_preview/model_viewer_preview.ts, packages/space-opera/src/components/model_viewer_snippet/components/open_button.ts, packages/space-opera/src/components/model_viewer_snippet/model_viewer_snippet.ts, packages/space-opera/src/components/shared/snippet_viewer/snippet_viewer.ts
=> miscellaneous changes

packages/render-fidelity-tools/test/results-viewer.html
=> make logo visible

packages/space-opera/src/components/model_viewer_preview/model_viewer_preview.ts
=> fix material not updating

packages/model-viewer/src/features/loading.ts, packages/modelviewer.dev/data/docs.json
The real test of this is if it allows us to simplify the editor.
=> add showPoster method

packages/space-opera/editor/index.html, packages/space-opera/src/components/camera_settings/components/limits_base.ts, packages/space-opera/src/components/file_modal/file_modal.ts, packages/space-opera/src/components/home/home.ts, packages/space-opera/src/components/ibl_selector/ibl_selector.ts, packages/space-opera/src/components/inspector/inspector.ts, packages/space-opera/src/components/materials_panel/materials_panel.ts, packages/space-opera/src/components/model_viewer_snippet/components/download_button.ts, packages/space-opera/src/components/model_viewer_snippet/components/open_button.ts, packages/space-opera/src/components/model_viewer_snippet/model_viewer_snippet.ts, packages/space-opera/src/components/shared/card/card.ts, packages/space-opera/src/components/shared/color_picker/color_map.css.ts, packages/space-opera/src/components/shared/color_picker/color_picker.css.ts, packages/space-opera/src/components/shared/expandable_content/expandable_section.css.ts, packages/space-opera/src/components/shared/expandable_content/expandable_tab.css.ts, packages/space-opera/src/components/shared/expandable_content/expandable_tab.ts, packages/space-opera/src/components/shared/section_row/section_row.css.ts, packages/space-opera/src/components/shared/texture_picker/texture_picker.css.ts, packages/space-opera/src/components/shared/texture_picker/texture_picker.ts, packages/space-opera/src/styles.css.ts, packages/space-opera/src/test/shared/texture_picker/texture_picker_test.ts
* expandable content carrots vertically aligned
=> UI Feedback

packages/model-viewer/src/model-viewer-base.ts, packages/model-viewer/src/test/decorators-spec.ts, packages/model-viewer/src/test/features/animation-spec.ts, packages/model-viewer/src/test/features/annotation-spec.ts, packages/model-viewer/src/test/features/ar-spec.ts, packages/model-viewer/src/test/features/controls-spec.ts, packages/model-viewer/src/test/features/environment-spec.ts, packages/model-viewer/src/test/features/loading-spec.ts, packages/model-viewer/src/test/features/staging-spec.ts, packages/model-viewer/src/test/helpers.ts, packages/model-viewer/src/test/model-viewer-base-spec.ts, packages/model-viewer/src/test/templates.ts, packages/model-viewer/src/utilities.ts
@chrismgeorge Can you check if this fixes your Glitch?
=> delay load event until jumpCameraToGoal() can execute

packages/model-viewer/src/features/ar.ts, packages/model-viewer/src/features/scene-graph.ts, packages/model-viewer/src/test/features/environment-spec.ts, packages/model-viewer/src/test/three-components/ARRenderer-spec.ts, packages/model-viewer/src/test/three-components/ModelScene-spec.ts, packages/model-viewer/src/three-components/ARRenderer.ts, packages/model-viewer/src/three-components/Model.ts, packages/model-viewer/src/three-components/ModelScene.ts, packages/model-viewer/src/three-components/PlacementBox.ts, packages/model-viewer/src/three-components/Shadow.ts, packages/modelviewer.dev/data/docs.json, packages/modelviewer.dev/data/examples.json, packages/modelviewer.dev/examples/augmentedreality/index.html
Fixes #687 
I'm taking the simple approach for now, outlined helpfully in this comment: https://github.com/google/model-viewer/issues/687#issuecomment-683315689, where we now have an attribute `ar-placement` which can be either `"wall"` or the default `"floor"`. This also configures SceneViewer to use vertical placement. QuickLook is not configurable on the intent side as far as I'm aware.
=> Vertical ar

packages/model-viewer/src/three-components/ARRenderer.ts
Missed a significant bug from #1714, which is fixed here. The logic was very fragile before, hence why the last PR broke it. Makes a bit more sense now.
=> fix broken floor placement

packages/model-viewer/src/features/annotation.ts, packages/model-viewer/src/features/controls.ts, packages/model-viewer/src/template.ts, packages/model-viewer/src/three-components/ARRenderer.ts, packages/model-viewer/src/three-components/Hotspot.ts, packages/modelviewer.dev/data/examples.json, packages/modelviewer.dev/examples/annotations/index.html
In addition to being a new hotspots example, this also fixes some bugs found by exercising some edge cases here.
=> Dimensions example

packages/editing-adapter/src/gltf/gltf_model.ts, packages/editing-adapter/src/gltf/gltf_model_test.ts, packages/model-viewer/karma.conf.js, packages/model-viewer/src/features/scene-graph/api.ts, packages/model-viewer/src/features/scene-graph/material.ts, packages/model-viewer/src/features/scene-graph/pbr-metallic-roughness.ts, packages/space-opera/src/components/materials_panel/material_state.ts, packages/space-opera/src/test/space_opera_base_test.ts
This was one of the gaps between scene-graph and editing-adapter and it was blocking some new UI in the editor, so it got higher priority.
=> added setEmissiveFactor to scene-graph API

packages/space-opera/src/components/camera_settings/camera_settings.ts, packages/space-opera/src/components/camera_settings/reducer.ts, packages/space-opera/src/components/materials_panel/materials_panel.ts, packages/space-opera/src/components/model_viewer_snippet/components/open_button.ts, packages/space-opera/src/test/camera_settings/camera_settings_test.ts, packages/space-opera/src/test/materials_panel/materials_panel_test.ts, packages/space-opera/src/test/shared/tabs/tabs_test.ts, packages/space-opera/src/test/space_opera_base_test.ts
* Cleaned up the PR that removed the initial camera
* Added feature that highlights selected material chosen, and then quickly interpolates back to original material, example here: https://drive.google.com/file/d/1qPvb3iifIFePYKe3UsYKC0w6uMyA2YS4/view?usp=sharing
=> Visualize Selected Material

packages/model-viewer/src/features/scene-graph.ts, packages/model-viewer/src/features/scene-graph/material.ts, packages/model-viewer/src/three-components/gltf-instance/correlated-scene-graph.ts, packages/model-viewer/src/three-components/gltf-instance/gltf-2.0.ts, packages/modelviewer.dev/data/docs.json, packages/modelviewer.dev/data/examples.json, packages/modelviewer.dev/examples/scenegraph/index.html
Added support for KHR_materials_variants extension.
=> add variants support

packages/model-viewer/src/features/ar.ts, packages/model-viewer/src/test/features/ar-spec.ts
Fixes #1732 
Thanks for pointing me right to the solution!
=> allow hashes appended to quickLook

packages/modelviewer.dev/examples/stagingandcameras/index.html
=> fixed pan example

packages/model-viewer/src/features/controls.ts, packages/model-viewer/src/features/loading.ts, packages/model-viewer/src/features/staging.ts, packages/model-viewer/src/model-viewer-base.ts, packages/model-viewer/src/styles/style-effector.ts
=> removed indirection in event handlers

packages/model-viewer/src/three-components/Model.ts
=> fix erroneous animation warning

packages/model-viewer/src/features/controls.ts, packages/model-viewer/src/features/scene-graph.ts, packages/model-viewer/src/features/scene-graph/api.ts, packages/model-viewer/src/test/three-components/ModelScene-spec.ts, packages/model-viewer/src/test/three-components/ModelUtils-spec.ts, packages/model-viewer/src/three-components/ARRenderer.ts, packages/model-viewer/src/three-components/Model.ts, packages/model-viewer/src/three-components/ModelScene.ts, packages/model-viewer/src/three-components/ModelUtils.ts, packages/model-viewer/src/three-components/Renderer.ts, packages/modelviewer.dev/data/docs.json, packages/modelviewer.dev/data/examples.json, packages/modelviewer.dev/examples/scenegraph/index.html
Fixes #426
Fixes #1118 
Fixes #1724 
This adds an orientation attribute specified as Euler angles and a 3-element scale attribute.
=> Add orientation and scale attributes

packages/space-opera/src/components/mobile_view/open_mobile_view.ts, packages/space-opera/src/components/model_viewer_snippet/model_viewer_snippet.ts
Removes id in URL to display mobile section
=> Unflag mobile section

packages/model-viewer/src/three-components/ModelScene.ts
=> fixed shadow

packages/space-opera/editor/index.html
=> Adjusting pannel height because of modelviewer header

packages/space-opera/src/components/materials_panel/material_state.ts, packages/space-opera/src/components/materials_panel/materials_panel.ts
=> bug fix: horse flickers when loaded after model

packages/space-opera/src/components/best_practices/render_best_practices.ts, packages/space-opera/src/components/best_practices/styles.css.ts, packages/space-opera/src/components/mobile_view/mobile_view.ts, packages/space-opera/src/components/mobile_view/reducer.ts, packages/space-opera/src/components/model_viewer_preview/model_viewer_preview.ts, packages/space-opera/src/components/model_viewer_preview/reducer.ts, packages/space-opera/src/styles.css.ts
Fixed bugs from Best Practices #1842 ::
* Hand prompt wasn't animated in WebXR
* The progress bar didn't render on mobile session from the editor
* The hand ar prompt would render on the editor main screen, removed it
=> editor-mobile fixes w/ best practices

packages/modelviewer.dev/data/docs.json
retuned -> returned 
horizotal -> horizontal
=> Fix some typos in docs.json

packages/space-opera/src/components/model_viewer_snippet/components/validation.ts, packages/space-opera/src/components/model_viewer_snippet/components/validation_utils.ts
I removed `any`.
https://github.com/google/model-viewer/blob/4c719c09253a646b248c6693e32c38c7d90eeda8/packages/space-opera/src/components/model_viewer_snippet/components/validation.ts#L30
https://github.com/google/model-viewer/blob/4c719c09253a646b248c6693e32c38c7d90eeda8/packages/space-opera/src/components/model_viewer_snippet/components/validation.ts#L131
=> Define Report type

packages/model-viewer/src/features/ar.ts, packages/model-viewer/src/test/features/ar-spec.ts
Fixes #2093 and some related problems. Also cleans up the code since we don't have to worry about IE11 support anymore.
=> Fix SceneViewer intent params

packages/model-viewer/src/features/ar.ts
I have encoded the url of model before adding it to the intent.
Fixes #1095
=> cloudfront url issue cleared

packages/modelviewer.dev/index.html
Mentioning Safari specifically since it is not an evergreen browser.
=> update browser support

packages/model-viewer/src/three-components/gltf-instance/ModelViewerGLTFInstance.ts
=> fixed transparency duplication bug

README.md
Adds some helpful Windows 10 setup info
=> Windows 10 install info

packages/model-viewer/src/features/loading.ts, packages/model-viewer/src/model-viewer-base.ts, packages/model-viewer/src/test/three-components/Renderer-spec.ts, packages/model-viewer/src/three-components/Renderer.ts
I noticed that #2300 introduced a regression where offscreen elements are getting rendered. In debugging I found a couple of other small errors, so I'm adding several regression tests. I'm opening this PR early so I can verify other browsers are behaving consistently. Next I'll fix them and then merge.
=> Fix render timing

packages/model-viewer/src/features/loading.ts
=> updated basis decoder version

packages/model-viewer/src/features/animation.ts
Fixes #2338 
I believe this will fix the problem, though without a repro link it's a little hard to say if there's anything left to solve here.
=> ensure animations play in AR

packages/model-viewer/src/test/three-components/Renderer-spec.ts, packages/model-viewer/src/three-components/Renderer.ts, packages/model-viewer/src/three-components/SmoothControls.ts
Improves our Renderer-spec by making a more end-to-end test. Also fixes an issue with updating the camera for an external renderer.
=> fix external renderer

packages/model-viewer/src/features/ar.ts
Fixes #2381 
Thanks @60days for finding the quick work-around. Scene Viewer has also fixed the underlying issue, but this will keep us from having to wait a couple weeks for that to roll out.
=> workaround for scene-viewer bug

packages/model-viewer/src/three-components/gltf-instance/ModelViewerGLTFInstance.ts
=> Possible fix for textures that appear fully glossy or black

packages/modelviewer.dev/examples/stagingandcameras/index.html
Fixing a couple of the examples to work with USDZ autogeneration better.
=> Examples update for iOS

packages/model-viewer/src/constants.ts, packages/model-viewer/src/model-viewer-base.ts, packages/model-viewer/src/styles/conversions.ts, packages/model-viewer/src/styles/parsers.ts, packages/model-viewer/src/test/three-components/Renderer-spec.ts, packages/model-viewer/src/three-components/ARRenderer.ts, packages/model-viewer/src/three-components/ModelScene.ts, packages/model-viewer/src/three-components/Renderer.ts, packages/model-viewer/src/utilities.ts, packages/render-fidelity-tools/src/artifact-creator.ts, packages/render-fidelity-tools/src/common.ts, packages/render-fidelity-tools/src/components/renderer-harness.ts, packages/render-fidelity-tools/src/components/renderers/filament-viewer.ts, packages/render-fidelity-tools/src/workflows/update-screenshots.ts, packages/space-opera/src/components/config/reducer.ts, packages/space-opera/src/components/materials_panel/material_state.ts, packages/space-opera/src/components/materials_panel/reducer.ts, packages/space-opera/src/components/mobile_view/mobile_view.ts, packages/space-opera/src/components/mobile_view/open_mobile_view.ts, packages/space-opera/src/components/model_viewer_snippet/components/download_button.ts, packages/space-opera/src/components/model_viewer_snippet/components/open_button.ts, packages/space-opera/src/test/materials_panel/materials_panel_test.ts
Finally getting around to fixing most of the issues that LGTM found: https://lgtm.com/projects/g/google/model-viewer/?mode=list&severity=error
Thanks for pointing me to that tool, @mrdoob!
=> Minor code cleanup

packages/model-viewer/src/features/annotation.ts, packages/model-viewer/src/three-components/ARRenderer.ts, packages/model-viewer/src/three-components/ModelScene.ts, packages/model-viewer/src/three-components/Renderer.ts
This further cleans up our camera code now that we're using XRManager.
=> Refactor xrCamera

packages/editing-adapter/package-lock.json, packages/model-viewer/package-lock.json, packages/model-viewer/package.json, packages/model-viewer/src/test/three-components/gltf-instance/ModelViewerGLTFInstance-spec.ts, packages/model-viewer/src/three-components/gltf-instance/ModelViewerGLTFInstance.ts, packages/modelviewer.dev/package-lock.json, packages/render-fidelity-tools/package-lock.json, packages/space-opera/package-lock.json, packages/space-opera/package.json
Also removes our hack to get transparent materials working properly now that three.js does this for us.
=> Three.js r130

packages/model-viewer/src/features/scene-graph.ts, packages/model-viewer/src/test/features/scene-graph-spec.ts, packages/shared-assets/models/cubes.gltf
Adding some tests for variant import/export, @takahirox.
=> Variant tests

packages/modelviewer.dev/scripts/ci-before-deploy.sh
Forgot to remove them from the deploy script, which then choked...
=> fix Deploy by removing unneeded polyfills

packages/model-viewer/src/features/scene-graph/material.ts, packages/model-viewer/src/features/scene-graph/pbr-metallic-roughness.ts
false-positive check generating erroneous logs
=> fix comparison generating false-positive

packages/model-viewer/src/features/scene-graph/api.ts, packages/model-viewer/src/features/scene-graph/material.ts, packages/model-viewer/src/features/scene-graph/pbr-metallic-roughness.ts, packages/model-viewer/src/test/features/scene-graph/material-spec.ts, packages/model-viewer/src/three-components/gltf-instance/ModelViewerGLTFInstance.ts
Adds API for getting/setting alphaCutoff, doubleSided, and alphaMode.
Adresses: #2558 
Fixes #1661
=> Adding doubleSided and alphaCutoff API

packages/model-viewer/src/three-components/Renderer.ts
=> Minor fix for singleton pattern

packages/space-opera/src/test/animation_controls/animation_controls_test.ts, packages/space-opera/src/test/camera_settings/components/pitch_limits_test.ts, packages/space-opera/src/test/camera_settings/components/yaw_limits_test.ts, packages/space-opera/src/test/inspector/inspector_test.ts, packages/space-opera/src/test/materials_panel/materials_panel_test.ts
=> Deflake editor tests

packages/space-opera/src/components/camera_settings/components/limits_base.ts
More attempted deflaking of editor tests.
=> robustify limit rendering

packages/model-viewer/src/features/scene-graph.ts, packages/model-viewer/src/features/scene-graph/material.ts, packages/model-viewer/src/features/scene-graph/pbr-metallic-roughness.ts, packages/model-viewer/src/three-components/gltf-instance/correlated-scene-graph.ts
@timmmeh I know you're out this week, but I'd like you to review this when you get back so the changes don't surprise you.
=> cleanup and fixed an onUpdate variants bug

packages/space-opera/src/components/animation_controls/animation_controls.ts, packages/space-opera/src/components/best_practices/styles.css.ts, packages/space-opera/src/components/camera_settings/camera_settings.ts, packages/space-opera/src/components/mobile_view/components/mobile_expandable_section.ts, packages/space-opera/src/components/model_viewer_preview/model_viewer_preview.ts, packages/space-opera/src/components/model_viewer_snippet/components/open_button.ts
Fixes #1508 and a bunch of other small issues. I removed some UI that I find distracting (since there's hardly any reason to change it). Also removed USDZ upload since we do auto-generation now for Quick Look.
=> Editor UX improvements

packages/model-viewer/src/features/scene-graph/pbr-metallic-roughness.ts, packages/model-viewer/src/features/scene-graph/texture-info.ts, packages/model-viewer/src/test/features/scene-graph/material-spec.ts
Fixes #2654 
@timmmeh We have an astute observer who noticed a pretty subtle bug in the new scene-graph API prior to release. I tightened up the testing a bit, but the fix was a one-liner.
=> Fix roughnessMap bug in scene-graph API

packages/model-viewer/package.json, packages/model-viewer/rollup.config.js
For those who don't support modules; hopefully this is rare.
=> added umd-min version

packages/model-viewer/src/features/loading.ts
Finally remembered to update this...
=> update DRACO decoder to v1.4.1

packages/space-opera/src/test/materials_panel/materials_panel_test.ts
changed timeout from 5sec  to 10sec, hoping that fixes the space-opera timeout failures.
=> increase material panel test timeout

packages/space-opera/karma.conf.js, packages/space-opera/src/test/materials_panel/materials_panel_test.ts
Try setting in karma instead, since the last one didn't seem to actually change the timeout.
=> Test flake2

packages/model-viewer/src/three-components/gltf-instance/gltf-2.0.ts, packages/model-viewer/src/three-components/gltf-instance/gltf-defaulted.ts, packages/space-opera/src/components/model_viewer_snippet/components/validation.ts, packages/space-opera/src/components/model_viewer_snippet/components/validation_utils.ts
This was an internal feature request for validating animated models.
=> added joint count to editor validation

packages/model-viewer/src/three-components/gltf-instance/gltf-2.0.ts, packages/model-viewer/src/three-components/gltf-instance/gltf-defaulted.ts, packages/space-opera/src/components/config/reducer.ts, packages/space-opera/src/components/mobile_view/reducer.ts, packages/space-opera/src/components/model_viewer_preview/model_viewer_preview.ts, packages/space-opera/src/components/model_viewer_snippet/components/open_button.ts, packages/space-opera/src/components/model_viewer_snippet/model_viewer_snippet.ts, packages/space-opera/src/types.ts
Fixing some poorly managed config state; now the correct defaults are applied regardless of how you load a model. Also verified that Zip files are indeed supported.
=> Editor snippet default fixes

packages/model-viewer/src/features/scene-graph/nodes/primitive-node.ts
Patches association issue with skinned-mesh
=> Patch to resolve mapping issue on skinned meshes

packages/model-viewer/src/features/scene-graph/nodes/primitive-node.ts
Patch on patch - resolved skinned mesh loading in the editor
Fixes #2798 <- Adding this line will automatically link and close the issue when this PR is merged.
=> Patch on skinned mesh loading patch

packages/model-viewer/src/three-components/ModelScene.ts
Fixes #2786 / #2784 
Oops, missed a new function call during my recent refactor.
=> fixed shadow on src update

packages/model-viewer/src/features/scene-graph/material.ts
Adding fix for alpha test
Fixes #2931
=> Adding fix for alpha test issue #2931

packages/modelviewer.dev/examples/scenegraph/index.html
=> Doc(3033): fix the alt and id attributes on some examples

packages/model-viewer/src/test/features/scene-graph/model-spec.ts
Adds tests for new variant functionality
=> Tests to cover new model.ts functionality

packages/modelviewer.dev/examples/loading/index.html, packages/space-opera/src/components/model_viewer_preview/model_viewer_preview.ts
=> added meshopt support to editor

packages/model-viewer/src/model-viewer-base.ts, packages/model-viewer/src/test/utilities/progress-tracker-spec.ts, packages/model-viewer/src/three-components/TextureUtils.ts, packages/model-viewer/src/utilities/progress-tracker.ts
Follow-up to #3110, fixing an error in the math, and adding a test  to catch it. Also removed an unnecessary activity so that total progress is more accurate.  FYI @mehak08g.
=> fixed progress-tracker math

packages/modelviewer.dev/examples/twitter/generator.js, packages/modelviewer.dev/examples/twitter/player.html
Leaked an event listener. Also adding auto-rotate to default player options.
=> fixed twitter card generator download button

packages/modelviewer.dev/scripts/ci-before-deploy.sh
Forgot to deploy. It's really time we  fixed  our deployment strategy to make this more automatic.
=> fix deployment

packages/model-viewer/src/features/animation.ts, packages/model-viewer/src/three-components/ModelScene.ts, packages/modelviewer.dev/data/docs.json, packages/modelviewer.dev/data/examples.json, packages/modelviewer.dev/examples/animation/index.html
Fixes #3125 
- add `timeScale` property
- You can change animation speed. If you set to a negative value (ex. `-2`), the animation play reverse.
- fix last frame position when the animation played a specified number of time
- Always stop the animation at the last frame when it ends.
=> Enable to change animation speed

packages/model-viewer/src/features/controls.ts
Fixes #3068 
- Prevented the camera from moving during AR in WebXR mode
=> The camera cannot be moved during AR

package-lock.json, packages/model-viewer/package-lock.json, packages/model-viewer/package.json, packages/modelviewer.dev/package-lock.json, packages/render-fidelity-tools/package-lock.json, packages/space-opera/package-lock.json
Fixes #3188 
Our `package.json` was not set up properly for use of our `/lib`. Thanks for the tip @justinfagnani; does this look right to you? The `main` and `module` parts are especially opaque to me, so it'd be great to have more experienced eyes on those. We've gotten a lot of complaints from TS users in frameworks I'm not familiar with.
=> fixing dependencies

packages/modelviewer.dev/examples/ux-pan.html, packages/modelviewer.dev/styles/ux-test.css
Slight tweaks for some UX testing.
=> update style for UX

packages/modelviewer.dev/examples/scenegraph/index.html
=> Updated the alt description for the duck example to address #3217

packages/model-viewer/src/test/three-components/ModelScene-spec.ts, packages/model-viewer/src/three-components/ModelScene.ts, packages/model-viewer/src/three-components/Renderer.ts, packages/model-viewer/src/three-components/gltf-instance/ModelViewerGLTFInstance.ts
Following @mrdoob's advice: https://github.com/google/model-viewer/pull/3152#issuecomment-1022418169
=> tone map clean up

packages/space-opera/src/components/model_viewer_snippet/components/validation.ts
Forgot to push my last commit to #3247.
=> minor update

packages/model-viewer/src/features/scene-graph/texture-info.ts
Fixes #3240 
This maintains any texture transforms on the texture info slot and applies them to any textures that are set on that slot. We can also expose this as an API later, though I'll wait for user demand.
=> retain texture transform info

package-lock.json, packages/model-viewer/package-lock.json, packages/modelviewer.dev/package-lock.json, packages/render-fidelity-tools/package-lock.json, packages/render-fidelity-tools/package.json, packages/space-opera/package-lock.json
Hoping this takes care of dependabot's warnings. Also updated the gltf-sample-viewer so that axios doesn't break our build every time we update.
=> updated package-lock

packages/model-viewer/src/features/controls.ts
Fixes #3331 
This is what I get for using old web APIs. The new ones really are better...
=> fix context menu

packages/model-viewer/src/test/features/animation-spec.ts, packages/model-viewer/src/three-components/ModelScene.ts, packages/modelviewer.dev/data/docs.json
Fixes #3326 
This change is really a one-liner with a couple of added tests, but it looks bigger because one of the files wasn't formatted.
=> fixed pause resetting animation

packages/model-viewer/package-lock.json, packages/model-viewer/package.json, packages/render-fidelity-tools/package-lock.json, packages/space-opera/package-lock.json
=> updated to r139

packages/modelviewer.dev/data/docs.json
Fixes #3394 
The font made the "i" in "In" look like another "L"
=> Add pronunciation of modelIsVisible due to font

packages/model-viewer/src/features/controls.ts, packages/model-viewer/src/template.ts, packages/model-viewer/src/test/features/controls-spec.ts, packages/model-viewer/src/three-components/SmoothControls.ts
Fixes a couple of interaction prompt regressions from #3320. Deferring the prompt was not working correctly and the prompt was staying visible incorrectly.
=> fixed default interaction prompt

packages/model-viewer/src/features/controls.ts
During iOS testing, I found the synthetic interaction was not smooth, particularly for pan. It appeared to stair-step, moving slightly in the X followed by Y. This shouldn't happen since on each requestAnimationFrame, two pointer events are fired, which individually update the pan/zoom but the resulting camera pos shouldn't be rendered until the next animation frame. It looks like perhaps due to losing frames these are not always being processed in sync. 
The solution I've chosen here is to remove some complexity: I had been setting the interpolationDecay to zero during a synthetic interaction, since they are already smooth. However, this allows small jitters to make it into the camera; keeping the default 50ms smooths out any small stair-steps. Also, I think this actually makes better …
=> consistent interpolationDecay for synthetic interaction

packages/modelviewer.dev/data/docs.json
This feature was actually shipped several versions ago for an internal project, but I'm finally documenting it publicly as the API seems to be stable and shouldn't require breaking changes.
=> added external renderer docs

packages/modelviewer.dev/examples/augmentedreality/index.html, packages/modelviewer.dev/examples/scenegraph/index.html
Some small fixes, also helpful for checking the current status of BrowserStack.
=> updated examples

packages/model-viewer/src/features/environment.ts, packages/model-viewer/src/three-components/ARRenderer.ts, packages/model-viewer/src/three-components/ModelScene.ts
Fixes #3415 
I fixed this by centralizing how the environment image and skybox are applied. This fixes this bug and generally makes the code clearer and more robust.
=> refactored environment/skybox setup

packages/model-viewer/src/features/controls.ts, packages/model-viewer/src/test/features/controls-spec.ts, packages/render-fidelity-tools/test/renderers/model-viewer/index.html
=> Consistent radius

packages/model-viewer/src/test/features/environment-spec.ts, packages/model-viewer/src/test/three-components/TextureUtils-spec.ts, packages/model-viewer/src/three-components/TextureUtils.ts
=> switched default environment

packages/model-viewer/src/features/controls.ts, packages/model-viewer/src/test/features/controls-spec.ts, packages/modelviewer.dev/data/docs.json
=> remove interaction-prompt-style

packages/model-viewer/src/features/controls.ts, packages/model-viewer/src/test/features/controls-spec.ts, packages/model-viewer/src/test/three-components/SmoothControls-spec.ts, packages/model-viewer/src/three-components/SmoothControls.ts, packages/modelviewer.dev/data/docs.json
=> remove interaction policy

packages/model-viewer/src/features/controls.ts, packages/model-viewer/src/test/features/controls-spec.ts, packages/model-viewer/src/three-components/SmoothControls.ts, packages/modelviewer.dev/data/docs.json
=> remove when-focused

packages/model-viewer/src/features/loading.ts, packages/model-viewer/src/test/features/loading-spec.ts, packages/modelviewer.dev/data/docs.json, packages/modelviewer.dev/data/examples.json, packages/modelviewer.dev/examples/lighthouse2.html, packages/modelviewer.dev/examples/loading/index.html, packages/space-opera/src/components/model_viewer_preview/model_viewer_preview.ts
=> remove reveal='interaction'

packages/model-viewer/src/features/loading.ts, packages/model-viewer/src/template.ts, packages/modelviewer.dev/data/docs.json, packages/modelviewer.dev/examples/color.html, packages/modelviewer.dev/examples/lighthouse.html, packages/modelviewer.dev/examples/lighthouse2.html, packages/modelviewer.dev/examples/twitter/player.html, packages/modelviewer.dev/index.html
=> remove progress-mask

packages/model-viewer/src/features/scene-graph.ts, packages/model-viewer/src/test/features/scene-graph-spec.ts, packages/modelviewer.dev/data/docs.json
=> remove scene-graph-ready event

packages/model-viewer/src/features/scene-graph.ts, packages/model-viewer/src/template.ts, packages/modelviewer.dev/data/docs.json, packages/modelviewer.dev/examples/annotations/index.html, packages/modelviewer.dev/examples/augmentedreality/index.html, packages/modelviewer.dev/examples/color.html, packages/modelviewer.dev/examples/lighthouse2.html, packages/modelviewer.dev/examples/loading/index.html, packages/modelviewer.dev/examples/twitter/player.html, packages/modelviewer.dev/examples/ux-pan.html, packages/modelviewer.dev/index.html, packages/render-fidelity-tools/test/renderers/model-viewer/index.html
=> Poster color

packages/model-viewer/src/features/scene-graph/api.ts, packages/model-viewer/src/features/scene-graph/image.ts, packages/model-viewer/src/test/features/animation-spec.ts, packages/model-viewer/src/test/features/scene-graph-spec.ts, packages/model-viewer/src/test/features/scene-graph/texture-spec.ts
=> Remove setURI

packages/model-viewer/src/features/scene-graph.ts
=> Update exportScene options

packages/model-viewer/src/features/controls.ts, packages/model-viewer/src/test/features/controls-spec.ts, packages/model-viewer/src/test/three-components/SmoothControls-spec.ts, packages/model-viewer/src/three-components/SmoothControls.ts, packages/modelviewer.dev/data/docs.json, packages/modelviewer.dev/data/examples.json, packages/modelviewer.dev/examples/lightingandenv/index.html
Fixes #3506 
Also adds "automatic" to possible camera-change sources and adds the interact-stopped event to allow you to know if it has been cancelled and why.
=> Cancel prompt

packages/model-viewer/src/three-components/ModelScene.ts
Fixes #3731 
Fixes #3732 
One-line error in a PR from late last week.
=> fix off-centering regression

packages/model-viewer/src/model-viewer-base.ts, packages/model-viewer/src/test/model-viewer-base-spec.ts
=> fix loadfailure error

packages/model-viewer/src/features/animation.ts, packages/model-viewer/src/features/loading.ts, packages/model-viewer/src/model-viewer-base.ts, packages/model-viewer/src/test/features/loading-spec.ts, packages/model-viewer/src/three-components/ARRenderer.ts
Fixes #3497 
After all the API simplification done for v2.0, I decided to see how much that would allow our loading logic to be simplified (this has been convoluted for a long time and a common source of bugs). I'm much happier with it now, and it also fixed this bug, and likely others unknown. I also tightened up our testing for this.
=> Loading refactor

packages/model-viewer/src/features/ar.ts, packages/model-viewer/src/features/scene-graph.ts, packages/model-viewer/src/test/features/scene-graph-spec.ts, packages/model-viewer/src/test/model-viewer-base-spec.ts, packages/model-viewer/src/three-components/ModelScene.ts, packages/modelviewer.dev/examples/scenegraph/index.html
Fixes #3765 
This turned into a larger refactor, but I'm happy with the results. I managed to remove a wrapper object from our scene hierarchy (`modelContainer`) and I also did a bunch of cleanup on the `model-viewer-base-spec`.
=> Fixed scale/orientation export

packages/model-viewer/package.json
=> Added typings in package.json

packages/modelviewer.dev/examples/lighthouse.html, packages/modelviewer.dev/examples/lighthouse2.html
=> fix: issue #3831

packages/model-viewer/src/features/scene-graph.ts
=> make loading wait for variant update

packages/modelviewer.dev/data/examples.json, packages/modelviewer.dev/examples/annotations/index.html
They were nearly duplicate, so better to just have the one.
=> combined the two dimensions examples

packages/model-viewer/src/features/controls.ts, packages/model-viewer/src/test/features/controls-spec.ts, packages/model-viewer/src/test/three-components/Renderer-spec.ts, packages/modelviewer.dev/data/docs.json
Reverting #3685 by popular demand.
=> revert prompt style removal

packages/space-opera/src/components/materials_panel/materials_panel.ts
Addresses most of https://github.com/google/model-viewer/discussions/3902
=> fixed sRGB conversion in editor color pickers

packages/model-viewer/src/features/scene-graph.ts, packages/model-viewer/src/model-viewer-base.ts, packages/model-viewer/src/three-components/ModelScene.ts, packages/model-viewer/src/three-components/Renderer.ts, packages/model-viewer/src/three-components/Shadow.ts
Trying to keep `ModelScene` from leaking when a `<model-viewer>` element is removed from the DOM.
=> Canvas leak

packages/model-viewer/src/features/controls.ts, packages/model-viewer/src/test/features/controls-spec.ts
Fixes #3961, replaces #3963. Thanks @samaneh-kazemi!
=> cancel interact() when disconnecting from DOM

packages/model-viewer/src/features/controls.ts, packages/model-viewer/src/test/features/controls-spec.ts
Fixes #3949 
Not sure how this was working before; couldn't find any related code that was removed, but this seems like a pretty robust fix.
=> fixed basic prompt

packages/space-opera/src/components/camera_settings/camera_settings.ts, packages/space-opera/src/components/config/reducer.ts
=> fixed camera saving

package-lock.json, packages/model-viewer/package-lock.json, packages/model-viewer/package.json, packages/render-fidelity-tools/package-lock.json, packages/space-opera/package-lock.json
Fixes transparent rendering regression and specular/ior export.
=> three.js r149

packages/model-viewer/src/three-components/ARRenderer.ts, packages/modelviewer.dev/examples/annotations/index.html
Also several additional fixes to the SVG annotations examples to make them work properly in AR.
=> added camera-change events during AR

packages/modelviewer.dev/examples/animation/index.html
Fixes the too-large-for-AR animated robot in our examples.
=> fixed robot scale

packages/model-viewer/src/features/annotation.ts, packages/model-viewer/src/test/features/annotation-spec.ts
=> added surface updating

packages/render-fidelity-tools/src/components/renderers/babylon-viewer.ts
This is a small PR to fix some models that are rendered black with the Babylon.js renderer.
=> Babylon.js renderer: Fixing some models being rendered black

packages/modelviewer.dev/examples/annotations/index.html
This PR aims to fix a small bug that was present in the annotations example.
=> fix annotations example bug

packages/modelviewer.dev/docs/faq.html, packages/modelviewer.dev/docs/index.html, packages/modelviewer.dev/examples/animation/index.html, packages/modelviewer.dev/examples/annotations/index.html, packages/modelviewer.dev/examples/augmentedreality/index.html, packages/modelviewer.dev/examples/color.html, packages/modelviewer.dev/examples/lighthouse.html, packages/modelviewer.dev/examples/lighthouse2.html, packages/modelviewer.dev/examples/lightingandenv/index.html, packages/modelviewer.dev/examples/loading/index.html, packages/modelviewer.dev/examples/scenegraph/index.html, packages/modelviewer.dev/examples/stagingandcameras/index.html, packages/modelviewer.dev/examples/twitter/generator.html, packages/modelviewer.dev/examples/twitter/player.html, packages/modelviewer.dev/index.html, packages/render-fidelity-tools/test/results-viewer.html, packages/space-opera/editor/index.html
Adds anonymous data collection on WebGL support in the wild, for the benefit of all: https://web3dsurvey.com/
Thanks @bhouston!
=> add web3dsurvey

packages/model-viewer/README.md
Fixes #4197
Update: Signed the CLA. Not sure how/when I should retry the CLA workflow check.
=> Make peer dependency relationship clear in readme

package-lock.json, packages/model-viewer-effects/README.md, packages/model-viewer-effects/package-lock.json, packages/model-viewer/package-lock.json, packages/model-viewer/package.json, packages/model-viewer/src/features/scene-graph/material.ts, packages/model-viewer/src/features/scene-graph/pbr-metallic-roughness.ts, packages/modelviewer.dev/examples/postprocessing/index.html, packages/modelviewer.dev/index.html, packages/modelviewer.dev/package-lock.json, packages/render-fidelity-tools/package-lock.json, packages/space-opera/package-lock.json
I'm not doing the [colorspace update](https://discourse.threejs.org/t/updates-to-color-management-in-three-js-r152/50791) yet, since the old way is only deprecated, but still works. I prefer to wait until the TS types are updated so we don't need to fill the code with `as any`.
=> three.js r152

scripts/postinstall.js
=> fix postinstall

lerna.json, package-lock.json, package.json, packages/modelviewer.dev/package.json, packages/modelviewer.dev/scripts/ci-before-deploy.sh, packages/render-fidelity-tools/test/renderers/filament/index.html, packages/render-fidelity-tools/test/renderers/gltf-sample-viewer/index.html, packages/render-fidelity-tools/test/renderers/three-gpu-pathtracer/index.html, packages/space-opera/editor/index.html, packages/space-opera/editor/view/index.html
=> update deployments again

packages/modelviewer.dev/scripts/ci-before-deploy.sh
=> recursive copy

packages/modelviewer.dev/examples/loading/index.html
=> First commit: Add details to the invalid gltf example

packages/modelviewer.dev/examples/scenegraph/index.html
in the browser
2. Go to Create Textures link
3. Change the normals and play around with the model in 3D and AR
4. Please try damaged helmet , lantern pole and water bottle options.
Expected Result:
-Asset should launch and render properly with Laptops & Mobile devices
-The text values of all options should be observed inside the screen.
Actual Result:
Belonging to the selected model; the picture name part does not fit on the screen and remains at the bottom of the screen.
=> Update scenegraph examples

packages/modelviewer.dev/examples/scenegraph/index.html, packages/modelviewer.dev/scripts/ci-before-deploy.sh
Switching cube models, as this one makes it clearer what happens in the case of clamp to edge - thanks @samaneh-kazemi for bringing it to my attention. I also fixed a few small typos in our mode API docs.
=> Material example update

.github/workflows/unit-tests.yml, packages/model-viewer/src/test/features/scene-graph-spec.ts, packages/model-viewer/src/test/features/scene-graph/material-spec.ts, packages/model-viewer/src/test/features/scene-graph/model-spec.ts, packages/model-viewer/src/test/features/scene-graph/nodes/primitive-node-spec.ts, packages/model-viewer/src/test/features/scene-graph/texture-info-spec.ts, packages/model-viewer/src/test/features/scene-graph/texture-spec.ts, packages/model-viewer/src/test/three-components/gltf-instance/correlated-scene-graph-spec.ts, packages/modelviewer.dev/ATTRIBUTIONS.md, packages/modelviewer.dev/examples/augmentedreality/index.html, packages/modelviewer.dev/examples/lightingandenv/index.html, packages/modelviewer.dev/examples/loading/index.html, packages/modelviewer.dev/examples/scenegraph/index.html, packages/modelviewer.dev/examples/stagingandcameras/index.html, packages/modelviewer.dev/scripts/ci-before-deploy.sh, packages/render-fidelity-tools/test/README.md, packages/render-fidelity-tools/test/renderers/vray/render.py, packages/space-opera/src/components/model_viewer_snippet/components/open_button.ts
@bhouston Our tests were broken because the Sample-Models hadn't been updated to Sample-Assets yet. You probably didn't noticed because like me, you hadn't deleted the Sample-Models directory and the unit tests weren't running on the CI for your PRs. I *think* I've fixed that here too - we'll see when you pull it into your open PRs.
=> Update example assets

packages/modelviewer.dev/examples/lightingandenv/index.html, packages/modelviewer.dev/scripts/ci-before-deploy.sh
=> Fix materials example

packages/model-viewer/src/three-components/GroundedSkybox.ts
=> fixed grounded skybox reversal

packages/modelviewer.dev/index.html
Whoops - testing change made it to deployment.
=> revert landing page

packages/model-viewer/src/features/ar.ts, packages/model-viewer/src/features/environment.ts, packages/model-viewer/src/features/scene-graph.ts, packages/model-viewer/src/model-viewer-base.ts, packages/model-viewer/src/test/utilities/progress-tracker-spec.ts, packages/model-viewer/src/utilities/progress-tracker.ts, packages/modelviewer.dev/data/docs.json
=> Provide a reason property when firing progress events

packages/model-viewer/src/three-components/Renderer.ts, packages/modelviewer.dev/examples/color.html, packages/modelviewer.dev/examples/tone-mapping.html
=> final tone mapping edits

packages/modelviewer.dev/examples/config.ocio, packages/modelviewer.dev/examples/lut-writer.mjs, packages/modelviewer.dev/examples/tone-mapping.html
Updating tone mapper docs, mostly for the new official Khronos name.
=> PBR Neutral docs

packages/model-viewer/src/features/scene-graph/pbr-metallic-roughness.ts, packages/modelviewer.dev/data/docs.json
Fixes #4354
Thanks for pinpointing the problem @hybridherbst!
Also updated some docs.
=> Fix color in USDZ export

packages/modelviewer.dev/examples/config.ocio, packages/modelviewer.dev/examples/lut-writer.mjs
Update associated with https://projects.blender.org/blender/blender/pulls/118936#issuecomment-1143880
=> updated Blender OCIO config

packages/model-viewer/src/features/ar.ts
Apparently we haven't updated this for quite some time. It *might* help with #4582, but I kind of doubt it.
=> Update scene-viewer intent

packages/modelviewer.dev/examples/augmentedreality/index.html
Make a more basic SV test example.
=> remove webxr from SV example

packages/model-viewer/src/features/ar.ts, packages/modelviewer.dev/examples/augmentedreality/index.html
Fixes #4732 
The turntable rotation was incorrectly being applied to the exported scene.
=> fixed USDZ rotation

packages/model-viewer/src/three-components/Renderer.ts
=> fixed offscreen toBlob

packages/model-viewer/src/features/ar.ts, packages/modelviewer.dev/examples/augmentedreality/index.html, packages/modelviewer.dev/examples/lightingandenv/index.html
Fix a regression caused by #4753.
=> fix USDZ positioning

packages/modelviewer.dev/examples/scenegraph/index.html
Our API was expanded quite a bit to support all the PBR Next extensions and such, but it looks like we neglected to update the public docs accordingly.
=> update model documentation

packages/modelviewer.dev/examples/3dPipelineDays24/index.html, packages/modelviewer.dev/examples/3dPipelineDays24/slides.js
Putting up a web-based presentation for a model-viewer talk. Perhaps should link to it later so it's easier to find, though it's not worth much without a voiceover.
=> Presentation

packages/model-viewer/src/features/scene-graph/material.ts, packages/model-viewer/src/features/scene-graph/model.ts, packages/model-viewer/src/features/scene-graph/nodes/primitive-node.ts, packages/model-viewer/src/features/scene-graph/three-dom-element.ts, packages/model-viewer/src/test/features/scene-graph-spec.ts, packages/model-viewer/src/test/features/scene-graph/model-spec.ts
=> Fix variants with multiple internal materials

packages/model-viewer/package.json
peerdependency was not updated along with the rest.
=> Set correct peerdependency on threejs

package-lock.json, packages/model-viewer/src/features/animation.ts, packages/model-viewer/src/features/environment.ts
In order to learn what's new in model-viewer [4.1.0](https://github.com/google/model-viewer/releases/tag/v4.1.0), I read through the changes in PR #4979. Very nice feature by @mohammadbaghaei  👍. I noticed there are some minor possible improvements, for which I created this PR.
After running `npm install`, the lock file was updated. Apparently this lock file update was missed in #5019.
=> Code improvements after 4.1.0 release

.github/workflows/deploy-documentation.yml
=> Fix Deploy Documentation issue

packages/model-viewer/src/three-components/ARRenderer.ts
Remove the indicator boxes for vr controller inputs
=> Deprecate vr controller indicator box

packages/space-opera/src/components/mobile_view/utils.ts
Reverts google/model-viewer#5063
=> Revert "Update Piping Server instance source"

packages/model-viewer/src/three-components/PlacementBox.ts, packages/model-viewer/src/three-components/XRMenuPanel.ts
XR menu panel position is now based on placementbox radius
=> make XR Menu Panel positioning based on placementbox radius
