google/model-viewer

src/features/ar.js
src/test/features/ar-spec.js

I think one of the recent AR changes caused the failing test, unrelated to the `ar` to `unstable-webxr` change (I think due to no longer setting the display inline), and also changed to `unstable-webxr` here, and decoupled the `ar` attribute usage from the `ios-src` tests, and added a stub for an `unstable-webxr` test (not sure what we can do there)

Fix ARMixin tests

---

package-lock.json
package.json

NPM: https://www.npmjs.com/package/@google/model-viewer
Webcomponents.org: https://www.webcomponents.org/element/@google/model-viewer
Unpkg.com: https://unpkg.com/@google/model-viewer@0.0.1/
Unfortunately, Webcomponents.org picks up the elements that are defined in tests. I'm going to bug @samuelli about this next week to see if there is anything we can do.

Update package.json in preparation for publishing

---

examples/background-image.html
src/features/environment.js
src/three-components/CachingGLTFLoader.js
src/three-components/ModelScene.js

* Broken out from #133
* Fixes #101, #120 render glitches from #94/skysphere depth test change. I think this fixes all the weird rendering issues I've seen.
* Fixes CachedGLTFLoader instances sharing materials (and environment maps) resulting in race conditions to determine what envmap is displayed

Render fixes

---

src/test/three-components/ModelScene-spec.js
src/three-components/ModelScene.js

see the examples in http://localhost:8000/examples/background-image.html and you'll see the skysphere does not match the environment map. This is now fixed:

Flip skysphere's X axis so that it matches the orientation of the environment map applied on models

---

src/features/environment.js
src/test/features/environment-spec.js

The glitch link is down, but tests confirm this should be fixed

Do not apply default when EnvironmentMixin connected to DOM when background-image/color defined. Fixes #141

---

examples/background-image.html
src/features/environment.js
src/test/three-components/TextureUtils-spec.js
src/three-components/EnvMapGenerator.js
src/three-components/Renderer.js
src/three-components/TextureUtils.js

Convert TextureUtils to TextureManager such that the renderer owns themanager so new texture helper instances do not need to be created, and properly dispose of textures that are no longer being used. Fixes #138, memory leak introduced by textures.

Fix texture memory leak

---

src/features/ar.js

-- and as a follow up from #154, rename unstable-webxr attribute in use as property to unstableWebxr. Fixes #142

Ensure QuickLook/WebXR AR methods are private

---

README.md
examples/index.html
examples/pbr.html

I'm not 100% happy with the README text, but I wanted to capture something like that.
With @jsantell's changes to async load the `pbr.html` examples, I don't think we need the warning in `index.html`, so I removed that (and updated the size to reflect the removal of the Flight Helmet sample).

minor changes to examples and readme

---

README.md

Now that examples are hosted on github

Link to examples hosted page rather than source code

---

src/three-components/ModelScene.js

I wasn't able to tell what the issue was with loading models (it was `THREE.GLTFLoader: Unsupported asset. glTF versions >=2.0 are supported. Use LegacyGLTFLoader instead.`). This change helped me debug the error more effectively in the console.

Include error message with model load error

---

src/constants.js
src/features/ar.js

Addresses an sub point in #18 in that you can't check if AR Quicklook is supported.
I'll add some tests when I've figured out how tests are run on this project. ¯\_(ツ)_/¯

Check to see if AR Quicklook is supported

---

src/constants.ts
src/types/webxr.d.ts

This change dips our toes in the TypeScript waters by introducing Web XR API types to the code base and converting our `constants` module over to TypeScript. As you can see from the diff, the changes required for conversion are minimal. Some notes:
- Some globals, like `opera` and `MSStream` were not given types due to their limited relevance to what we are building
- Web XR types are currently _not comprehensive_, and only include what is necessary for the `constants` module to compile
- The Web XR API is rapidly changing, and as of right now the API in Canary does not track with the spec (which has already removed `requestDevice` from `XR` as of this change)

Introduce types for Web XR API

---

POLYFILLS.md
README.md
examples/augmented-reality.html
examples/background-color.html
examples/background-image.html
examples/default.html
examples/fuzzer.html
examples/index.html
examples/list.html
examples/loading.html
examples/multiple-elements.html
examples/pbr.html
examples/sources.html
src/constants.ts
src/model-viewer-base.js
src/template.js
src/types/resizeobserver.d.ts
src/utils.js
test/index.html
test/legacy.html

Some details about this change:
- `ResizeObserver` is used if (and only if) the API is detected on the page
- If `ResizeObserver` is not available, the element falls back to updating on global `resize` events
- If global `resize` events are used, layout measurement is debounced with a 50ms threshold
- Resize observation for all conditions is now enabled in `connectedCallback` and disabled in `disconnectedCallback`
- `ResizeObserver` polyfill is no longer loaded in the "legacy" test suite in order to get coverage for the fallback condition
- Docs have been updated to emphasize that `ResizeObserver` is optional and will be used only if available
Fixes #155

Remove hard dependency on ResizeObserver

---

src/features/controls.js
src/test/index.js
src/test/three-components/PatchedOrbitControls-spec.js
src/third_party/three/OrbitControls.js
src/three-components/PatchedOrbitControls.js

This change patches `OrbitControls` to support basic keyboard input for controlling the camera orbit. ~Currently only orbit is supported (notably not zoom).~
Update: zoom support has also been added via page-up and page-down.
I tried out the built-in keyboard input, but it is designed to control panning (not orbit), which we currently don't enable for `<model-viewer>`.
Also, the built-in keyboard input responds to global keyboard events, so it would likely be unsuitable anyway (every key input would control all `<model-viewer>`s at once).
This implementation only listens for events on the `<canvas>`, so the `<model-viewer>` must be focused before it will respond to keyboard input.
Keyboard orbiting is jumpy right now, but as we rewrite controls later this sprint we can look into smoothing …

Implement basic keyboard support for camera orbit

---

src/three-components/Renderer.js
src/three-components/WebGLExtensionUtils.js

Currently, Firefox can incorrectly appear to support [EXT_shader_texture_lod](https://developer.mozilla.org/en-US/docs/Web/API/EXT_shader_texture_lod) (https://bugzil.la/1451287). Three thinks the extension is supported, so when the shader compiles, an error is thrown. This is reproducible on Firefox Android on Pixel 1 and 2 at least, with these [Khronos conformance tests](https://github.com/KhronosGroup/WebGL/blob/master/sdk/tests/conformance/extensions/ext-shader-texture-lod.html) also failing. It appears [some Samsung devices also have this issue in all browsers](https://github.com/mrdoob/three.js/issues/15343). It appears only textures generated by EquirectangularToCubeGenerator cause this.
Three [provides fallbacks if this extension isn't …

Patch gl.getExtension() EXT_shader_texture_lod for WebGL browser compatibility

---

examples/augmented-reality.html
examples/background-color.html
examples/background-image.html
examples/default.html
examples/fuzzer.html
examples/list.html
examples/loading.html
examples/multiple-elements.html
examples/pbr.html
examples/sources.html
examples/styles/examples.css

Styling from the three.js docs; happy to tweak
Fixes #177

add a 'view source' button to the examples

---

examples/assets/reflective-sphere.gltf

It looks when I made pbr-spheres there was an off by one on the range of material values, and for some reason reflective-sphere wasn't fully metal/zero roughness, leading to a lot of wrong assumptions on my end. The diffuse was wayyy too bright.
Updated PBR spheres to be the same color as MetalRoughnessSpheres (https://github.com/GoogleWebComponents/model-viewer/issues/236), which is testing texture maps more so than IBL, so no need to use the reference material which clocks in at 9MB more than this stripped down version (which is half the size of the current pbr-spheres with shared geometry). I think then we could close https://github.com/GoogleWebComponents/model-viewer/issues/236. Compare below (specifically the lighting of the grey spheres).
Original reference rendered view …

Fix PBR test models to use full range of metallic/roughness

---

package.json

Fixes #254 
Ensures that the legacy bundles get generated before publish so that they get distributed as part of the published artifacts.

Create legacy bundles during prepublish

---

src/test/utils-spec.js
src/three-components/ModelScene.js
src/three-components/Renderer.js
src/three-components/WebGLUtils.js
src/utils.js

This change is a candidate to fix #185 . ~**I think this proposal deserves some discussion / debate** as it is an imperfect approach that works in a lot of common cases, but has some known (and probably unknown) failure modes.~ Concisely, this is the strategy being proposed:
> If the document _does not_ have a meta viewport tag, ~_and_ the ratio of the window dimensions to the screen dimensions (in CSS pixels) is greater than one,~ _then_ cap the effective device pixel ratio to 1.
~Known failure modes include:~
i. ~**Page without meta viewport viewed on desktop** window-to-screen ratio exceeds 1 due to user manually scaling the window to be wider than their desktop screen.~
ii.  ~**Page without meta viewport viewed on mobile** is loaded in an iframe, and the iframe-to-screen ratio is <= 1 …

Cap DPR when <meta name="viewport"> is missing

---

src/features/environment.js
src/test/features/environment-spec.js
src/three-components/ModelScene.js

This change is a candidate to address #179
- Re-introduces a directional light by adding the "shadow" light to the scene
- Shadow light hue is tinted to match background color if configured
Fixes #179

Re-introduce the directional light to the scene

---

README.md

It is now unprefixed in the latest stable Chrome and Firefox.

Update status of Fullscreen API

---

package-lock.json
package.json
src/test/three-components/ARRenderer-spec.js
src/three-components/ARRenderer.js
test/index.html
test/legacy.html

- Changes `ARRenderer` to use `EventDispatcher`
- Adds the `EventTarget` polyfill for use in test suites.
Fixes #283

ARRenderer uses EventDispatcher; EventTarget only in tests

---

package-lock.json
src/three-components/ARRenderer.js

I've renamed the single use of `frame.getDevicePose` to `frame.getViewerPost` which fixes #286.

Renamed getDevicePose to getViewerPose according to update in spec

---

package-lock.json
package.json
src/third_party/three/GLTFLoader.js

Only examples/ widget that changed is GLTFLoader -- in the future, work's being done so we can just pull these in via npm (https://github.com/mrdoob/three.js/pull/15518), so next three update may be able to use that.
[Migration guide](https://github.com/mrdoob/three.js/wiki/Migration-Guide) does not mention anything that would affect us.

Update three.js to r100

---

src/model-viewer-base.js
src/test/three-components/Renderer-spec.js
src/three-components/Renderer.js

Zooming (e.g., with `⌘ +`/`⌘ -`) changes the effective `devicePixelRatio` and lays everything out accordingly. Previously, WebGLRenderer's DPR was not being updated under these circumstances, causing the model to be incorrectly staged under zoom events (and, incidentally, when turning on device emulation in dev tools).
Current behavior | New behavior
-----------------|---------------
Fixes #298

Fix incorrect scale when zooming

---

examples/background-image.html
package-lock.json
src/assets/controls-svg.js
src/features/controls.js
src/template.js
src/test/features/controls-spec.js

This change proposes a visual counterpart to the controls prompt suggested in #319 .
- The timing and dismissal logic is the same as the ARIA prompt
- An animated SVG is bundled to offer a reasonable default experience
- Default prompt can be overridden by distributing "light tree" content to the `controls-prompt` slot
```html
<model-viewer src="something.gltf" controls>
</model-viewer>
```
fixes #317

Visual controls prompt

---

examples/index.html
src/features/controls.js
src/test/features/controls-spec.js
src/test/three-components/SmoothControls-spec.js

This change is meant to complement a11y / interaction improvements brought by #319 and #322 .
- When the orientation of the camera changes significantly, the new orientation is announced to screen readers
- When the model loses focus and then regains focus, the original ARIA label is announced
- Azimuth is separated into quadrants: front, left, back and right
- The top third of the sphere is the "upper" pole, the bottom third is the "lower" pole
---
Fixes #315

Announce camera orientation

---

examples/background-image.html
src/assets/controls-svg.js
src/features/controls.js
src/template.js
src/test/features/controls-spec.js
src/test/three-components/SmoothControls-spec.js

This change is the rolled up PR including work from #322 and #325. Since this work all ties in to #299, I have copied over relevant graphics and descriptions so that everything can be tested / signed-off-on in its integrated form before it lands in master. Detailed info related to the change follows:
This change proposes an ARIA-based interaction prompt for users who are focused on an activated `<model-viewer>` element with `controls` configured. The logic for this prompt is roughly:
1. A user focuses the `<model-viewer>` (after any `poster` or equivalent is dismissed)
2. After a period of time (currently ~3s), if the user has not interacted w/ the controls, they are prompted to interact ("Use mouse, touch or arrow keys to control the camera!")
3. If the user blurs and then re-focuses the …

Improved a11y for <model-viewer> controls

---

package-lock.json
package.json

This paves the way for:
- Usage of scene.background in HDR changes #196 
- Importing discrete modules, even from TypeScript, to reduce bundle size
Fixes #330

Upgrade Three.js to r101

---

test/wct-sauce.conf.json

This is to address occasional outage of support for Chrome Dev by Sauce Labs

Disable Chrome Dev, bump FF to 65

---

examples/augmented-reality.html

This change proposes a page-specific CSS patch to fix the obscured "Enter AR" button called out in #348.
Below are samples of the new layout. Note that these changes only affect the AR examples page:
Mobile layout | Desktop layout
--------------|---------------
Fixes #348

Patch styles to fix obscured AR button

---

examples/styles/examples.css
src/features/loading.js
src/features/loading/status-announcer.ts
src/test/features/loading/status-announcer-spec.ts
src/test/helpers.js
src/test/index.js
src/utils.ts

This change proposes providing screenreader users with sparse updates on the current loading status of all `<model-viewer>` elements on the page. Some details of the change:
- A singleton manages aggregation and observation of the loading state of all `<model-viewer>` instances that apply the `LoadingMixin`
- `<model-viewer>` instances are observed when they connect to the document, and ignored after they disconnect
- Two announcements are made: an initial one ("There are 3D models that are loading") and a final one ("All 3D models have loaded")
- An initial announcement is made if (and only if) there is at least one `<model-viewer>` in the document
- When all currently observed instances have either loaded or errored, the final announcement is made
- Note: since the status announcer is …

Sparsely announce loading status to screen readers

---

scripts/install-third-party-renderers.sh

Without `CXXFLAGS=-stdlib=libc++`, Filament won't build on my Debian machine.
It doesn't impact compilation on MacOS, but I had to make other changes that I'll ask about below.

Add CXXFLAGS for Filament on Debian

---

src/features/environment.js
src/test/features/environment-spec.js
src/three-components/StaticShadow.js

This change proposes the addition of configurable shadow intensity, with a new default of `0.0`, effectively causing shadows to be hidden by default.
The image above demonstrates the shadow being changed on a timer between values `0.0` and `2.0`. The previous default intensity can be achieved by setting the value to `1.0`.
Fixes #206

Add configurable shadow intensity, change default

---

src/test/fidelity/filament.patch

On Linux, if the Filament window isn't visible the captured image is all back.
Unfortunately, even on Mac (where we don't need to display the window to capture the render), the window still steals focus.
Therefore, for consistency, we'll always display the window.

Show the Filament window

---

src/features/environment.js
src/test/features/environment-spec.js
src/test/three-components/TextureUtils-spec.js
src/three-components/ModelScene.js

This change proposes adding a `stage-light-intensity` attribute/property for configuring the intensity of Three.js ambient/directional lights in the scene.
- Intensity in this context is a scalar that is applied to the base intensity of the ambient and directional lights separately
- Rationale here is that the base intensity for each of these lights is different, and also based on the current role (see below)
- Stage lights now also have a "primary" and "secondary" role, for non-PMREM and PMREM rendering respectively
- The rationale here is that when PMREM is activated, the stage lights should be de-emphasized (they become "secondary" lighting)
- This is an implementation detail, not directly configurable by the `<model-element>` user
- `0.0` intensity turns off the stage lights; `1.0` is …

Add configurable stage light intensity

---

package-lock.json
package.json
src/documentation/components/example-snippet.ts
src/features/environment.js
src/model-viewer-base.js
src/test/features/environment-spec.js
src/test/features/loading/status-announcer-spec.ts
src/test/fidelity/components/analysis-view.ts
src/test/fidelity/components/image-comparison-app.ts
src/test/fidelity/components/images-4-up.ts
src/test/fidelity/components/magnifying-glass.ts
src/test/fidelity/components/rendering-scenario.ts
src/test/three-components/TextureUtils-spec.js
src/three-components/Model.js
src/three-components/TextureUtils.js

This change proposes the introduction of two new user-configurable attribute/properties: `environment-image` and `environment-intensity`. Highlights of the change include:
- Upgrades `@polymer/lit-element@0.6.x` to `lit-element@2.0.x`
- Various fixes were necessary to make tests pass after breaking changes from upgrade
- Adds `environment-image` attribute to control the environment map without affecting the background image or color
- Adds `environment-intensity` attribute to control the intensity of whatever environment map happens to be used
`environment-intensity` oscillating `0.0` - `6.0` | Cycle `environment-image` only | Cycle `background-image` only |
| -------------------------------------------- | ------------------------------- | ----------------------------------- |
~Terms like …

Introduce environment-image and environment-intensity

---

examples/assets/Triangle.gltf
examples/assets/attributions.md
src/test/features/environment-spec.js
src/three-components/CachingGLTFLoader.js
src/three-components/Model.js

Currently with a default env map, image env map, and PMREM'd env map currently:
With this patch:
Note that `UnlitTest.glb` is included (4kb) -- can reference the Khronos models if/when they land. The Astronaut is *not* unlit AFAICT (or, does not use the unlit extension), maybe should change the background-image demo describing it as such.

Do not apply environment maps to unlit models. Fixes #374

---

src/constants.ts
src/model-viewer-base.js
src/test/model-viewer-base-spec.js
src/types/intersectionobserver.d.ts
test/legacy.html

This change proposes that `IntersectionObserver` should be an optional, performance-enhancing feature rather than a required feature to make `<model-viewer>` work (as it is now). Documentation updates related to this change are in progress, and will be included in a forthcoming PR.
Fixes #386

Make IntersectionObserver optional

---

package-lock.json
src/three-components/TextureUtils.js

We experienced an untracked regression after the environment map refactor in #392 . The regression manifested as artifacts shown when using an environment map that we are currently excluding from our fidelity tests while we investigate PMREM generation quirks. Here is the rendering before and after this hotfix:
Without hotfix | With hotfix
---------------|-----------

Hotfix for PMREM environment map regression

---

src/features/loading/status-announcer.ts

When we added the status element in #345 , its styles left it hanging outside the box boundary of its `<model-viewer>` host element. The unfortunate side-effect of this is that the status element receives a focus ring in Chrome.
This change tweaks the styles of the status element so that it no longer receives a separate focus ring from its host element.
Before style change | After style change
-------------------- | ------------------

Fix overhanging focus ring in Chrome

---

src/three-components/Renderer.js

We were creating transparent webgl context and forcing the browser do extra compositing work.

Renderer: Disable alpha by default.

---

src/three-components/StaticShadow.js

We're sending unneeded commands to the GPU and making it rasterise two invisible triangles.

StaticShadow: Avoid rendering shadow mesh when opacity is 0.

---

src/model-viewer-base.js
src/test/templates.ts
src/three-components/Renderer.js

We have been experiencing intermittent timeouts in our iOS test target, as well as "GPU out of memory" errors in IE11 on every test run.
This change ensures that renderer-related memory allocations are properly cleaned up across every test run. There may be additional memory leaks, but I have not performed a deeper trace to uncover any at this time.
Fixes #433

Cull test suite memory bloat

---

src/features/controls.js

This will help to mitigate artifacts seen in some models where scene nodes are placed sufficiently close together to cause z-fighting.

Adjust camera near plane for improved depth precision

---

index.html
src/assets/controls-svg.js
src/assets/view-in-ar-material-svg.js
src/features/controls.ts
src/test/features/controls-spec.js

Fixes #435 
Fixes #437 
Fixes #446 
Fixes #456

Fix various bugs related to interaction prompt

---

src/features/loading.js
src/features/staging.ts
src/model-viewer-base.js
src/test/features/staging-spec.ts

This fix checks to make sure that auto-rotation only starts once the poster is no longer visible and the model is interactable.
One thing is that this will not prevent the small stutter that happens when the poster transitions into 3D. That's because the rotation will start when the poster is dismissed, but the poster has a 0.3 second opacity transition. So during the transition you'll see the model rotation while the poster which is an image of the first frame will be fading away. It's not super noticeable, but it's also not perfectly smooth. 
It may be more trouble than it's worth solving that case since we'd have to listen for when the opacity transition ends before triggering the rotation. And since the loading mixin and the staging mixin don't know about each other, that could be …

Auto-rotate doesn't rotate the model pivot if no model is loaded

---

examples/lazy-loading.html
examples/styles/examples.css
index.html
rollup.config.js
src/features/animation.ts
src/features/controls.ts
src/features/environment.js
src/features/loading.ts
src/model-viewer-base.ts
src/template.ts
src/test/features/loading-spec.js
src/test/helpers.js
src/test/index.js
src/test/utilities/progress-tracker-spec.ts
src/third_party/three/GLTFLoader.d.ts
src/three-components/CachingGLTFLoader.ts
src/three-components/Model.js
src/three-components/ModelScene.js
src/three-components/TextureUtils.js
src/types/resizeobserver.d.ts
src/utilities/progress-tracker.ts
src/utils.ts

This change proposes the addition of the notion of instance-wide loading progress, as well as corresponding customizable visualizations and API. In other words: progress bars.
Some highlights of this change include:
- A new `progress` event is introduced, maps directly to our internal notion of progress
- A built in progress bar UI has been introduced
- Can be customized by adding child nodes to `slot="progress-bar"`
- Can also be customized with CSS custom properties
- The poster now has a default background color, and is always displayed before the model is loaded
- Can now be customized by adding child nodes to `slot="poster"`
- Can also be customized with CSS custom properties
- A new `reveal` attribute has been introduced to control model visibility
- Default configuration is …

Progress bars

---

src/assets/controls-svg.js

This change partially fixes the issue reported in #466 . I'm going to leave #466 open until we have a full fix.
With this change, the prompt still doesn't animate, but doesn't look totally broken (as it did before) with the animations disabled:

Partially fix interaction prompt SVG

---

src/assets/view-in-ar-material-svg.js

This brings our AR glyph up to date with the latest Material version.
Old | New
--- | ---

Update AR glyph

---

src/test/fidelity/components/rendering-scenario.ts

Fixes #511 
Looking at https://www.w3schools.com/cssref/css3_pr_flex.asp, it seems like their example code doesn't really match with their CSS syntax. I changed it from the example way to the CSS way, and it seems to be happy now. If someone has some other browsers handy, it'd be good to double check they all like it too.

fixed flex syntax

---

src/features/animation.ts
src/features/ar.ts
src/features/controls.ts
src/features/loading.ts
src/features/loading/status-announcer.ts
src/features/staging.ts
src/model-viewer-base.ts
src/model-viewer.ts
src/test/features/controls-spec.js
src/test/features/staging-spec.ts
src/test/three-components/SmoothControls-spec.js
src/test/utilities/timer-spec.ts
src/test/utils-spec.js
src/three-components/ARRenderer.js
src/three-components/ModelScene.js
src/three-components/Renderer.js
src/three-components/SmoothControls.ts
src/utilities.ts
src/utilities/progress-tracker.ts
src/utilities/timer.ts

#459 
While I was acquainting myself with the `<model-viewer>` codebase I realized there's very little shared state.
In order to implement this fix `StagingMixin` and `ControlsMixin` need to either:
1. Have some shared state on `ModelViewerBase`
2. Somehow via events or callbacks be notified that interaction has started/ended
Since this project seems to avoid global state I opted for Option 2.
I do think that if someone is building custom UI around `<model-viewer>` they do need to know of interaction start and end so this why dispatching these events from `<model-viewer>` might make sense.
On the downside. I HATE wiring application logic via internal events. It general is not good for the long term.
Anyway would love to hear some thoughts.
To make this PR not be *[WIP]*. I'll need to do …

Disable Auto Rotate On Interaction

---

README.md
index.html

@cdata I only updated the reveal attribute in docs index.html & readme. **reveal-when-loaded** still exist in accessibility examples and fuzzer.html, I defer the change to you.

Updated reveal-when-loaded to reveal in docs

---

src/three-components/Renderer.js

This regression was introduced when upgrading to r104 in #536.
Thanks to @DavidPeicho for investigating and [figuring out](https://github.com/GoogleWebComponents/model-viewer/issues/546#issuecomment-493088841) the [root cause](https://github.com/mrdoob/three.js/pull/13593).
Fixes #546.

Renderer: Fixed vertical alignment regression.

---

src/features/controls.ts
src/test/features/staging-spec.ts
src/test/three-components/ModelScene-spec.js
src/three-components/ModelScene.js

Fixes #520 
As part of fixing the misaligned shadow, I found that our handling of align to origin was a bit confusing. This change makes Y=0 the floor (the plane of the shadow) always, thus centered objects are moved above the floor while objects aligned to origin assume their coordinates also use Y=0 as the floor. Additionally, for non-centered models, we now use a larger framing, such that the model is still in view as it is rotated.

Model and shadow alignment

---

index.html
src/model-viewer-base.ts
src/test/model-viewer-base-spec.ts

This change proposes that we forward invocations of `toDataURL` to our internal `<canvas>` element so that users can take advantage of one of `<canvas>`'s built-in screenshot capabilities without reaching through `<model-viewer>`'s shadow root.
The semantics of `toDataURL` are the same as the native `<canvas>` one. Screenshots will only display what is rendered to the canvas.
~Depends on #586~
Fixes #596 
cc @pushmatrix

Basic screenshot API via toDataURL

---

index.html
src/constants.ts
src/conversions.ts
src/features/ar.ts
src/test/conversions-spec.ts
src/test/features/ar-spec.ts

- It is now possible to opt-in or -out of Quick Look integration for a set of known browsers
- Currently only "chrome" and "safari" are supported values
- 🚨**BREAKING CHANGE**: iOS Chrome is now opt-in by default (previously it was enabled by default, with no way to opt-out)
- To achieve the behavior before this change, use the following configuration: `<model-viewer quick-look-browsers="safari chrome"></model-viewer>`
- Other browsers are not included because we don't test for them and don't currently know if they even integrate with Quick Look (#627)
- Currently tests targeting specific browsers are prohibitively difficult to write due to how we set constants (#624, #625)
Fixes #534

Opt-in to Quick Look for iOS Chrome

---

index.html
src/features/controls.ts
src/test/features/controls-spec.ts

- A new `interaction-prompt` attribute is introduced, with two supported values:
1. **`when-focused`** (default): this is the current behavior, where the threshold is not measured until the element is first focused
2. **`auto`**:  This enables the behavior described in #529 , and causes the threshold time to be measured as soon as the model is revealed
- In both cases, the prompt is dismissed by user interaction the same way
- This change precedes #622 , but in that change `auto` will become the default behavior (and we will possibly also remove `when-focused`)
Fixes #529

Configuration to raise prompt automatically

---

package-lock.json
package.json

Reverts GoogleWebComponents/model-viewer#641
We need to ship a v0.4.x point release to fix `field-of-view` attribute before shipping v0.5.0.

Revert "Upgrade to Three.js r105.2"

---

src/features/environment.ts
src/test/features/environment-spec.ts

Fixes #649 
Our environments were getting loaded twice, once in firstUpdate, and again in update. I think generation only happened once because of three's caching, but reading in the HDR file and running PMREM were both definitely happening twice, and are both quite expensive. I can't see anything going wrong from removing the firstUpdate function, but I'm also not sure why it was there, so please let me know if I've missed some side effect.

Remove duplicate environment creation

---

POLYFILLS.md
examples/animation.html
examples/augmented-reality.html
examples/fuzzer.html
examples/lazy-loading.html
examples/lighting-and-environment.html
examples/list.html
examples/model-formats.html
examples/multiple-elements.html
examples/pbr.html
examples/rendering-showcase.html
examples/staging-and-camera-control.html
index.html
package-lock.json
package.json
src/model-viewer.ts
src/template.ts
src/test/index.ts
src/test/utilities/focus-visible.ts
src/utilities/focus-visible.ts
test/index.html

This change proposes that we integrate with the `:focus-visible` polyfill (finally possible now that WICG/focus-visible#196 has landed in a release), and rely on its signaling to selectively disable the default focus ring for non-keyboard interactions.
Additional highlights of this change include:
- The [custom element mixin](https://github.com/cdata/focus-visible/blob/fc33395294dd69ad8af70e822e6176a8893816e2/src/custom-element-mixin.js#L1-L49) originally created as an example for WICG/focus-visible#196 has been adapted and added in our project
- Docs have been updated to include information on the polyfill and the use case it supports
- If the polyfill is not included on the page, the focus ring will behave as it did before this change
This change, **polyfill not present** on the page | …

Selectively hide focus ring via :focus-visible polyfill support

---

index.html
src/features/controls.ts
src/features/staging.ts
src/model-viewer-base.ts
src/test/features/controls-spec.ts
src/three-components/SmoothControls.ts

This change proposes a new, public event `camera-change`, that can be used to observe and respond to changes in the `camera-orbit` and `field-of-view`.
The new event also replaces our internal, ad-hoc coordination with a moving/changing camera.
Fixes #506

Camera change event

---

src/model-viewer-base.ts
src/test/templates.ts
src/test/three-components/ARRenderer-spec.ts
src/test/three-components/ModelScene-spec.ts
src/test/three-components/Renderer-spec.ts

Still working on getting our tests to pass. All those Safari warnings about too many WebGL contexts made me dig in a little. I found this thread https://github.com/pixijs/pixi.js/issues/2233#issuecomment-271924403 which says that Three's renderer.dispose() method only simulates a context being destroyed and there's no guarantee the browsers actually clean up at that point. Everyone seems to think the best answer to create a renderer (and therefore a context) once, and always reuse it. We were doing that everywhere except our tests, so I've updated them, and even on Chrome they run markedly faster. We still create and (try to) destroy a few in tests that don't involve an element. I'm not sure if it's worth it to try and make those share a renderer too.

Reuse renderer in tests

---

src/features/environment.ts
src/test/features/environment-spec.ts
src/three-components/EnvironmentMapGenerator.ts
src/three-components/ModelScene.ts

Fixes #396 
In addition to changing the default, I removed the hemisphere light as I believe its only purpose was to hide an old LDR environment lighting bug that has since been fixed. I also removed all the arbitrary constants I could find relating to lighting. 
I also added a top-light to our environment generation to take the place of our default stage light, but we'll need to update our fidelity tests to properly compare.

Default stage light to zero

---

index.html
src/features/controls.ts
src/test/features/controls-spec.ts
src/three-components/SmoothControls.ts

From all of our user testing it seems clear that requiring focus on mobile to interact is not intuitive. @mrdoob said the same thing over at https://github.com/GoogleWebComponents/model-viewer/issues/479.
I do think we need a better heuristic for mobile (https://github.com/GoogleWebComponents/model-viewer/issues/479), and we should have the interaction policy be configurable (https://github.com/GoogleWebComponents/model-viewer/issues/500), but a sensible default should favor making it easy to interact with.
Thoughts?

Change default interaction policy to always-allow

---

src/features/ar.ts
src/template.ts

This hotfix addresses a regression in Chrome m76, that causes our "fullscreen fallback" for Scene Viewer to not work as intended. The symptoms of this problem have been documented by several users in #693 . 
The nature of the fix is to split our click handling out into multiple event listeners. We now use two events to attempt fullscreen and trigger the intent respectively.
This "fix" is actually just a workaround for the problem. It preserves our behavior through Chrome m76, but **this workaround doesn't save us from potential future regressions**. The kernel of the problem is that we expect a handled `intent://` URL on Android to cancel a `requestFullscreen()` invocation. There is no spec or other explicit guarantee that this will always be true.
Special thanks go to @azakus for …

Hotfix: address fullscreen fallback in Chrome m76

---

src/three-components/ModelScene.ts

This change is a proposed alternative #619, which I think we should keep in its current state for historical context.
Paired with #706 this also addresses #701
Fixes #618 
Fixes #701

Re-render in microtask after updating framing

---

index.html
src/template.ts

This change proposes two new CSS custom properties that will enable users to completely hide the UI via CSS. It also adds docs for these properties and missing docs for the `model-visibility` event.
Fixes #554

Add some docs, CSS to hide UI

---

src/features/controls.ts
src/test/features/controls-spec.ts

This change proposes that the default for `interaction-prompt` should become `auto`, causing the visible interaction prompt to always appear after the configured `interaction-prompt-threshold` time has elapsed. The changed default here makes this PR a _breaking change_.
Additionally, this change adds `none` to the set of allowed values for `interaction-prompt`. Setting `interaction-prompt="none"` prevents the interaction prompt from ever being displayed or presented to screen readers. This additional feature was added since we received user feedback in #623 that this was a desirable mode for some use cases.
Fixes #623

Change interaction prompt default, allow disabling it

---

src/features/controls.ts
src/test/features/controls-spec.ts
src/test/three-components/SmoothControls-spec.ts
src/three-components/SmoothControls.ts

Fixes #542 
In addition to zooming using FoV instead of radius, I also interpolate using log(FoV) in order to make it perpetually linear (same movement is the same fractional change from any starting point). I also narrowed the minimum so you can get closer to the object, since you can never enter it now.

Zoom using FoV

---

examples/staging-and-camera-control.html
index.html
scripts/ci-run-tests.sh
scripts/run-fidelity-check.sh
src/conversions.ts
src/features/controls.ts
src/features/staging.ts
src/model-viewer-base.ts
src/test/features/controls-spec.ts
src/test/features/environment-spec.ts
src/test/features/staging-spec.ts
src/test/three-components/ModelScene-spec.ts
src/three-components/ARRenderer.ts
src/three-components/ModelScene.ts
src/three-components/SmoothControls.ts
src/three-components/StaticShadow.ts

Fixes #453 
Fixes #603 
Fixes #679 
In the process of removing align-model I was able to simplify our logic considerably, including cleaning up how the static shadow is placed, since I was having trouble following its logic as I was debugging. The target is interpolated along with the other camera parameters, so this should allow us to do a smooth transition that includes zooming, position and rotation, and once combined with #729, without going through the model. 
I only removed a function from staging.ts, but it seems it wasn't formatted before? Because everything got reflowed. I'm assuming it's correct now...
#679 turned out to be mostly not a <model-viewer> bug, but we noticed that it did show an incorrect shadow for large models. The refactor of StaticShadow here should fix this.

Camera target control

---

.travis.yml
package-lock.json
scripts/ci-run-tests.sh
src/test/fidelity/image-comparison-worker.ts
src/three-components/WebGLUtils.ts

These tweaks are intended to fix our flailing builds, which seem to be choking when trying to run a "stable" Chrome that is pinned somewhere in the mid 60 versions.

Migrate from trusty to xenial

---

src/features/animation.ts
src/features/ar.ts
src/features/controls.ts
src/features/environment.ts
src/features/loading.ts
src/features/magic-leap.ts
src/features/staging.ts
src/test/features/ar-spec.ts
src/test/features/controls-spec.ts
src/test/features/environment-spec.ts
src/test/features/loading-spec.ts
src/test/features/magic-leap-spec.ts
src/utilities/focus-visible.ts
tsconfig.json

Unfortunately, we must revert this part of #747 because it is not compatible with generating external declaration files.
See also https://github.com/Microsoft/TypeScript/issues/30355#issuecomment-473060190

Revert mixin type inference

---

src/constants.ts

Fixes #758 
Copying the inline comment here as it contains the relevant details:
```
// Prior to iOS 13, detecting iOS Safari was relatively straight-forward.
// As of iOS 13, Safari on iPad (in its default configuration) reports the same
// user-agent string as Safari on desktop MacOS. Strictly speaking, we only care
// about iOS for the purposes if selecting for cases where Quick Look is known
// to be supported. However, for API correctness purposes, we must rely on
// known, detectable signals to distinguish iOS Safari from MacOS Safari. At the
// time of this writing, there are no non-iOS/iPadOS Apple devices with
// multi-touch displays.
// @see https://stackoverflow.com/questions/57765958/how-to-detect-ipad-and-ipad-os-version-in-ios-13-and-up
// @see …
```

Properly detect iOS 13 Safari on iPad

---

examples/augmented-reality.html

Many times when referring to the `quick-look-browsers` documentation I would open up the [**Augmented Reality**](https://googlewebcomponents.github.io/model-viewer/examples/augmented-reality.html) page & was surprised to see `ios-src` listed but not `quick-look-browsers`. This rectifies that & lessens the amount people need to scroll to find the feature documentation.
No reference issue.

Add quick-look-browsers to Augmented Reality page

---

src/constants.ts

Fixes #758 
In #775 we addressed incorrect detection of iOS 13 Safari on iPad. Unfortunately, the logic was subtly flawed, and we discovered the flaw when testing the fix on an iPad Pro this morning. This change addresses the flaw. It has been tested on an iOS 13 iPad Pro, iOS 12 iPad Air and MacOS Safari to ensure that the AR button display cases are what we expect.
Once this goes out, we will also back-port this as v0.6.2.

Change logic for detecting iOS 13 Safari on iPad

---

src/test/features/controls-spec.ts
src/test/three-components/SmoothControls-spec.ts
src/three-components/SmoothControls.ts

Fixes #778 
This change means adjustOrbit should not be used to attain an absolute theta (since it will clamp), but that seems fine since we already have a setOrbit method for that purpose.

Fix over-spin reversal

---

src/template.ts

Although we fixed computation-based visibility errors in #755 , Chrome 76 apparently has a rendering disparity that causes render layers to be messed up without any interventions by us. This is what the render layers look like without / with the intervention:
Without intervention | With forced `transform`
---------------------|-------------------------

Force canvas onto its own render layer

---

src/constants.ts
src/features/ar.ts
src/test/three-components/ARRenderer-spec.ts
src/three-components/ARRenderer.ts
src/three-components/Renderer.ts
src/three-components/Reticle.ts
src/types/webxr.d.ts
src/utilities.ts

Get WebXR mode working again using the current API as implemented in Chrome Canary using immersive-ar mode. 
This commit is a snapshot of an airplane hacking session, it's in rough shape due to having a barely-functioning dev environment. Please ignore superficial issues such as indentation, those should obviously be fixed before merging. There's also extra logging, and I was taking shortcuts to get it working such as overriding feature checks. I'm turning it into a PR at @elalish 's suggestion, at least it should be useful as a roadmap of areas that need changing.
FYI, the hit test API is likely to undergo more changes in the near future again, so that will need further tweaks at that time.
Fixes #495

Update WebXR mode to match current immersive-ar

---

scripts/run-fidelity-check.sh

Oops, reverting a change that made it into an earlier PR that broke https://googlewebcomponents.github.io/model-viewer/test/fidelity/results-viewer.html

re-fixing fidelity publishing

---

src/features/controls.ts
src/three-components/ModelScene.ts

Fixes #806 
The first fix was a one-liner to force the pivot to recalculate when the target changes. This caused me to also notice it wasn't smoothly interpolating along with the camera, so I fixed that too.

Fixed autorotate interpolation

---

src/test/three-components/SmoothControls-spec.ts
src/three-components/SmoothControls.ts

Fixes #800 
Now when you set orbit to theta = 3.5*pi rad, it will immediately jump theta to 4*pi (no camera motion), then interpolate in the proper direction (-0.5*pi) to the set goal. Before we were clamping the goal between -pi and pi, which was part of how this bug formed.

Fixed camera reversal

---

src/three-components/StaticShadow.ts

Oops, I noticed a rounding error in #809 on the last models in https://googlewebcomponents.github.io/model-viewer/examples/staging-and-camera-control.html
I also added some comments.

fixed shadow rounding error

---

src/three-components/StaticShadow.ts

This comes down to precision, which varies a lot by GPU, so while I've tested this on Pixel2 XL, we should ideally try to verify on a few more phones. I didn't want to make the gap any larger, because you can start to see it when you rotate to floor level. I suppose this is another reason to remove the baked-in shadow entirely, but I don't see a robust way to identify it in general.

fix shadow Z-fight on mobile

---

index.html
src/features/loading.ts
src/model-viewer-base.ts
src/styles/conversions.ts
src/test/model-viewer-base-spec.ts
src/test/three-components/ARRenderer-spec.ts
src/test/three-components/ModelScene-spec.ts
src/test/three-components/Renderer-spec.ts
src/three-components/ARRenderer.ts
src/three-components/ModelScene.ts
src/three-components/Renderer.ts

This change introduces a new error event that is dispatched when we lose the WebGL context. It also changes the `type` of the previous error event from `"preload"` to `"loadfailure"`. Finally, it adds documentation for our error event, which was previously missing.
Some additional lingering cleanup intended for #739 has also been added. Also, the `Renderer` is no longer a "default" export as of this change. In general, "default" exports should be avoided (and technically are forbidden by the Google lint tools).
Fixes #801 
Fixes #816

Document errors, add error for lost context

---

index.html
src/features/staging.ts
src/test/features/staging-spec.ts

This change introduces an `auto-rotate-delay` attribute, which allows users to configure the a previously internal-only delay value that defaults to 3 seconds. After the delay has passed, the model will start rotating.
Additionally, this change revises our previous behavior for when `auto-rotate` is toggled. Previously, we would reset the "turntable" rotation when `auto-rotate` is disabled, causing the model to appear to jump back to its initial rotation. Now, the rotation is not reset when `auto-rotate` is disabled. In order to achieve the previous effect, a new `resetTurntableRotation` method has been introduced that sets the turntable's rotation back to 0.
Fixes #823 
Fixes #827

Introduce auto-rotate-delay attribute

---

src/features/controls.ts
src/test/features/controls-spec.ts

This change address an oversight from #739 , where intrinsics for `field-of-view` were not being updated appropriately.
Filed #835 for future refactor work here.

Fix FOV intrinsics

---

index.html
src/documentation/components/example-snippet.ts
src/features/controls.ts
src/features/staging.ts
src/template.ts
src/test/features/controls-spec.ts
src/test/index.ts
src/test/three-components/SmoothControls-spec.ts
src/test/utilities-spec.ts
src/test/utilities/animation-spec.ts
src/test/utilities/timer-spec.ts
src/three-components/SmoothControls.ts
src/utilities/animation.ts

This change addresses messed up wiggling in Safari 13 (and similar glitches in IE11).
As of this change, we now orbit the camera rather than rotate the pivot node while wiggling. The upside of this is that it now looks more like what the user sees when they interact with the model. The possible downside is that the camera smoothing looks aesthetically different from the original implementation.
I tried "jumping" the camera to its goal when wiggling. This achieves a similar look to the original implementation, but also causes the wiggle effect to layer poorly with other effects that change the camera orbit (such as the recently added scroll position tracking in #739 ).
The new implementation was manually tested and is known to work as intended IE11 and Safari 13.
Fixes #839 
Fixes #842

Fix wiggle in Safari and IE11

---

src/three-components/ModelUtils.ts

Fixes #848 
Quick fix, but we should remove it once we upgrade three.js, as the fix has already landed there.

Clone tangents

---

src/features/controls.ts
src/features/environment.ts
src/features/loading.ts
src/model-viewer-base.ts
src/test/features/environment-spec.ts
src/test/model-viewer-base-spec.ts
src/test/three-components/Renderer-spec.ts
src/three-components/Renderer.ts

When I implemented #833 I introduced the bug described in #847. We did defer loading models as intended, but since `IntersectionObserver` announces intersections somewhat late compared to property updates we were still performing other side-effects early. Among these effects was environment map generation.
With this change, environment map generation is also deferred until we are in the render tree. The rationale for this is that being `display: none` or outside of the viewport should be considered "no cost" in the typical case.
Also, a new, one-time progress activity has been introduced that measures the time before we get the first signal from `IntersectionObserver` that we are visible. This should account for any additional side-effects that measure progress early.
Fixes #847

Fix progress state thrashing on first configuration

---

examples/augmented-reality.html
src/features/ar.ts
src/test/features/ar-spec.ts

Although this is not currently a common case, we have been breaking Scene Viewer integration whenever the model URL contains sensitive query parameters. A common case for this is when models are hosted on static storage that allows token-based access. In such scenarios, the token is often added to the query string.
Fixes #742

Preserve query string when intenting

---

src/model-viewer-base.ts
src/test/features/environment-spec.ts
src/test/three-components/ARRenderer-spec.ts
src/test/three-components/ModelScene-spec.ts
src/test/three-components/Renderer-spec.ts
src/three-components/ARRenderer.ts
src/three-components/Debugger.ts
src/three-components/ModelScene.ts
src/three-components/Renderer.ts
src/three-components/StaticShadow.ts
src/three-components/TextureUtils.ts
src/utilities.ts

This change introduces a very light "debug" mode to `<model-viewer>`. Debug mode can be activated in two ways:
1. By adding a query parameter to the URL:
- `http://example.com/foo.html?model-viewer-debug-mode`
2. By including a global signal on the page with script:
```html
<script>
ModelViewerElement = ModelViewerElement || {};
ModelViewerElement.debugMode = true;
</script>
```
Activating debug mode currently does two things:
1. Enables verbose shader error messages on the GL context
2. Exposes renderer internal details with a globally dispatched `model-viewer-renderer-debug` event
An example of using this event looks like:
```html
<script>
self.addEventListener('model-viewer-renderer-debug', (event) => {
const {
THREE, // Limited subset of Three.js constructors
renderer // The singleton …
```

Add minimum viable debug mode

---

src/model-viewer-base.ts

This came up when building in google3. I'm actually surprised we were allowed to compile in this case.

Use correct property name for source event

---

CNAME

Per the docs, this needs to live in the root of our deployed source.
If we don't want to include the actual file here we could have it as a step in the deploy, but that seemed more complex.

Add CNAME pointing at modelviewer.dev to the root

---

src/three-components/PMREMGenerator.ts

This is necessary to avoid closure compiler renaming of these properties. In most cases like this, renaming is acceptable because the objects are not exported. However, in this case there is a relationship between the property key name and a literal value in the shader program, so renaming breaks the shader.

Make all freeform keys string literals

---

index.html
src/model-viewer-base.ts
src/test/model-viewer-base-spec.ts
src/utilities/data-conversion.ts

Fixes #858 
Adds `toBlob` to the `ModelViewerElementBase`.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob
The general approach was to delegate the `toBlob` on the model-viewer to the canvas. Instead of using callbacks like `HTMLCanvasElement` does with `toBlob`, I used promises so that it is possible to use `async/await` syntax. We can change this back if needed.

Implement toBlob function on ModelViewerElementBase

---

src/features/animation.ts
src/features/ar.ts
src/features/controls.ts
src/features/environment.ts
src/features/loading.ts
src/features/magic-leap.ts
src/features/staging.ts
src/model-viewer-base.ts

This change "declares" our mixin interfaces to ensure that our public custom element API isn't renamed by closure compiler. Some of our interfaces were incomplete and have been updated. Also, `@export` annotations have been added to the public API of the base class, as this is the most succinct way I could come up with to prevent that part of the public API from being renamed.
Note: `@property`-decorated API automatically gets decorated with `@export` for our purposes thanks to compiler magic.

Declare interfaces to prevent renaming

---

src/three-components/CachingGLTFLoader.ts

Fixes #903 
Only meshes should cast shadows, not lights (our shadow light is added later). I believe this means when lights are included in the glTF they are still illuminating the model (in addition to our environment light). I assume this is expected behavior, but if anyone feels otherwise, this is the place to change it.

turned off glTF light shadows

---

src/three-components/shader-chunk/encodings_pars_fragment.glsl.ts

Fix shader compilation error on a particular low-end device found at Target.
Follow-on work from this will include https://github.com/GoogleWebComponents/model-viewer/issues/921

Fix shader compilation on some low-end phones

---

src/features/controls.ts
src/test/features/controls-spec.ts

This change fixes a small bug where a race condition could override a user-configured `max-field-of-view` if the configuration was made before the model is loaded, or before an impending resize.
@elalish I'm not sure if the fix appropriate conveys the semantics of the original implementation (particularly adjustments for zoom). Your feedback there would be very welcome 🙇

Fix max-fov race condition

---

src/features/controls.ts
src/test/features/controls-spec.ts

Messed up a unit in #932 . This is the fix.
In fixing this, we also uncovered a bug that was causing another test to flake. Any `@property` member that also uses `@style` needs to have `hasChanged: () => true` configured for their `@property` decorator.

Units are hard

---

src/features/controls.ts
src/features/loading.ts
src/model-viewer-base.ts
src/test/features/loading-spec.ts

The core bug here is that `LoadingMixin` has very complex state and is rather difficult to reason about. It shares implementation details with the base class because it pertains to the only thing the base class does: load models given a `src`. `LoadingMixin` and related implementation in the base class deserve some refactoring to clean this up, but in the mean time I was able to do some light patching to ensure the state transitions work as intended.
This change also fixed some camera jank we had identified when resizing.

Fix double load and camera jank

---

examples/model-formats.html
src/features/controls.ts
src/features/loading.ts
src/model-viewer-base.ts
src/test/features/loading-spec.ts
src/three-components/ModelScene.ts
src/three-components/Shadow.ts

Fixes #891
I don't think we had an issue for this yet, but this fixes a problem @mrdoob found [here](https://model-viewer-tester.glitch.me/) when using a shadow and changing models. In addition to fixing this issue, we also uncovered a double load event, which @cdata was kind enough to fix and merge in here along with a resize jank fix.
I also updated our model-switching example to include a shadow to guard against regression.

Fixed shadow when updating src

---

src/three-components/ModelScene.ts
src/three-components/Shadow.ts
src/utilities/debug.ts

Fixes #939 
The actual fix is just a one-liner on the bounding box calculation. The other changes are to make the shadowHelper work better when it's being used for debug.

Fix animated shadows with bounding box below zero

---

packages/model-viewer/src/test/features/staging-spec.ts

Fixes a couple of flaky autoRotate tests. The key is waiting for an animation frame after loading, but before enabling autoRotation, since that first tick can have a delta including the whole loading time, which can end up staring the rotation too soon. The rest is just cleanup.

fix autoRotate flake

---

packages/model-viewer/src/features/annotation.ts
packages/model-viewer/src/features/controls.ts
packages/model-viewer/src/model-viewer-base.ts
packages/model-viewer/src/template.ts
packages/model-viewer/src/test/features/annotation-spec.ts
packages/modelviewer.dev/examples/annotations.html
packages/modelviewer.dev/examples/tester.html
packages/modelviewer.dev/index.html
packages/modelviewer.dev/src/tester.ts

Fixes #977 
Fixes #979 
In the spirit of getting our docs ready for release, I wanted to add a hotspot helper to our tester doc. In order to make this possible, I also had to add an API method, `getHitResult`, but I believe this is pretty generally useful anyway. Try out our interactive example and see how you can add hotspots by clicking on the model and they display the data-position and data-normal attribute values you need to put a hotspot there. 
One bug: I notice that different models are returning normal vectors seemingly in different coordinate systems. I'll resolve this before the PR lands, but I'd like some feedback in the meanwhile.

Hotspot helper

---

packages/model-viewer/src/test/features/scene-graph-spec.ts

There was a missing capitalization that caused a file request to work on OSX (case-insensitive FS) and fail on not-OSX (all our CI environments). Oops.
Fixes #1012

Fix scene graph spec

---

packages/model-viewer/src/template.ts

- defers control of pointer events to slotted elements, similar to opacity

annotations - allow for pointer events to be controlled on the slotted element

---

packages/model-viewer/src/features/annotation.ts
packages/model-viewer/src/features/annotation/hotspot.ts
packages/model-viewer/src/features/controls.ts
packages/model-viewer/src/model-viewer-base.ts
packages/model-viewer/src/template.ts
packages/model-viewer/src/test/features/annotation-spec.ts
packages/model-viewer/src/test/features/annotation/hotspot-spec.ts
packages/model-viewer/src/test/index.ts
packages/model-viewer/src/three-components/SmoothControls.ts
packages/modelviewer.dev/examples/annotations.html
packages/modelviewer.dev/index.html

This change proposes a handful of refinement tasks for the hotspots:
- Hotspots are now `pointer-events: none` when user is tumbling the model with a pointer (#981)
- Introduces support for `data-visibility-attribute` to enable easier CSS styling w/o requiring script (#989)
- Introduces a `hotspot-visibility` event that is dispatched on assigned hotspot nodes when their visibility changes (also #989)
- Adds a `--max-hotspot-opacity`, which is the "visible" counterpart to `--min-hotspot-opacity`
Thanks to #1020 the user can combine the above improvements to implement #980 for themselves until we have time to address it properly.
Fixes #981 
Fixes #989

Refinements to annotations feature

---

packages/model-viewer/src/features/controls.ts
packages/model-viewer/src/test/features/controls-spec.ts
packages/modelviewer.dev/index.html

This change proposes an instance method that enables authors to reset the interaction prompt state.
Fixes #792

Reset interaction prompt

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

The links to `CONTRIBUTING.md` in issue and PR templates look old. This PR updates the links.

Update the links to CONTRIBUTING.md in issue and PR templates

---

packages/model-viewer/src/three-components/ARRenderer.ts

Fixes: #1016 
Please refer to https://github.com/google/model-viewer/issues/1016#issuecomment-586032019 for the detail
**Notes**
* My platform I'm testing on is [Windows 10 + WSL Ubuntu](https://github.com/google/model-viewer/issues/1021#issuecomment-585985485). It seems `npm run test` couldn't run correctly, it stops during the test without any messages. I'm happy if someone runs the test on my behalf.
* I'm very new to &lt;model-viewer&gt; inside. Especially I don't see out of WebXR AR code so much then I'm not really sure if this solution is best. Feedback is very welcome.

Fix the black model problem in WebXR AR mode

---

packages/3dom/package-lock.json
packages/3dom/package.json
packages/3dom/src/context.ts
packages/3dom/src/facade/api.ts
packages/3dom/src/facade/three-js/material.ts
packages/3dom/src/facade/three-js/model-graft.ts
packages/3dom/src/facade/three-js/model.ts
packages/3dom/src/facade/three-js/pbr-metallic-roughness.ts
packages/3dom/src/facade/three-js/three-dom-element.ts
packages/model-viewer/package-lock.json
packages/model-viewer/package.json
packages/model-viewer/src/three-components/TextureUtils.ts
packages/modelviewer.dev/package-lock.json
packages/modelviewer.dev/package.json
packages/render-fidelity-tools/package-lock.json
packages/render-fidelity-tools/package.json

This should make it easier for other renderers to be implemented and used with `ThreeDOMExecutionContext`.
Partially address #1004

Describe facade in terms of abstract interfaces

---

packages/model-viewer/src/test/three-components/ModelScene-spec.ts
packages/model-viewer/src/three-components/ModelScene.ts

We had a small bug that prevented shadow intensity from being reset to 0 after being increased from 0.
Fixes #1032

Fix resetting shadow intensity to 0

---

packages/3dom/src/context-spec.ts
packages/3dom/src/context.ts
packages/model-viewer/src/features/scene-graph.ts
packages/model-viewer/src/test/features/scene-graph-spec.ts

Currently, we support inline 3DOM scripts in `<model-viewer>`:
```html
<script type="experimental-scene-graph-worklet">
console.log('Hello, world!');
</script>
```
This change proposes the addition of _external_ script support:
```html
<script type="experimental-scene-graph-worklet" src="./external-script.js"></script>
```
In support of this feature in `<model-viewer>`, a new method has been introduced to the `ThreeDOMExecutionContext`: `import`, which takes an external script URL and loads it into a running context.
In practice, the implementation of `import` is just a small refactor, because `eval` performed all the steps of `import` on a dynamically generated URL.

Support external 3DOM scripts

---

packages/model-viewer/src/features/scene-graph.ts

This is a style fix to address lint rules applied in google3. I did some investigation to see if we could incorporate a similar check into our linter. The rule we would want to activate is here: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-floating-promises.md
Unfortunately, the rule requires that we enable TypeScript type generation in the linter, and doing this caused it to hang and crash. So, I'm punting on that for now.

Fix floating promises

---

packages/model-viewer/src/test/three-components/ModelScene-spec.ts
packages/model-viewer/src/three-components/ModelScene.ts

This ensures a shadow in not created until needed, fixing a small regression from #1042.

fix shadow lazy creation

---

packages/3dom/src/api/material-spec.ts
packages/3dom/src/api/material.ts
packages/3dom/src/context.ts
packages/3dom/src/end-to-end-spec.ts
packages/3dom/src/facade/three-js/three-dom-element-spec.ts
packages/3dom/src/facade/three-js/three-dom-element.ts
packages/model-viewer/src/features/loading.ts
packages/model-viewer/src/test/helpers.ts
packages/model-viewer/src/test/index.ts
packages/model-viewer/src/test/three-components/CachingGLTFLoader-spec.ts
packages/model-viewer/src/test/three-components/GLTFInstance-spec.ts
packages/model-viewer/src/test/three-components/ModelUtils-spec.ts
packages/model-viewer/src/test/three-components/gltf-instance/ModelViewerGLTFInstance-spec.ts
packages/model-viewer/src/three-components/CachingGLTFLoader.ts
packages/model-viewer/src/three-components/GLTFInstance.ts
packages/model-viewer/src/three-components/Model.ts
packages/model-viewer/src/three-components/ModelUtils.ts
packages/model-viewer/src/three-components/gltf-instance/ModelViewerGLTFInstance.ts
packages/modelviewer.dev/rollup.config.js

This started out as a fix for the problem where 3DOM scene graphs expressed a unique material for every location in the scene graph where a material occurred. It turned out that this was an implementation problem caused in `CachingGLTFLoader` and related to how models are cloned. So, to address the issue I made a light refactor of the related code (which was overdue anyway). Some highlights from the change:
- Refactored `CachingGLTFLoader` and `cloneGltf`
- Separate loading/caching from model preparation/cloning
- Introduced `GLTFInstance`, a conveniently clone-able, dispose-able, API-compatible alternative to `GLTF`
- `CachingGLTFLoader` now loads a full GLTF-like, rather than just a scene
- `RoughnessMipmapper` is created once, rather than per-instance of `CachingGLTFLoader`
- Ensure …

Reduce to unique materials

---

packages/model-viewer/src/three-components/gltf-instance/ModelViewerGLTFInstance.ts
packages/model-viewer/src/three-components/shader-chunk/normalmap_pars_fragment.glsl.ts

This fixes a bug that was reported through a different channel. I had actually noticed before getting occasional triangles that would either be completely black or covered with random black noise, and traced it down to triangles with degenerate UV coordinates (different vertices with the same UV coords). It will only manifest if tangent vectors are not supplied.
I had assumed at first this was a problem with the authoring software, but it turns out this happens pretty often during compression by quantization, as happens with DRACO, etc. The problem is just NaNs creeping into the normal vector computation, so I've fixed that here.

Rendering fix for degenerate UVs

---

.github/workflows/unit-tests.yml
packages/3dom/karma.conf.js
packages/model-viewer/karma-legacy.conf.js
packages/model-viewer/karma.conf.js
packages/shared-assets/scripts/karma-hacks.js

Browser stack builds appear to be establishing overlapping tunnels. This may be due to misconfiguration on our part. I'm testing out amendments to our configuration in this PR.
We landed on forcing a unique tunnel ID into each `karma-browserstack-launcher` run. This ID is required to run BrowserStack tunnels in parallel, according to all documentation that I can find on the topic. This appears to work as described, but we'll need to keep our eyes on the build after landing this change just in case.
Original approach:
The new approach creates a distinct BrowserStack build (which, for the sake of pedantry, is different but related to the Github Actions build) for each group of connections we make during a Github Actions run. In theory, this will result in two BrowserStack builds for each …

Attempt to shard BrowserStack via project/build name

---

README.md
packages/model-viewer/README.md

- GoogleWebComponents -> google in a few spots
- Update links to our docs site (now https://modelviewer.dev) and fidelity testing (https://modelviewer.dev/fidelity/)
- Add a "getting started" link to the main page
Fixes #1123

Small URL updates

---

packages/model-viewer/src/features/ar.ts
packages/model-viewer/src/features/controls.ts
packages/model-viewer/src/three-components/ARRenderer.ts
packages/model-viewer/src/three-components/Model.ts
packages/model-viewer/src/three-components/ModelScene.ts
packages/model-viewer/src/three-components/Shadow.ts

Adds two-finger scaling to the webXR UX, based on the ar-scale attribute. This involved moving the target dampers from controls to ModelScene so that they could be used by ARRenderer as well (they were moved to controls from SmoothControls in the first UX PR).

Webxr scale

---

packages/3dom/karma.conf.js
packages/model-viewer/karma.conf.js

Something is very wrong with iOS13 on BrowserStack this week, so disabling until they get it working again.

disable iOS13 tests

---

packages/model-viewer/src/template.ts
packages/modelviewer.dev/examples/lazy-loading.html
packages/modelviewer.dev/index.html

I think this may have regressed as part of the seamless poster change in #890 . I don't think it's necessary for the poster to have a fallback color of `inherit` for seamless poster transitions to work, and also it means that in most cases, the built-in poster won't have any background color at all.

Ensure built-in poster has default background color

---

packages/model-viewer/src/template.ts

I have received feedback that the AR button is really difficult to push on mobile devices since it is too small. So I have just made the button size variable and the SVG image is scaled to 60% (which keeps the original ratio since 24px is 60% from 40px).

AR button size is now variable

---

packages/model-viewer/karma.conf.js
packages/model-viewer/src/features/loading.ts
packages/model-viewer/src/test/features/loading-spec.ts
packages/modelviewer.dev/examples/lazy-loading.html
packages/modelviewer.dev/index.html
packages/modelviewer.dev/package-lock.json
packages/render-fidelity-tools/package-lock.json

Fixes #832 
Fixes #502
The behavior of `preload` can now be attained with `loading="eager"`, similarly to the `<img>` and `<video>` elements. Additionally, `reveal="manual"` is now an option to keep the poster displayed until `dismissPoster()` is called. 
The diff is large because I had to update package-lock.json since we hadn't updated our internal version numbers since the release.

replaced preload with loading

---

packages/modelviewer.dev/examples/augmented-reality.html

This is a reminder to test things like size units, although without going into too much detail as a recommendation depends on target use case (including if you need to support only iOS 13).
Fixes #559

Add recommendations regarding verifying glTF->USDZ output

---

packages/model-viewer/src/model-viewer-base.ts
packages/model-viewer/src/test/three-components/Renderer-spec.ts
packages/model-viewer/src/three-components/Renderer.ts
packages/modelviewer.dev/examples/add.html

Fixes #1184 
Turns out I introduced this regression when I optimized us to use direct rendering when there is only one model-viewer instance. When adding the second, I didn't properly update the first. 
I also put in an unlinked example page, add.html, which I was using to diagnose this. I'm leaving it in because it's also useful for checking memory leaks, which I'm still chasing down.

Fix adding element

---

packages/model-viewer/src/three-components/ARRenderer.ts

Fixes #1190 
The first problem was caused by a line of code I didn't write, but I'm ashamed I read it so many times without noticing the fairly glaring error. The second problem was that we were failing to call resize when cleaning up webXR. I think I missed this because our examples all use a %width CSS which causes the resize observer to fire when leaving fullscreen, but it does not for fixed-width elements.

fixed multiple webXR issues

---

packages/model-viewer/src/three-components/ARRenderer.ts
packages/model-viewer/src/types/webxr.ts

There was a change that prevented webXR from launching in Chrome Canary due to a small spec change. This fixes it.

match webXR spec update

---

packages/modelviewer.dev/examples/lighting-and-environment.html

If you have the second and third examples on this [page](https://modelviewer.dev/examples/lighting-and-environment.html) both wiggling at once, the performance is terrible. Turns out this is because of the way Three.js handles backgrounds. There is only one background for the renderer we share among all elements; it will happily swap out texture images, but if those images are in different formats (.hdr vs .jpg), it causes the background shader to recompile, in this case recompiling twice per frame. It looks like major surgery to change's three's behavior and I don't expect the need for LDR and HDR skyboxes on the same page to be great anyway (especially since environment-image is unaffected). Instead I changed the example to explain.

fixed example performance

---

packages/model-viewer/karma.conf.js
packages/model-viewer/src/test/features/staging-spec.ts

This change attempts to quash our current round of test flakes with a two-pronged strategy:
1. Flakes in Firefox have been disabled (#1205, #1206)
2. Chrome 81.0 and Edge 80.0 have been replaced with Chrome 83.0 beta / Edge 83.0 beta (#1207)
I did two rounds of bisects in order to separate out and diagnose the problems. It was immediately apparent after the first bisect that there is A Problem™ in Chromium 80~81 that has been resolved as of Chromium 83.0 beta. A Google search suggests that this problem has been affecting other browsers as well (such as Brave).
Separately, I bisected for test flakes in non-Chromium browsers and discovered Firefox test flakes had been introduced in https://github.com/google/model-viewer/commit/6ed11e5bddedffdc0db7cf683b254f8549f6c650.
Hopefully all crashing …

Fix flakes of doom

---

packages/model-viewer/src/test/index.ts
packages/model-viewer/src/test/three-components/Damper-spec.ts
packages/model-viewer/src/test/three-components/SmoothControls-spec.ts
packages/model-viewer/src/three-components/Damper.ts

Fixes #1210
The issue is that with no `src`, the ideal camera distance is zero, which makes maximum radius zero, which is the normalization factor for the radius damper. That made it asymptotically approach zero forever because it was never close enough to stop. Fixed it by making the damper handle non-positive normalization values, which should be a general fix. I believe this problem could also have come up if someone set max-camera-orbit to zero or negative radius, but this'll handle those cases as well.

handle non-positive damper normalizer

---

packages/model-viewer/src/features/ar.ts
packages/model-viewer/src/template.ts
packages/model-viewer/src/three-components/ARRenderer.ts

Fixes #519 
Fixes #1098 
This adds the X exit button to the top-left of webXR; it takes the place of the exit fullscreen button as I've also removed the fullscreen fallback, which was broken anyway. It also switches webxr to the default ar experience. There is also some cleanup of vestigial codepaths and more complete post-session state reset.
A breaking change (though it was never documented) is that the `exit-fullscreen-button` slot is now the `exit-webxr-button` slot.

WebXR update

---

packages/model-viewer/src/features/controls.ts
packages/model-viewer/src/test/features/controls-spec.ts
packages/model-viewer/src/three-components/SmoothControls.ts

It may be useful to know the current FOV limits so user code can change them sensibly. And, to do this without needing to parse the attributes (duplicating work).

Add getters for FOV limits

---

.github/workflows/deploy-documentation.yml
.github/workflows/fidelity-tests.yml
.github/workflows/unit-tests-third-party.yml
.github/workflows/unit-tests.yml
packages/model-viewer/src/constants.ts
packages/model-viewer/src/features/controls.ts
packages/model-viewer/src/model-viewer-base.ts
packages/model-viewer/src/test/three-components/Renderer-spec.ts
packages/model-viewer/src/three-components/ModelScene.ts
packages/model-viewer/src/three-components/Renderer.ts
packages/modelviewer.dev/index.html

Fixes #1220 
Fixes #261
This is a major performance improvement, where we now detect dropped frames and scale down the rendering appropriately to maintain framerate. This also includes an additional performance improvement for firefox, where we use the fast, no-copy render path when there is only a single model visible in the viewport, rather than on the page in its entirety. I also found that we were needlessly rendering during the motionless part of the interaction prompt, so that's also fixed. Finally, we now render a first frame when the model loads even if it's not visible to fix #1220, since that seems like desired default behavior.

Dynamic render scaling

---

packages/3dom/src/facade/three-js/correlated-scene-graph-spec.ts
packages/3dom/src/facade/three-js/correlated-scene-graph.ts

Explanation copied from inline comment:
GLTFLoader creates a "default" material that has no corresponding glTF element in the case that no materials are specified in the source glTF. This means that for basic models without any of their own materials, we might accidentally try to present a configurable glTF material that doesn't exist. It might be valuable to make this default material configurable in the future, but for now we ignore it.
Fixes #1234

Ignore default material

---

LICENSE
packages/3dom/LICENSE
packages/model-viewer/LICENSE
packages/modelviewer.dev/LICENSE
packages/render-fidelity-tools/LICENSE

Turns out your copyright notice does not belong in the source license text.

use unmodified license text

---

packages/3dom/karma.conf.js
packages/model-viewer/karma.conf.js

Fixes #1207 
Interestingly, the `83.0 beta` we had been using started launching Chrome 84. Looks like Headless Chrome in Github actions has also been updated to 83 now, so that's reenabled. I also pushed out old Firefox version from 62 to 66, which looks to have removed a test flake I was seeing occasionally.

updated Chrome and Edge to 83

---

packages/model-viewer/src/features/ar.ts
packages/model-viewer/src/three-components/ARRenderer.ts
packages/model-viewer/src/three-components/Renderer.ts
packages/modelviewer.dev/index.html

Fixes #567 
This adds an `ar-status` event and attribute which reflects the status of webxr. I have a small demo I've been testing this on which I'll need to clean up for an example in our docs. I also need to add some documentation before I merge this, but figured it would be good to get some feedback first.

AR status event and attribute

---

packages/model-viewer/src/features/controls.ts

This fixes several small bugs I noticed while making a carousel example. After interaction, if the src was changed, then the prompt would start up again. The camera orbit would also get reset to our front view when switching src, except it could end up off due to the interaction prompt. I decided it's a better experience to keep the camera theta and phi consistent during src switching, and this is also more consistent with how we do it for webXR.

Make src changes more seamless

---

packages/model-viewer/src/constants.ts
packages/model-viewer/src/model-viewer-base.ts
packages/model-viewer/src/test/three-components/Renderer-spec.ts
packages/model-viewer/src/three-components/Renderer.ts

I found a workaround for the offscreen canvas bug, where the dynamic render resize was briefly visible as you'd get a flash of wrong canvas scaling. This can be mitigated by forcing the offscreen canvas to go through the multi-scene render path where it does an extra copy. Interestingly, this is not noticeably slower, and seems to be less janky.
I had to make this change now due to another bug: I found ToBlob() gave blank output with OffscreenCanvas disabled (on Chrome). This was a quick fix, but I'm concerned that it may still not work on Firefox or other browsers without OffscreenCanvas. I need to investigate this more and determine whether this is a model-viewer or browser bug.

reenable offscreen canvas

---

packages/render-fidelity-tools/test/renderers/model-viewer/index.html

This fixes Sponza, VC and SimpleMorph fidelity tests, which had the wrong camera position due to the radius being less than the default minimum.

set radius limits to not clamp fidelity test configurations

---

packages/model-viewer/src/constants.ts

We noticed the renders were inverted on ChromeOS, but only when offscreenCanvas was enabled. This is now disabled for CrOS as a workaround; next we need to file a bug on Chrome.

disable offscreenCanvas for ChromeOS

---

packages/model-viewer/src/test/model-viewer-base-spec.ts

This is to fix a flake we just started seeing in master on the toBlob dimensions test.

round size to integer before comparison

---

packages/model-viewer/karma.conf.js

We have a couple of test flakes that only seem to happen on Firefox 76, so disabling for now. This should be investigated further at a later date.

disable firefox76 testing

---

packages/model-viewer/src/model-viewer.ts
packages/model-viewer/src/test/index.ts
packages/modelviewer.dev/examples/animation.html
packages/modelviewer.dev/examples/augmented-reality.html
packages/modelviewer.dev/examples/fuzzer.html
packages/modelviewer.dev/examples/staging-and-camera-control.html
packages/modelviewer.dev/index.html

Making good on our promise to deprecate magic-leap, and also removing reference to the ar fallback which was removed from the code a few weeks ago. Also removed the `ar-modes` that were just set to the now default values.

remove magic-leap and fallback docs

---

packages/model-viewer/package-lock.json
packages/modelviewer.dev/package-lock.json
packages/render-fidelity-tools/package-lock.json
packages/render-fidelity-tools/package.json

I was having trouble running check-fidelity locally and realized our version of puppeteer was based on Chrome 80, which was giving us trouble. After updating it's now working fine for me, and I'm hoping this might fix our published fidelity results which are currently giving white renders inexplicably.

puppeteer 2.0->4.0

---

packages/model-viewer/POLYFILLS.md
packages/model-viewer/package-lock.json
packages/model-viewer/package.json
packages/model-viewer/src/template.ts
packages/modelviewer.dev/examples/accessibility.html
packages/modelviewer.dev/examples/add.html
packages/modelviewer.dev/examples/animation.html
packages/modelviewer.dev/examples/annotations.html
packages/modelviewer.dev/examples/augmented-reality.html
packages/modelviewer.dev/examples/customizing-ui.html
packages/modelviewer.dev/examples/fuzzer.html
packages/modelviewer.dev/examples/lazy-loading.html
packages/modelviewer.dev/examples/lighting-and-environment.html
packages/modelviewer.dev/examples/list.html
packages/modelviewer.dev/examples/model-formats.html
packages/modelviewer.dev/examples/multiple-elements.html
packages/modelviewer.dev/examples/rendering-showcase.html
packages/modelviewer.dev/examples/scene-graph.html
packages/modelviewer.dev/examples/staging-and-camera-control.html
packages/modelviewer.dev/examples/tester.html
packages/modelviewer.dev/examples/webxr.html
packages/modelviewer.dev/index.html
packages/modelviewer.dev/package-lock.json
packages/modelviewer.dev/package.json
packages/modelviewer.dev/scripts/ci-before-deploy.sh
packages/render-fidelity-tools/package-lock.json
packages/render-fidelity-tools/package.json
packages/render-fidelity-tools/test/renderers/model-viewer/index.html

This was vestigial, and seemed to be causing problems on IE11. I also added a SceneViewer example to the augmented-reality page to make it easier to compare to WebXR (and since the fullscreen polyfill was originally to help SceneViewer when it failed to launch).

Remove fullscreen polyfill

---

.github/workflows/deploy-documentation.yml

I just noticed that modelviewer.dev has not been loading on IE11 because we were neglecting to build the legacy bundles during our deployment step. This has probably been broken for a while.

deploy IE11 builds to github pages

---

packages/model-viewer/src/constants.ts

There are just too many bugs to continue using this for now. We already had to disable it for ChromeOS because the renders were upside-down. Now it turns out it also fails to render over chrome remote desktop. It has no measurable performance benefit, so really it is only needed in order to move rendering off the main thread. Since that's a ways out anyway, we'll disable, file Chrome bugs and revisit when those are fixed.

disable offscreenCanvas

---

packages/model-viewer/src/features/ar.ts
packages/model-viewer/src/features/environment.ts
packages/model-viewer/src/features/loading.ts
packages/model-viewer/src/test/model-viewer-base-spec.ts

Fixes #1286 
The problem was relative vs. absolute URLs. This problem was introduced by the fix to another bug where URLs were being converted from relative to absolute when set as attributes, but not when set from JS. Turns out we were doing a similar thing in other parts of the code, so all the URL handling has been updated here.

fix relative urls

---

packages/model-viewer/src/three-components/CachingGLTFLoader.ts

Fixes #1332 
Since the progress was NaN, our state machine never saw loading as completed, even though it had.

fix NaN progress

---

packages/editing-adapter/package.json
packages/space-opera/package.json

..otherwise, build won't work after a clean, because tsc --incremental will assume there's nothing to be done (given the tsbuildinfo is still there).

Make sure we remove tsbuildinfo cache upon clean

---

packages/render-fidelity-tools/test/renderers/model-viewer/index.html

A temporary workaround for model-viewer's golden is taken before the model is actually loaded.

set timer for model-viewer's model-ready event

---

packages/3dom/src/facade/api.ts
packages/3dom/src/facade/three-js/model-graft.ts
packages/model-viewer/src/template.ts

Fixes #1379
This fix was just a one-liner; apparently `overflow:hidden` is only respected on Safari in combination with `position:relative`. In the process I discovered a larger issue where the scene-graph was not working in Safari, which is also fixed here. Safari doesn't implement EventTarget, so I had to copy a hack from another part of model-viewer. What troubles me most is that our scene-graph-spec should have caught this on our Safari tests. I still have no idea how it passed.

Fix scene-graph for Safari

---

packages/modelviewer.dev/examples/scene-graph.html

The texture switching wasn't working in our scene-graph examples because they used paths that aren't served on our dev pages. I've updated them to point to the 2.0 folder instead of sourceModels.

fixed texture asset paths

---

packages/model-viewer/src/template.ts

During release testing I noticed the poster doesn't cover the hotspots, so in the annotations example when the model loaded, the annotations would snap into place while the model faded in, which was slightly jarring. This is a very simple fix, which will only work as long as there are less than 1,000 hotspots on a given model, but at that point there are probably bigger problems.

make poster cover hotspots

---

packages/model-viewer/src/features/loading.ts
packages/model-viewer/src/test/features/loading-spec.ts

This fixes a small regression where the poster was being shown even when just switching between models.

fix poster regression

---

packages/3dom/karma.conf.js
packages/model-viewer/karma.conf.js
packages/modelviewer.dev/scripts/ci-before-deploy.sh

These were out of date from the days when Chrome 81 was giving our unit tests headaches. Also added the WaterBottle to stop modelviewer.dev from getting 404s.

Update CI browser versions

---

packages/3dom/karma.conf.js
packages/model-viewer/karma.conf.js
packages/modelviewer.dev/index.html

Fixes #1157 
Also fixed the support tables not being legible in Firefox; for some reason alt tags fixed it.
Also turned off Mobile Safari 12 testing, as it's been getting too flaky and 14 is nearly out.

update browser support tables

---

packages/model-viewer/src/test/features/environment-spec.ts

Switch the unit test to point to the new hdr file path. Looks like all test passed. 
Do you also want me to add the "cheat" dspbr golden of furnace test in this pr? If so, i should remove dspbr from exclude, right?

replace hdr file path in unit testing

---

packages/model-viewer/src/features/loading.ts
packages/space-opera/src/components/camera_settings/camera_settings.ts
packages/space-opera/src/components/poster_controls/poster_controls.ts

Fixes #1428 
In fact this was a regression that also affected the old interactive example, so both are now fixed. I also updated the editor to set the initial camera when creating a poster, like the interactive example does.

Fix editor poster generation

---

packages/model-viewer/src/features/loading.ts
packages/render-fidelity-tools/src/artifact-creator.ts
packages/render-fidelity-tools/src/common.ts
packages/render-fidelity-tools/src/workflows/test-fidelity.ts
packages/render-fidelity-tools/test/renderers/model-viewer/index.html

1.  Added two raf when firing the poster-dismissed event, to make sure the event is fired after poster completely disappear
2. Check if model-viewer hang there when rendering golden. If it hang there after some time(maxTime), stop it and report error and keep testing the rest scenarios
3. Check if the golden captured is completely white. If so, report error and keep testing the rest scenarios
A new error emerges. I think 10 seconds is long enough, but i will try longer maxTime later. 
Also, not sure what caused the huge chunk of logging. I think the only thing i did related to model-viewer is adding an additional raf. I will hunt it down

Improve auto fidelity test

---

packages/model-viewer/src/features/ar.ts
packages/model-viewer/src/test/features/ar-spec.ts
packages/modelviewer.dev/index.html

Fixes #1030
Fixes #1314
This adds a new `quick-look-button-tapped` event, replacing the work started in #1435; thanks @hybridherbst! I could use some help verifying that this is working for everyone's use cases.

quickLook event

---

packages/model-viewer/src/features/ar.ts
packages/model-viewer/src/test/features/ar-spec.ts
packages/model-viewer/src/three-components/ARRenderer.ts
packages/modelviewer.dev/examples/augmented-reality.html
packages/modelviewer.dev/index.html

Fixes #1330 
Fixes #1329
We now automatically fallback from webXR to SceneViewer if something goes wrong, and we disable the AR button if none of the requested modes work. When this happens we now set the `ar-status` attribute to `'failed'` and dispatch a similar event. I haven't found a way to detect if QuickLook has failed.

Handle AR failures better

---

packages/model-viewer/package.json

Fixes #690 
Fixes #1192 
Fixes #1208 
Fixes #1310 
Well, really I'm hoping this is the root of the problem; could use help validating this. Unfortunately it won't be easily testable until we put out a new npm release with this fix, so I'll plan to do that fairly soon. I believe the problem is that `main` is supposed to point to a umd version of the library, instead of the es6 module version it was pointing at.

fixed npm main

---

packages/space-opera/rollup.config.js

Fixes #1485 
I thought I tested my deduplication of three.js in this bundle, but clearly not well enough. Rolling it back for now while I work on a proper fix (the current space-opera.js bundle is far larger than it should be).

temporary dedupe rollback for editor

---

packages/3dom/package-lock.json
packages/3dom/package.json
packages/model-viewer/package-lock.json
packages/model-viewer/package.json
packages/model-viewer/src/three-components/gltf-instance/ModelViewerGLTFInstance.ts
packages/modelviewer.dev/index.html
packages/space-opera/package-lock.json
packages/space-opera/package.json
packages/space-opera/rollup.config.js

Removes a small work-around and decreases the editor's bundle size by deduplicating three.js. Also adds a link to our fidelity results from modelviewer.dev.

threejs r120.1

---

packages/model-viewer/src/features/animation.ts
packages/model-viewer/src/features/annotation.ts
packages/model-viewer/src/template.ts
packages/model-viewer/src/three-components/ARRenderer.ts
packages/modelviewer.dev/examples/annotations.html
packages/modelviewer.dev/examples/customizing-ui.html
packages/modelviewer.dev/styles/examples.css

Fixes #1419 
It was by pure luck this ever worked before v1.0; this makes the display much more intentional.

hide hotspots until model renders

---

.eslintrc.yaml
packages/3dom/src/api/image.ts
packages/3dom/src/api/material.ts
packages/3dom/src/api/model-kernel.ts
packages/3dom/src/api/model.ts
packages/3dom/src/api/pbr-metallic-roughness.ts
packages/3dom/src/api/sampler.ts
packages/3dom/src/api/texture-info.ts
packages/3dom/src/api/texture.ts
packages/3dom/src/api/three-dom-element.ts
packages/3dom/src/facade/model-graft-manipulator.ts
packages/3dom/src/facade/three-js/correlated-scene-graph.ts
packages/3dom/src/facade/three-js/image.ts
packages/3dom/src/facade/three-js/material.ts
packages/3dom/src/facade/three-js/model-graft.ts
packages/3dom/src/facade/three-js/model.ts
packages/3dom/src/facade/three-js/pbr-metallic-roughness.ts
packages/3dom/src/facade/three-js/sampler.ts
packages/3dom/src/facade/three-js/texture-info.ts
packages/3dom/src/facade/three-js/texture.ts
packages/3dom/src/facade/three-js/three-dom-element.ts
packages/3dom/src/test-helpers.ts
packages/3dom/src/utilities.ts
packages/model-viewer/src/test/three-components/Renderer-spec.ts

ESLint got pickier about specifying return types, which I think is good practice anyway. I've added them all across 3dom where they were missing to remove the warnings.

3DOM Return types

---

packages/model-viewer/src/features/staging.ts
packages/model-viewer/src/test/features/staging-spec.ts
packages/modelviewer.dev/index.html

Fixes #1541 
Now the `resetTurntableRotation()` method takes an option argument for the desired value in radians. This will allow scriptable rotation relative to the environment.

manual turntable rotation

---

packages/model-viewer/src/features/controls.ts
packages/model-viewer/src/test/features/controls-spec.ts
packages/modelviewer.dev/examples/staging-and-camera-control.html

Fixes #447 
I've added an example of pan to the staging-and-camera-control examples. This is a decent generic pan example, but there are a lot of possible variations that are use-case specific, so hopefully this gives everyone enough to go on to build their own. I don't see this entering our API, as it can be confusing in many cases and it doesn't work for all scenarios that require pan - for instance a city model might constrain pan to the horizontal plane instead of screen space.

Pan example

---

packages/model-viewer/src/features/controls.ts
packages/modelviewer.dev/examples/lighthouse.html

Turns out there was also about 750ms of prompt delay added on top of the threshold, so that's now been removed so that zero means immediately.

set performance example prompt threshold to zero

---

packages/model-viewer/src/features/ar.ts

Fixes #272
The AR button would fail to be hidden if a transparent poster was used. This ensures it only appears once the model is loaded.

show AR button after loading

---

packages/model-viewer/src/features/loading.ts

Fixes DRACO loading error that came with the r121 update.

update DRACO to match three's version

---

.github/workflows/unit-tests-third-party.yml
.github/workflows/unit-tests.yml

Revert this once our check clears. No releases until this has been reverted and full testing passes.

Disable BrowserStack testing until our license recovers

---

packages/model-viewer/src/features/ar.ts
packages/model-viewer/src/template.ts
packages/model-viewer/src/test/features/animation-spec.ts
packages/model-viewer/src/test/features/annotation-spec.ts
packages/model-viewer/src/test/features/ar-spec.ts
packages/model-viewer/src/test/features/controls-spec.ts
packages/model-viewer/src/test/features/environment-spec.ts
packages/model-viewer/src/test/features/loading-spec.ts
packages/model-viewer/src/test/features/loading/status-announcer-spec.ts
packages/model-viewer/src/test/features/scene-graph-spec.ts
packages/model-viewer/src/test/features/staging-spec.ts
packages/model-viewer/src/test/helpers.ts
packages/model-viewer/src/test/model-viewer-base-spec.ts
packages/model-viewer/src/test/model-viewer-spec.ts
packages/model-viewer/src/test/three-components/Hotspot-spec.ts
packages/model-viewer/src/test/three-components/Renderer-spec.ts
packages/model-viewer/src/test/three-components/SmoothControls-spec.ts
packages/model-viewer/src/test/utilities/focus-visible-spec.ts
packages/model-viewer/src/test/utilities/progress-tracker-spec.ts
packages/model-viewer/src/utilities.ts
packages/modelviewer.dev/examples/loading/index.html
packages/modelviewer.dev/examples/model-formats.html

Fixes #1627 
Fixes #568
Reverts #1567 and #1401 as these were not great fixes, especially after some other work fixed up the hotspot/poster issue better. This also moves `waitForEvent()` from test helpers to utilities, as I'm now using it in the main code base. 
Now using `reveal="manual"`, the poster will remain and AR can be activated before downloading the model. In this way scene-viewer and quick-look can be activated while only downloading the model once (this is always true with webXR). In this way the model-viewer element can become just a customizable "Enter AR" button if desired.

AR button before load

---

.github/workflows/unit-tests-third-party.yml
.github/workflows/unit-tests.yml

This reverts #1595 
Our BrowserStack license should be good to go now, so enabling our cross-browser testing again.

Revert "swap to basic testing (#1595)"

---

package.json
packages/model-viewer/src/constants.ts
packages/model-viewer/src/features/ar.ts

Fixes #1640 
Fixes #1093 
App intents do not work properly on Firefox android or Oculus browser, so we're disabling scene-viewer for those browsers.

Disable scene-viewer on browsers that don't handle intents

---

packages/3dom/karma.conf.js
packages/model-viewer/karma.conf.js
packages/model-viewer/package.json

BrowserStack has iOS 14 on iPhone 11, so let's use that in addition to our iPhone 8 on iOS 13.

add iOS 14 testing, put src, lib back on npm

---

packages/modelviewer.dev/examples/loading/index.html

`i` was redefined when we merged two examples pages.

fix cycling model example

---

packages/model-viewer/src/features/controls.ts
packages/model-viewer/src/three-components/SmoothControls.ts
packages/modelviewer.dev/data/docs.json
packages/modelviewer.dev/data/examples.json
packages/modelviewer.dev/examples/stagingandcameras/index.html

Fixes #1424 
Also adds an example, to make it clear that default scroll/pinch behavior is reenabled.

add disable-zoom

---

packages/modelviewer.dev/examples/annotations/index.html

A link in the Annotations Example documentation to the interactive example `tester.html` was broken.

Fix broken link to tester.html

---

packages/model-viewer/src/test/model-viewer-spec.ts
packages/model-viewer/src/three-components/gltf-instance/ModelViewerGLTFInstance.ts
packages/model-viewer/src/three-components/gltf-instance/gltf-2.0.ts
packages/modelviewer.dev/examples/scenegraph/index.html

Fixes #1678 
The material clone is a shallow copy, so now we're cloning the textures as well (but not the underlying images). I've also updated the scene-graph example to demonstrate the bug, so that will now serve as a regression test.

cloning textures

---

packages/model-viewer/src/features/controls.ts
packages/model-viewer/src/test/features/animation-spec.ts
packages/modelviewer.dev/data/docs.json
packages/modelviewer.dev/data/examples.json
packages/modelviewer.dev/examples/stagingandcameras/index.html

Fixes #1727
This is a new example for rotating the skybox instead of the camera. Thanks to @dhruvadhia-cela as this builds off of his #1570. I also added the missing `toString()` method to `getCameraOrbit` to further simplify this.

Rotate environment example

---

packages/model-viewer/src/features/animation.ts
packages/model-viewer/src/test/features/animation-spec.ts
packages/model-viewer/src/three-components/Model.ts
packages/modelviewer.dev/data/docs.json

This provides a read-only `duration` property which surfaces the duration of the current animation, in the same way that `currentTime` can be accessed.
This PR is derived from a discussion in an [issue](https://github.com/google/model-viewer/issues/1736) on the same topic.
Documentation has also been updated to include a description of the property.
Implements Issue #1736

Added read-only 'duration' property to animations

---

packages/model-viewer/karma-legacy.conf.js
packages/model-viewer/src/features/annotation.ts
packages/model-viewer/src/model-viewer.ts
packages/model-viewer/src/test/model-viewer-base-spec.ts
packages/model-viewer/src/test/model-viewer-spec.ts
packages/model-viewer/src/three-components/ARRenderer.ts
packages/model-viewer/src/three-components/Renderer.ts
packages/model-viewer/src/three-components/Shadow.ts
packages/render-fidelity-tools/src/common.ts

Also some light cleanup in Renderer.ts and the tests. Unskipped the webGL context loss test now that the Chrome bug is fixed.

Replace functions deprecated by three.js

---

packages/model-viewer/src/model-viewer-base.ts
packages/model-viewer/src/three-components/Renderer.ts
packages/modelviewer.dev/data/docs.json

Fixes #1715 
Well, I'm not actually sure that's true since I don't have a windows machine to test on. However, we've seen problems on Windows Chrome before relating to rounding errors on canvas dimensions making the canvas suddenly very blurry (dramatically lower resolution). I noticed a place where we introduced rounding error, so I've fixed that here. Help verifying would be much appreciated.

avoid render scale rounding errors

---

packages/model-viewer/src/test/three-components/Renderer-spec.ts

I think the gl context loss test was resetting the renderer and so the minimum render scale setting was being lost. I moved it into the setup function of the renderer tests so that it's more assured. Hopefully this deflakes the "only renders dirty scenes" test, since I think it was getting erroneous renders due to the render scale changing if the hardware was too slow.

deflake Renderer test

---

packages/editing-adapter/src/gltf/gltf_model.ts
packages/editing-adapter/src/gltf/gltf_model_test.ts
packages/editing-adapter/src/testing/utils.ts

Fixed two delete texture bugs that resulted in an invalid GLB file:
1. The byteOffset is optional for a BufferView. We weren't handling the case where a byteOffset was missing, resulting in invalid GLBs.
2. Deleting a texture file of an odd file size results in an invalid GLB. This happened because the place holder image we replace deleted textures with is 68 bytes, resulting in odd byteOffsets when we adjust the byteOffset for subsequent bufferViews. Accessors have specific data alignment requirements for the byteOffset.

Fix delete texture bugs

---

packages/model-viewer/src/features/ar.ts
packages/model-viewer/src/test/features/ar-spec.ts
packages/modelviewer.dev/data/docs.json
packages/modelviewer.dev/examples/augmentedreality/index.html

This removes the `quick-look-browsers` attribute, which was used to screen out iOS Chrome from AR mode because of an old and long-since fixed bug. This seems pretty unnecessary now, so we'll just allow any iOS browser to try and launch AR.

remove quick-look-browsers

---

packages/model-viewer/src/features/ar.ts
packages/model-viewer/src/test/features/ar-spec.ts

Fixes #1733 
Occlusion in scene-viewer is not a great experience with the current sensors, so we're disabling it by default now. It can be enabled by putting a query param on the `src` URL: `https://somewhere.org/model.glb?disable_occlusion=false`. You can also set any other scene-viewer query params in this way, like title, link, etc. This PR has also removed the default values for title and link that used to be set from alt and the source website, as that is rarely what a user would want anyway. Alt text is not a title, and the link was doing the same thing as the exit button, except sucking you into a WebView instead of taking you back to your browser.

Disable scene-viewer occlusion

---

packages/modelviewer.dev/data/docs.json

The current link, https://github.com/google/model-viewer#supported-formats, refers to a non-existent anchor. I think this is supposed to refer to GLTFLoader, but I can't find any details on supported formats aside from the GLTF extensions list.

Change broken link in docs.json

---

packages/space-opera/editor/index.html
packages/space-opera/src/components/mobile_view/components/mobile_expandable_section.ts
packages/space-opera/src/components/mobile_view/components/mobile_modal.ts
packages/space-opera/src/components/mobile_view/mobile_view.ts
packages/space-opera/src/components/mobile_view/open_mobile_view.ts
packages/space-opera/src/components/mobile_view/reducer.ts
packages/space-opera/src/components/mobile_view/styles.css.ts
packages/space-opera/src/components/mobile_view/types.ts
packages/space-opera/src/components/mobile_view/utils.ts
packages/space-opera/src/components/model_viewer_preview/model_viewer_preview.ts
packages/space-opera/src/reducers.ts
packages/space-opera/src/styles.css.ts
packages/space-opera/src/types.ts

Mobile Bridge Cleanup

---

packages/model-viewer/src/features/scene-graph.ts

If a variant was specified as an attribute it was not being loaded; it would only update when changed after load.

fixed initial variant

---

packages/space-opera/src/components/model_viewer_preview/model_viewer_preview.ts
packages/space-opera/src/components/utils/render_model_viewer.ts

Trying to load a "malformed" glb into the editor yields a white screen with no information to the end user.
The issue with the attached glb file is that while the model is fine, some materials reference textures from './'. 
three.js tries to `fetch` those files, the requests fail and the "error" custom event is triggered but not listened to from space-opera.
Malformed glb: [Ring.glb.zip](https://github.com/google/model-viewer/files/5874330/Ring.glb.zip)

Add basic error handling in space-opera viewer preview when loading malformed glb.

---

packages/model-viewer/src/three-components/SmoothControls.ts

There was built into the default `touch-action: "pan-y"` a special case to effectively turn it into `touch-action: "none"` when the modelviewer element was fullscreen. However, this doesn't work well at all for iframes and it's honestly a little confusing anyway. From now on, if you know your page doesn't need to scroll, you'll have to remember to set `touch-action: "none"` manually.

removed fancy default for pan-y

---

packages/model-viewer/src/three-components/ARRenderer.ts

Fixes #2060 
Fixes #2071 
Here is the bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1184085
It will be fixed soon, but as it'll take time to roll out to stable, we're putting in this workaround in the meanwhile.

work around Chrome WebXR bug

---

packages/model-viewer/src/three-components/ModelScene.ts
packages/model-viewer/src/three-components/TextureUtils.ts

When a model is in the viewport but hasn't finished loading yet, the intersection observer triggers updateSource multiple times with the same source, resulting in extra retainerCounts for that source's URL in CacheEvictionPolicy. The url check at the top of the function is supposed to avoid that, but wasn't working because this.url is not set until after some async calls.
Fixes #1674 
It's possible there are other leaks still, but I think this was the big one.

Fix CacheEvictionPolicy retainerCounts  

---

packages/space-opera/src/components/best_practices/render_best_practices.ts

A dangling event handler dispatches an error when the "Use Custom Progress Bar" checkbox is not selected and the user is trying to switch to another HDR or even another model.
- Select a model from the dropdown
- Uncheck "Progress bar" in "Best practice" section.
- Switch to "Lighting" tab
- Select any other HDR from the dropdown
```
Uncaught TypeError: Cannot read property 'style' of null
at HTMLElement.onProgress (space-opera.js:36313)
at DocumentFragment.LoadingModelViewerElement.<computed> (space-opera.js:98778)
at ProgressTracker.dispatchEvent (space-opera.js:95316)
at ProgressTracker.[announceTotalProgress] (space-opera.js:95374)
at ProgressTracker.beginActivity (space-opera.js:95346)
at TextureUtils.generateEnvironmentMapAndSkybox (space-opera.js:94736)
at environment …
```

Prevent error on 'progress' event with default progress bar.

---

packages/space-opera/src/components/file_modal/file_modal.ts
packages/space-opera/src/components/model_viewer_snippet/components/open_button.ts
packages/space-opera/src/test/shared/texture_picker/texture_picker_test.ts

https://github.com/google/model-viewer/blob/b5678a4e064356a2ae4fad2712a6fdc2e8e5ac7b/packages/space-opera/src/components/model_viewer_snippet/components/open_button.ts#L225
[Blob](https://developer.mozilla.org/ja/docs/Web/API/Blob) does not have `name` prototype and [File.name](https://developer.mozilla.org/ja/docs/Web/API/File/name) exsists, so I guessed `File` is correct.

Change Blob to File in file_modal.ts

---

packages/model-viewer/src/three-components/gltf-instance/ModelViewerGLTFInstance.ts

Some draco compressed models that share metalness and roughness maps resulted in errors cloning models because roughness mipmap generation state isn't properly duplicated. This changes fixes the issue by waiting to generate roughness mipmaps until after the clone has occured.

Wait to generate roughness mipmaps until after clone

---

packages/model-viewer/src/features/ar.ts
packages/model-viewer/src/features/controls.ts
packages/model-viewer/src/features/staging.ts
packages/model-viewer/src/model-viewer-base.ts
packages/model-viewer/src/test/features/annotation-spec.ts
packages/model-viewer/src/test/features/controls-spec.ts
packages/model-viewer/src/test/three-components/Renderer-spec.ts
packages/model-viewer/src/three-components/Damper.ts
packages/model-viewer/src/three-components/ModelScene.ts
packages/model-viewer/src/three-components/Renderer.ts
packages/model-viewer/src/three-components/SmoothControls.ts
packages/model-viewer/src/three-components/gltf-instance/ModelViewerGLTFInstance.ts
packages/modelviewer.dev/data/docs.json
packages/modelviewer.dev/examples/stagingandcameras/index.html

* Setting the attribute affects camera smoothing and model position interpolation.
* Adds 'decayMilliseconds' to Damper.update() method call.
* Updates to docs - adds interpolation-decay
* Updates to the Interpolation example - adds interpolation-decay attribute example
Fixes #580

Adds 'interpolation-decay' attribute

---

packages/model-viewer/src/three-components/Shadow.ts
packages/modelviewer.dev/examples/augmentedreality/index.html

I changed the WebXR example to remove `ar-scale="fixed"` because I found a bug where scaling the model and then switching models caused the shadow to be at the wrong scale. This is now fixed and the updated example will serve as a manual regression test.

Fixed scaled shadows

---

packages/model-viewer/src/features/annotation.ts
packages/model-viewer/src/test/features/annotation-spec.ts
packages/model-viewer/src/test/three-components/ARRenderer-spec.ts
packages/model-viewer/src/three-components/ARRenderer.ts
packages/model-viewer/src/three-components/ModelScene.ts
packages/model-viewer/src/three-components/Renderer.ts

It turns out #2279 broke both hotspot placement and raycast placement in WebXR, which is fixed here. It was broken somewhat subtly because of the way XRManager handles camera updates. Before our animation frame is called, WebXR updates the internal `cameraVR`, which is great. However, upon calling `threeRenderer.render(scene, camera)` the camera I pass in gets updated to the view matrix of cameraVR, but not the projection matrix. Since I'm using my camera for other activities that happen before render time (like raycasting and CSS2D rendering), this has the effect of making my camera delayed by a frame and also have the wrong projection matrix. I worked around this by moving my CSS2D rendering to after the 3D render call, but I still had to call `xr.getCamera()` once, which feels like a …

Fix hotspots

---

packages/modelviewer.dev/examples/augmentedreality/index.html
packages/modelviewer.dev/styles/examples.css

Fixes #1830 
I believe the problem was a bunch of rapid element resizing due to the element's size being dependent on vh, which changes as the URL bar scrolls in and out of sight. At fixed aspect ratio, it seems to be much happier. I also found a small error in the background example which was solved by simplifying the CSS.

improved examples CSS

---

packages/model-viewer/src/three-components/ARRenderer.ts
packages/modelviewer.dev/examples/augmentedreality/index.html

Fixes #2180 
Fixes #1270 (sort of; that issue has multiple things and some have to be external HTML)
This should help especially for large models or models you're inside of. Now that AR mode starts from the same camera position as 3D mode, if you've set the user up inside of the model, that will work in AR too, and rotation will be possible with two fingers (since you can't find a one-finger spot outside of the bounding box).

added two-finger rotation for WebXR

---

packages/model-viewer/src/model-viewer-base.ts
packages/model-viewer/src/template.ts
packages/model-viewer/src/test/three-components/Renderer-spec.ts
packages/model-viewer/src/three-components/ModelScene.ts
packages/model-viewer/src/three-components/Renderer.ts

This is experimental, for using model-viewer to control an external renderer instead of using Three.js. This removes any dependence on glTF and even allows non-model-based experiences (e.g. generative systems, etc). Of course the model-dependent parts of our API will also cease to function in this situation.

add external renderer support

---

packages/model-viewer/src/features/ar.ts
packages/model-viewer/src/three-components/ARRenderer.ts
packages/modelviewer.dev/data/docs.json
packages/modelviewer.dev/examples/augmentedreality/index.html

Fixes #2340 
Description in the docs. Also fixes the bug where session-started was happening later than the start of the session. Not-tracking is only posted if it's true after the first 30 XR frames have passed (about 1 second), to give ARCore a chance.

add ar-tracking attribute

---

packages/model-viewer/src/template.ts
packages/modelviewer.dev/data/docs.json
packages/modelviewer.dev/src/docs-and-examples/create-html.ts
packages/modelviewer.dev/styles/docs.css

Replacing #2258 
I've removed most of the CSS custom properties from the docs and replaced them with corresponding `part`s that will give more flexibility to styling our default elements without having to define more and more properties. The old custom properties still work, but are deprecated, so please switch over to using the parts instead. They'll be removed when we do a 2.0 release, though that's not likely to be soon. 
I also removed the undocumented interaction-prompt part, since that seemed likely to only lead to trouble and I didn't add a poster part for the same reason, since its CSS is pretty important to its functionality.

deprecate custom properties in favor of parts

---

packages/model-viewer/src/features/ar.ts
packages/modelviewer.dev/examples/augmentedreality/index.html
packages/modelviewer.dev/examples/scenegraph/index.html

@kolodi A slight simplification of #2374 in order to release the USDZ memory earlier. Also added info about `ios-src` and how auto-generation interacts with the scene-graph API.

simplified USDZ and added docs

---

packages/model-viewer/src/test/three-components/gltf-instance/ModelViewerGLTFInstance-spec.ts
packages/model-viewer/src/three-components/gltf-instance/ModelViewerGLTFInstance.ts

Fixes #2386 
The transform was being applied twice since the duplicate was made a child rather than a sibling.

fixed transform duplication issue

---

packages/model-viewer/src/three-components/gltf-instance/ModelViewerGLTFInstance.ts

Fixes #2396 
I remembered running into this some time ago: `texture.needsUpdate`. Baffling why it was only a problem in Firefox/Safari and not Chrome.

Fix cloning issue on Firefox/Safari

---

packages/model-viewer/src/three-components/ARRenderer.ts

Fixes #2402 
Rotation was never meant to be enabled for wall placement.

removed two-finger rotation for wall placement

---

packages/model-viewer/src/template.ts

Fixes #2393 
The simplifies the progress bar CSS so that it is more ergonomic to style using `part`. It is slightly different than it used to be, fading out instead of sliding up, but given its small default height, I'd say most people will be unlikely to notice the difference. @maciekglowka does this look like a reasonable change?  I verified that your initial CSS works as expected now.

simplified progress bar CSS for easier styling

---

packages/model-viewer/src/test/features/scene-graph/model-spec.ts
packages/model-viewer/src/test/three-components/gltf-instance/correlated-scene-graph-spec.ts
packages/model-viewer/src/three-components/gltf-instance/correlated-scene-graph.ts

Fixes #2419 
We created a default material in the correlated scene graph, but failed to clone it.

fixed default material in scene-graph

---

packages/model-viewer/src/features/ar.ts
packages/modelviewer.dev/index.html
packages/modelviewer.dev/styles/examples.css

Fixes #2397 
Now if the user clicks the AR button on iOS with reveal="interaction" (no loaded model yet) and no ios-src, we will trigger the model load in order to have something to convert to USDZ. Also added AR to the front page and made its CSS consistent with the other examples.

fixed USDZ generation with reveal=interaction

---

packages/model-viewer/src/three-components/gltf-instance/ModelViewerGLTFInstance.ts
packages/modelviewer.dev/examples/augmentedreality/index.html

Fixes the AR Custom Button example on iOS. Apparently "needs a newer version of iOS" also means "couldn't find that URL".

removed bad example path

---

packages/editing-adapter/karma.conf.js
packages/model-viewer/karma.conf.js
packages/space-opera/karma.conf.js

Related discussion: #2194
It doesn't seem that `$ num run test:ci` runs on WSL2.
```
$ npm run test:ci
> test:ci
> ./node_modules/.bin/lerna run test:ci --stream
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 4 packages: "npm run test:ci"
@google/model-viewer: > @google/model-viewer@1.7.1 test:ci
@google/model-viewer: > npm run test
@google/model-viewer: > @google/model-viewer@1.7.1 test
@google/model-viewer: > karma start --single-run
@google/model-viewer: (node:13498) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./dist/" in the "exports" field module resolution of the package at /mnt/c/Users/Takahiro/Documents/model-viewer/packages/model-viewer/node_modules/systemjs/package.json.
@google/model-viewer: Update this …
```

Add workaround for the karma test on WSL

---

packages/model-viewer/src/three-components/ModelUtils.ts

Adds buffer normalization check before de-quantizing
follow up to #2450

adds buffer normalization check

---

packages/model-viewer/src/features/scene-graph.ts
packages/model-viewer/src/three-components/CachingGLTFLoader.ts
packages/model-viewer/src/three-components/GLTFInstance.ts
packages/model-viewer/src/three-components/gltf-instance/VariantMaterialExporterPlugin.ts
packages/model-viewer/src/three-components/gltf-instance/VariantMaterialLoaderPlugin.ts
packages/model-viewer/src/three-components/gltf-instance/correlated-scene-graph.ts

This PR adds glTF `KHR_materials_variants` extension export support based on my Three.js glTF loader/exporter plugins
* [Three.js glTF loader KHR_materials_variants extension plugin](https://github.com/takahirox/three-gltf-extensions/tree/main/loaders/KHR_materials_variants)
* [Three.js glTF exporter KHR_materials_variants extension plugin](https://github.com/takahirox/three-gltf-extensions/tree/main/exporters/KHR_materials_variants)
**Changes**
* Copy the plugin source codes into &lt;model-viewer&gt; repository, rather than importing them, for easier maintenance
* Rewrite them to TypeScript from JavaScript
* Register the plugins to `GLTFLoader` and `GLTFExporter`
* Some minor internal API change. See my review comments.
**Notes**
* I replaced [our `KHR_materials_variants` handlers for …

glTF KHR_materials_variants extension export support

---

packages/model-viewer/karma.conf.js

BrowserStack is investigating why iOS13 has gone from flaky to not working at all. Meanwhile, I'd like our automated tests to pass.

remove ios13 testing while BrowserStack's test runner is down

---

packages/model-viewer/src/test/three-components/gltf-instance/correlated-scene-graph-spec.ts
packages/model-viewer/src/three-components/gltf-instance/correlated-scene-graph.ts

Default material was being created even in cases where an object node did have a material (such as a group node)
This is a follow up to #2419 - tested with the same asset to verify that this PR does not cause a regression with the case where the glTF only has the default material.

* Resolves extraneous materials being created.

---

packages/model-viewer/src/three-components/GLTFInstance.ts

Resolves problem with memory overflow when GLTFInstance object is being repeatedly created and disposed.
Fixes: [#2139](https://github.com/google/model-viewer/issues/2139)

dispose material textures when disposing GLTFInstance

---

packages/model-viewer/src/test/three-components/ARRenderer-spec.ts
packages/model-viewer/src/three-components/ARRenderer.ts
packages/model-viewer/src/three-components/PlacementBox.ts
packages/model-viewer/src/three-components/SmoothControls.ts

Addressing what I hope is the biggest part of #2413, this changes the WebXR UX to allow user interactions all the time, instead of blocking them until the model is placed on the floor/wall. I think this improves the experience quite a bit and makes it less annoying/visible to the user when ARCore is struggling. However, there is not much we can do about ARCore's failures to find especially walls. We could potentially implement something like Scene Viewer's UI here, but that's pretty complicated and has it's own user education issues. We'll go with simple for now, but please add your thoughts to the above-linked discussion. 
Also fixes an existing bug where the zoom was sometimes not where you left it when returning from a WebXR session.

Move before place

---

packages/model-viewer/src/three-components/ARRenderer.ts

This fixes the bug @tpsiaki noticed on wall placement (it could also happen in non-wall mode, just less likely).

ensure touch is used when the hit is filtered

---

packages/model-viewer/src/features/ar.ts

Fixes a bug where the AR button showed up on android even if there was no `src`.

don't show AR button when there's no src

---

packages/model-viewer/src/features/environment.ts
packages/model-viewer/src/three-components/Renderer.ts
packages/space-opera/src/components/model_viewer_preview/model_viewer_preview.ts

Fixes #782 
This is tricky to test; you have to put a break point in the render loop, then set `window.renderer = this.threeRenderer` to keep a handle. Then you remove the break point and continue and in the console put `window.renderer.forceContextLoss()` and verify the render is gone. Then put `window.renderer.forceContextRestore()` and verify the render is working again (the bug was that the object would show up black instead of lit because our lighting was not getting properly restored). I tried to make an automated test out of this, but for some reason it is not behaving properly.

fixed context restoration

---

packages/model-viewer/src/features/scene-graph.ts
packages/model-viewer/src/test/features/scene-graph-spec.ts
packages/space-opera/src/components/materials_panel/materials_panel.ts
packages/space-opera/src/components/shared/texture_picker/texture_picker.ts
packages/space-opera/src/test/materials_panel/materials_panel_test.ts
packages/space-opera/src/test/shared/texture_picker/texture_picker_test.ts

Fixes #2668 
Turns out this was properly exporting GLBs with the same output format as input format (for JPG and PNG), but would convert any separately uploaded texture from JPG to PNG. I also fixed a small bug where uploaded textures were not updating the editor's UX properly.

Export JPGs in GLB

---

packages/model-viewer/src/three-components/SmoothControls.ts

As discussed in #2687, I refactored the mouse/touch handling in SmoothControls to get rid of the checks on `event.type` and `touchMode` in `onPointerMove`. Instead, the correct switch case is determined in `touchstart` and `mousedown` and assigned directly as a move handler.
I remained faithful to the old behavior with two exceptions described below, which I consider welcome consequences of a more elegant approach.
1.  After zooming with 2 touches, lifting one touch will resume rotation. I consider this a significant UX improvement as the old behavior was a big nuisance for me personally.
2. Zooming during a scroll is now disallowed. Previously, it was allowed to initiate a zoom interaction with two touches even when the first touch interaction was determined to be a scroll. 
On Android …

Remove checks about event nature in onPointerMove

---

packages/model-viewer/src/features/controls.ts
packages/model-viewer/src/three-components/SmoothControls.ts

Based on the [logs (or lack thereof) produced on iOS](https://github.com/google/model-viewer/issues/2729#issuecomment-907334260) on branch `lucadalli:debug-ios-zoom`, it seems that if two touches happen at the same time, iOS only fires one `touchstart` event 😵🤯
The previous implementation was banking on the fact that each touch fires a `touchstart` event.
These changes should hopefully fix the issue.

Fix iOS zoom

---

packages/render-fidelity-tools/src/artifact-creator.ts
packages/render-fidelity-tools/src/common.ts
packages/render-fidelity-tools/src/components/renderer-harness.ts
packages/render-fidelity-tools/src/workflows/test-fidelity.ts
packages/render-fidelity-tools/test/renderers/model-viewer/index.html

We've had a lot of weird flakiness in our fidelity tests that we didn't understand, so we just turned the flake into a warning so we could ignore it. However, the fidelity tests actually catch quite a few nasty regressions, so I'd rather they were all functional. I found a few sketchy things that I've fixed here. I was only able to get a consistent repro on a single model locally, and this fixed that, but we'll see if the CI agrees.
And it looks like it does! Seems the catch for the poster issue must have been somehow wrong, but there's no poster problem now and once that check was removed everything seems to be working well.

fixed renderer-harness

---

packages/modelviewer.dev/examples/stagingandcameras/index.html

Updates relevant examples to be in line with the changes to SmoothControls.
Favors simplicity over completeness.
For example: after swiping vertically on the [panning example](http://localhost:8080/packages/modelviewer.dev/examples/stagingandcameras/#panning) to scroll, it is possible to add a second touch and pan while scrolling. SmoothControls has guards against zoom while scrolling but an unsavory amount of redundancy is necessary to port them to the examples.
To avoid this, we should consider adding an API to allow for user-defined `touchModes`.

Update controls-related examples

---

packages/model-viewer/src/features/scene-graph.ts
packages/model-viewer/src/features/scene-graph/model.ts
packages/model-viewer/src/features/scene-graph/nodes/primitive-node.ts
packages/model-viewer/src/test/features/scene-graph-spec.ts
packages/model-viewer/src/test/features/scene-graph/nodes/primitive-node-spec.ts
packages/modelviewer.dev/data/docs.json
packages/modelviewer.dev/examples/scenegraph/index.html

Allows passing 'null' to enableVariant() API in order to switch the material back its initial setting.

Restore initial material

---

packages/model-viewer/src/features/ar.ts
packages/model-viewer/src/three-components/ModelScene.ts
packages/model-viewer/src/three-components/Shadow.ts

Fixes #2748 / #2736
The problem was that the turn table's state was not being kept when resetting a shadow for a new model. I'm actually surprised it was so tricky to repro. When I was in there I found some other bugs and confusing bits of code that I cleaned up as well, for instance switching from wall back to floor was not working.

Shadow clipping

---

packages/space-opera/editor/index.html
packages/space-opera/src/components/model_viewer_snippet/components/open_button.ts
packages/space-opera/src/components/model_viewer_snippet/model_viewer_snippet.ts
packages/space-opera/src/components/shared/expandable_content/expandable_section.css.ts

Fixes #2768 / #2767
I must have moved an element when I was refactoring  that I shouldn't have. I also made the snippet non-sticky, which makes the editor much more usable on mobile.
I was  surprised to find there was no test  for this, but I  tried adding one and now  I think I know why. When adding a  test for the snippet, the download button is part of  that, which imports `JSZip`, a commonJS module with a default export. It all works with rollup, but Karma chokes on it  with a  pretty baffling error message. I  tried a bunch of things, but could not get  it to resolve the import, so I'm punting on that test for now.

Fix editor export

---

packages/space-opera/src/components/ibl_selector/ibl_selector.ts
packages/space-opera/src/test/ibl_selector/ibl_selector_test.ts
packages/space-opera/src/types.ts

Now neutral lighting is available in the editor, and we're default to it as well. We don't change the MV default to avoid breaking changes, but the purpose of  the editor is to be opinionated and choose what we think is best for most users. And we can change it whenever we want without anything being a breaking change.

default editor to neutral lighting

---

packages/space-opera/src/components/model_viewer_snippet/components/download_button.ts

Fixes #2810 / #2791
We really need some automated end-to-end regression tests, which means we need to figure out the module resolution issue on JSZip and Jasmine.

fixed editor download regression

---

packages/space-opera/src/components/mobile_view/mobile_view.ts
packages/space-opera/src/components/mobile_view/open_mobile_view.ts

Mobile deployment was broken because it was trying to  treat "neutral" as a URL. In the process of fixing that, I found a bunch of other strange things in the deployment code that I've tried to clean up a bit. I'm also finding strange results with SceneViewer, but some of that is present on the previous version anyway, so I'll look into that more later.

fix mobile deploy for neutral lighting

---

packages/model-viewer/src/features/environment.ts
packages/model-viewer/src/test/features/environment-spec.ts
packages/model-viewer/src/test/three-components/TextureUtils-spec.ts
packages/model-viewer/src/three-components/TextureUtils.ts

Fixes #1955 
This problem has always been flaky, but has been getting steadily worse. In my testing it seems to be fine with this change where I've removed our PMREMGenerator in favor of using the one now built into three.js. This has exposed some odd things about three.js, but I've managed to work around them for now. I'll plan to add some PRs to three.js this cycle to address them.
All the random corruption issues seemed to come down to one render target disposal; I'm fine with a little extra GPU memory to keep Safari's driver from puking. 
However, I'm still seeing an occasional  bug (only on iOS and less common) where either some or all  of my GLB textures  are gone. It's not the lighting, because  even the emissive channel of DamagedHelmet disappears. I've also seen the mixer in this …

Work  around Safari  PMREM corruption

---

packages/model-viewer/src/three-components/Renderer.ts

Fixes #2915 
There's a bunch of discussion in three.js and apparently there's a chrome bug in webGL2 around a particular sRGB format. Hopefully a better fix will be coming soon, but until then, it  seems our best way around this performance issue is to go back to WebGL1 for the moment.

switch back to WebGL1Renderer

---

.github/workflows/deploy-documentation.yml

The fidelity tests have their own run on the PR anyway, so skip blocking the deployment step if they fail, especially since they are occasionally flaky anyway.

allow deployment if fidelity fails

---

.github/workflows/deploy-documentation.yml
packages/model-viewer/karma.conf.js
packages/model-viewer/src/test/features/ar-spec.ts
packages/model-viewer/src/test/three-components/ARRenderer-spec.ts

Fixes #2949 
To catch regressions like #2949 since we do have basic tests for black renders, and this device has an old GPU which reproduces problems like the above. I expect  our unit tests to fail  on this PR until I revert #2936, so I'm double-checking here first.
Edit: the new tests successfully caught the problem, and also verify its  solution, so we're good to go.

added Huawei P30 to automation

---

packages/model-viewer/src/features/ar.ts
packages/modelviewer.dev/examples/twitter/player.html

This was actually a MV bug where if you  add the  `src` after  the `ar` attribute it wouldn't enable the AR button. In addition to fixing that, I put a work-around in the  twitter card, since that  operates off of the latest release, rather than master.

fixed AR button on  twitter card

---

packages/model-viewer/src/features/scene-graph/image.ts

Fixed a bug where BasisU textures were not having a URI set, which caused the editor to choke on making their thumbnails.

Buffer view

---

packages/model-viewer/src/three-components/ARRenderer.ts
packages/model-viewer/src/three-components/PlacementBox.ts

While debugging WebXR mode I noticed we were recompiling some shaders that shouldn't. A couple of small fixes: 
1) The placement box is transparent  and was double-sided, which was causing it to be rendered twice (with two different shaders).
2) The shadow is turned off in AR until the model is set on  the floor. Turning  off the  shadow recompiles the  shader, so instead I turn it to a small (invisible) value.

use fewer shaders

---

packages/space-opera/src/components/model_viewer_snippet/components/open_button.ts
packages/space-opera/src/components/model_viewer_snippet/model_viewer_snippet.ts

Just a small feature request from an internal user. I still  think WebP is the only way to  go  for  posters, but apparently the poster button is also used  for quickly generating images  for other  purposes.

added poster type dropdown

---

packages/model-viewer/src/features/loading.ts

When the reveal strategy is AUTO, clicking on the screen was triggering progress change as every click was added as a new ongoing activity.
@elalish

Click triggering Progress when reveal strategy is auto fix

---

packages/model-viewer/src/features/controls.ts
packages/model-viewer/src/three-components/ModelScene.ts
packages/model-viewer/src/three-components/SmoothControls.ts
packages/modelviewer.dev/data/docs.json
packages/modelviewer.dev/examples/annotations/index.html

Fixes #3071 
Fixes #3012 
I also simplified the Midgard Serpent example and set the min radius up to 10% which helps with the nonlinear zoom. The reason I didn't use a log like for FoV is because the radius can  go to  zero (or even negative). There's a lot of assumptions about what you're actually looking at, so it's hard to get it  right for all cases. I think I'm going to leave  it as is for now instead of trying to solve #3013. 
I've also added  a `zoom(keyPresses)` function to allow mimicking of the default  zoom behavior using buttons and such. This  was requested to aid accessibility and generally make programatic control more similar to interactions.

fixed some bugs and updated  an  example

---

packages/model-viewer/src/features/scene-graph/model.ts

Resolve an async bug that occurs when two nodes reference the same material. The first node starts loading a material and marks it as loaded, then while waiting for Three to complete the actual material setup the second node begins loading the same material and which is now marked as loaded thus it tries to fetch the cached material which is not actually available because the first node was still waiting on Three.
Fixes #3086

Fix for bug #3086

---

packages/model-viewer/src/test/utilities/progress-tracker-spec.ts
packages/model-viewer/src/utilities/progress-tracker.ts

We had a report that the progress-tracker was not passing through results when only a single activity was being tracked. Turns out the math in there was pretty weird, so I think this will be better. I also removed the  symbols and IE workarounds  since this file hadn't been touched in awhile.

better math for progress-tracker

---

packages/modelviewer.dev/examples/augmentedreality/index.html
packages/modelviewer.dev/scripts/ci-before-deploy.sh

Demonstrates how the background can show through the (glTF transmission extension) windows of the ToyCar, while preserving the specular reflections.

improved transparency  example

---

packages/modelviewer.dev/examples/twitter/generator.html
packages/modelviewer.dev/examples/twitter/generator.js

This allows arbitrary CSS strings for the `style` extra parameter.

encode special chacters for query params in twitter generator

---

packages/model-viewer/src/features/scene-graph.ts
packages/model-viewer/src/features/scene-graph/image.ts
packages/model-viewer/src/features/scene-graph/texture.ts
packages/modelviewer.dev/examples/scenegraph/index.html

Added the possibility to set a custom name to the model-viewer texture object.
The model-viewer image name has been set to the file name (plus extension) if the source field is valorized. 
The CreateTextures example has been updated in order to display these new values.

Set texture name

---

README.md

The npm version 6.14 is no longer **the** recommended version.

Removing outdated npm version text from README

---

packages/model-viewer/src/three-components/TextureUtils.ts

Async functions without an `await` expression are executed synchronously. So there is no need to make them `async`.
Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function ("The body of an async function can be thought of as being split by zero or more await expressions. Top-level code, up to and including the first await expression (if there is one), is run synchronously. In this way, an async function without an await expression will run synchronously.")

Remove unnecessary async/await in TextureUtils

---

README.md

While working on #3224, I had again issues with setting up model-viewer development on WSL. This time, I took some notes, and added them to the Readme. There's a few lines that everyone using WSL should read (e.g. the magic trick to get started is "clone via https from inside WSL, not from inside Windows"), and a number of concrete error messages and issues I ran into that I added behind a foldout.

WSL troubleshooting

---

packages/space-opera/src/components/model_viewer_snippet/components/validation.ts
packages/space-opera/src/components/model_viewer_snippet/components/validation_utils.ts

Helpful to determine if the units are off for AR. If it's wrong, you can use our `scale` attribute to correct it.

added dimensions to editor validation report

---

packages/model-viewer/src/three-components/ModelUtils.ts

Fixes #3189 
Sure enough, three's bounding box computation doesn't apply bone transforms at all. I fixed this so long as you set `bounds="tight"`, since that is our custom bounding logic we control (and it's better, so you should use it anyway). I'll also put in a PR to three.js to fix the underlying problem upstream.

handle skinned mesh in bounds=tight

---

packages/model-viewer/src/utilities.ts

Turns out *some* search pages don't bother including a meta viewport tag... who knew?

pixelRatio fix

---

packages/model-viewer/src/features/controls.ts
packages/model-viewer/src/template.ts
packages/model-viewer/src/test/features/controls-spec.ts
packages/model-viewer/src/test/features/scene-graph/model-spec.ts
packages/model-viewer/src/test/three-components/ModelScene-spec.ts
packages/model-viewer/src/test/three-components/SmoothControls-spec.ts
packages/model-viewer/src/three-components/ARRenderer.ts
packages/model-viewer/src/three-components/ModelScene.ts
packages/model-viewer/src/three-components/SmoothControls.ts
packages/modelviewer.dev/data/docs.json
packages/modelviewer.dev/examples/annotations/index.html
packages/modelviewer.dev/examples/stagingandcameras/index.html
packages/space-opera/src/types.ts

Adds `enable-pan` as an attribute so that no extra JS is needed to enable panning interactions. Pan is limited to the bounding sphere of the model. Tapping on the model focuses on that point, while tapping off the model zooms back to the original framing. When panning, the center point is shown visually (and can be suppressed/changed using the `pan-target` slot) and when the pan gesture ends, the camera is focused on that model point (if there was a surface under the dot), so that the camera doesn't orbit around a random point in space.

Pan attribute

---

packages/model-viewer/src/features/environment.ts
packages/model-viewer/src/three-components/ModelScene.ts
packages/model-viewer/src/three-components/ModelUtils.ts
packages/model-viewer/src/three-components/Shadow.ts
packages/model-viewer/src/three-components/SmoothControls.ts
packages/modelviewer.dev/data/docs.json
packages/modelviewer.dev/examples/scenegraph/index.html
packages/modelviewer.dev/examples/stagingandcameras/index.html

Identifies pre-baked shadows in the model (unlit, transparent, axis-aligned planes) and removes them from framing calculations. Also disables them if `shadow-intensity` is non-zero so that only one type of shadow is shown. Added `hasBakedShadow()` method to query the model. 
Also fixed some bugs from the last PR: tap-recentering was enabled always instead of only when `enable-pan` was specified. Fixed `positionAndNormalFromPoint` to ignore hits on shadows.

Baked shadows

---

packages/model-viewer/src/features/animation.ts
packages/model-viewer/src/three-components/ModelScene.ts
packages/modelviewer.dev/examples/animation/index.html

Fixes #3223 
This was painful to debug; I think there's a three.js bug in here somewhere, but our own animation code is also a little convoluted. This workaround seems to fix it, but I should probably go in and refactor this sometime. I also changed our example to repro the bug and serve as a manual regression test.

fixed reverse play

---

packages/model-viewer/src/three-components/Renderer.ts
packages/modelviewer.dev/data/docs.json
packages/modelviewer.dev/data/examples.json
packages/modelviewer.dev/examples/loading/index.html

You can now monitor our dynamic render scaling to know what kind of rendering performance your users are seeing. I've added an example that shows how the process works with a complicated and slow-to-render model that will tend to trigger GPU throttling on many less powerful devices. This also demonstrates how to control the behavior with `minimumRenderScale` and allows you to see what tradeoffs that creates.

added render-scale event

---

packages/model-viewer/src/three-components/SmoothControls.ts

I realized when panning that my finger was not staying on the same part of the model as I moved. Turns out the sensitivity needs to account for both radius *and* FoV.

account for fov in pan sensitivity

---

packages/model-viewer/src/three-components/SmoothControls.ts

Fixes #3334 
By popular demand, `enable-pan` will no longer zoom in on a tap: it will only shift the camera target. Tapping on the background will still zoom back out.

remove tap-zoom-in

---

packages/model-viewer/src/three-components/SmoothControls.ts

Fixes https://github.com/google/model-viewer/issues/3334#issuecomment-1086174404
I managed to repro with `pan-y`, where dragging up/down doesn't start a 3D interaction - that also caused the pan target to erroneously show and not hide. Now fixed; thanks for the head's up @hybridherbst. It was tricky for me to repro at first.

ensure pan target appears and disappears correctly

---

packages/modelviewer.dev/examples/annotations/index.html

Fixes #3281 
Okay, on closer inspection, I think the only reason this example was zooming too fast is that it was set to have no FoV range (max = min = 45deg). We base the zoom on changing the FoV, so if that fails, we have a fallback that's getting used for radius. With these small tweaks to the example it now feels just fine to me. 
The bigger question: right now a single zoom "click" is set to change the zoom by a fixed amount of `log(FoV)`, which means if the FoV range decreases, it takes fewer "clicks" to cross that range (because it tries to change FoV and radius in proportion to their extents). Should we instead target a fixed number of "clicks" traversing the range of the zoom limits? If so, how many? Will it be weird that small zoom ranges have less zoom sensitivity? 
Would love …

updated FoV in thor example

---

package-lock.json
packages/model-viewer/package-lock.json
packages/model-viewer/package.json
packages/model-viewer/src/test/model-viewer-spec.ts
packages/model-viewer/src/three-components/GLTFInstance.ts
packages/modelviewer.dev/package-lock.json
packages/render-fidelity-tools/package-lock.json
packages/space-opera/package-lock.json

As helpfully noted by @deenns: https://github.com/mrdoob/three.js/issues/23953#issuecomment-1110742946, we had a memory leak due to GLTFLoader switching to `ImageBitmap` while we had not updated our `dispose()` method. That's done here, along with a package-lock update to pull in the latest three.js types.

fixed ImageBitmap memory leak

---

packages/model-viewer/src/features/controls.ts
packages/model-viewer/src/three-components/SmoothControls.ts

Upon switching to pointer events, I noticed that the context menu would cause our pointerUp method to never be called. Turns out this is a known bug in most browsers: https://github.com/w3c/pointerevents/issues/408
So, I'm now calling it manually to keep our state in a good place. So much for the reliability of `pointercancel`...

fixed context menu pointer cancel

---

packages/model-viewer/src/three-components/CachingGLTFLoader.ts
packages/modelviewer.dev/src/docs-and-examples/sidebar.ts

Fixes #3414
This bug was exposed by #3399, but the error appears to be long-standing: I don't think our `modelCacheSize` was ever working correctly. The idea is to cache X models in GPU memory to facilitate rapid switching. It appears we were accidentally disposing of them all and three.js was happily re-uploading them. However, once I disposed of the source data, that was no longer possible, hence the black textures. 
Hopefully this doesn't start causing out-of-memory problems for our users; it was always intended to work this way, but we effectively had `modelCacheSize = 0` enforced on everyone, which should really only be used by folks switching between very memory-intense models. In any case, that will be the solution for anyone encountering a regression here, unless I've introduced …

fixed cache

---

packages/space-opera/src/components/shared/tabs/styles.css.ts
packages/space-opera/src/components/shared/tabs/tab.ts
packages/space-opera/src/components/shared/tabs/tabs.ts

Overrides `mwc-tab` and creates `me-tab` and exposes the min-width property to fix space opera's seemingly missing 5th, inspect, tab
Workaround for:
material-components/material-web#2609

Override MWC tab to expose min-width

---

packages/model-viewer/src/features/controls.ts
packages/model-viewer/src/test/features/controls-spec.ts
packages/model-viewer/src/three-components/ModelScene.ts
packages/model-viewer/src/three-components/SmoothControls.ts

Fixes https://github.com/google/model-viewer/discussions/3386#discussioncomment-2618327
This is important now that we have pan causing tap-to-recenter. This change will allow that type of user-interaction to be listened for.

make target change fire camera-change event

---

packages/model-viewer/src/features/environment.ts
packages/model-viewer/src/three-components/ModelScene.ts

Fixes #3398 
In addition, we found some furniture models with baked shadows that don't use the unlit extension, so we're no longer checking that.

update baked shadow criteria

---

packages/model-viewer/src/three-components/SmoothControls.ts

Apparently Chrome on Android 12 will emit a pointermove event even if the pointer didn't move. Go figure.

fix pan-y for Android 12

---

packages/model-viewer/src/three-components/SmoothControls.ts

Fixed another small regression, where two-finger pinch was not scaling the page under `disable-zoom` like it ought to.

fix disable-zoom for touch

---

packages/render-fidelity-tools/src/components/image-comparison-app.ts
packages/render-fidelity-tools/src/components/images-4-up.ts

Fixes the missing images in our glTF fidelity comparison page.

added missing .js for fidelity comparisons

---

packages/model-viewer/src/features/ar.ts
packages/model-viewer/src/test/features/ar-spec.ts

#3425
This change allows extended AR QuickLook parameters (EG `custom`, `checkoutTitle`, `checkoutSubtitle`, etc) to be appended after the `src` path as `#` hash fragment when using auto USDZ generation and there is no `ios-src` property. 
Any / all defined `#` params get appended to USDZ blob without discrimination (AR QuickLook will ignore any invalid params).
Define `src` as something like:
`https://example.com/model.gltf#custom=path-to-banner.html`
Omit `ios-src`
Include `"quick-look"` in `ar-modes` to trigger auto USDZ generation.
When opening AR on iOS, USDZ will be auto generated and displayed with custom banner in AR.
Two tests created:
- replicate src hash to usdz blob url
- replicate src hash to usdz blob and set hash for fixed scale …

Support extended AR QuickLook parameters when auto generating USDZ blob

---

packages/space-opera/src/components/shared/snippet_viewer/snippet_viewer.ts
packages/space-opera/src/test/snippet_viewer/snippet_viewer_test.ts

Lit comments were being stripped greedily in `snippet-viewer`. This means when doing manual DOM insertion like with hotspots, the `` regex was matching the entire line of:
```html
<button slot="ar-button" id="ar-button">View in your space</button>
```
rather than just individual comments. See:
| Before | After |
| -- | -- |
| ![image](https://user-images.githubusercontent.com/5981958/168404144-af137b13-b318-4f40-b0e7-89111c619056.png) | ![image](https://user-images.githubusercontent.com/5981958/168404152-ce780bf2-1cc7-4cc0-9974-8f975abc747c.png) |
fixes: #3455

Do not greedily strip lit comments in snippet-viewer

---

packages/model-viewer/src/features/scene-graph/api.ts
packages/modelviewer.dev/data/docs.json
packages/modelviewer.dev/data/examples.json
packages/modelviewer.dev/examples/scenegraph/index.html
packages/modelviewer.dev/src/docs-and-examples/create-html.ts

None of this functionality is new, but I'm finally adding our Materials API to our public docs, and in so doing, marking it as public API and not experimental/internal. I've also renamed this section of our docs from Scene-Graph to Materials because this is what we are actually exposing. In fact we've made a conscious decision to *not* expose the whole glTF scene graph, as this would make our API too large to properly maintain and would blur the distinction between model-viewer and three.js. 
Some extra methods exist on `model` that are not yet documented as we are not sure they are API-stable yet, so they are not officially public. I've also removed the glTF export example, as I'm not confident the options parameter we inherit from three.js is API-stable.

Add Material docs

---

packages/model-viewer/src/three-components/ModelScene.ts

Fixes #3531 
It wasn't even hitting the shadow, but the blur plane. Honestly raycaster should probably skip `!visible` objects anyway, but at least it's easy to work around.

don't hit invisible geometry

---

packages/model-viewer/src/model-viewer-base.ts
packages/model-viewer/src/template.ts
packages/model-viewer/src/three-components/Renderer.ts

https://github.com/google/model-viewer/issues/3554
Fractional pixel dimensions (eg, 650.8) on canvas can cause "1px upsampling" (canvas is scaled larger by a single pixel), causing a slight "resampling blur" compared to native render size.
This can be fixed by removing the fractional parts of the dimensions.
After an initial solution using floor(), we are now switching to using ceil() to eliminate 1px gap issues.  (Concerns about three.js using floor() are moot; we just feed it integers anyway)
- As we are already focused on canvas dimensions here, we are also attempting to resolve 1px gap issues (in addition to initial blurring issue).  This is accomplished by using ceil() and hiding overflow
- Only "final" values are adjusted (retain floating point until the last step)
- Tested on both …

apply ceil() to canvas (prevent potential resampling from fractional pixel dimensions)

---

packages/model-viewer/karma.conf.js
packages/model-viewer/src/test/features/ar-spec.ts
packages/model-viewer/src/test/three-components/ARRenderer-spec.ts

Reverting the hostname: 'bs-local' in karma.conf because it made the tests not run locally and caused WebXR sessions to appear erroneously unsupported.

reactivate AR tests

---

packages/model-viewer/src/features/environment.ts
packages/model-viewer/src/model-viewer-base.ts
packages/model-viewer/src/test/features/controls-spec.ts
packages/model-viewer/src/three-components/TextureUtils.ts

I finally found the source of our flakiest test on the CI: the HDR rendering test. It turns out the `load` event was firing after the HDR image loaded, but just before it was actually applied to the scene (the flakiness was likely from where in the animation loop it happened to be when it finished). And it never repro'd locally because the network was instant - I finally got a local repro by opening dev tools in a debug Karma window and throttling the network.

fix HDR race condition

---

package-lock.json
packages/model-viewer/package-lock.json
packages/modelviewer.dev/package-lock.json
packages/render-fidelity-tools/package-lock.json
packages/render-fidelity-tools/package.json
packages/render-fidelity-tools/rollup.config.js
packages/render-fidelity-tools/test/config.json
packages/render-fidelity-tools/test/results-viewer.html
packages/space-opera/package-lock.json

FYI @emadurandal and @bsdorra, I'm disabling Rhodonite and dppbr-pt in our render fidelity tests for now. The code is still there, so it'll be easy to reenable them if anyone wants to. I'm removing Rhodonite primarily because of my [comments](https://github.com/google/model-viewer/pull/3513#issuecomment-1206673414) which have yet to be acknowledged or fixed. I'm removing dspbr-pt because we now have the Stellar renders with is a more official Dassault product, and running dspbr-pt was prohibitively slow. 
In both cases many of the tests were disabled, indicating these renderers are not yet generally glTF-compliant. I'd prefer to keep our official results to those renderers that either support the whole spec, or are actively working toward that goal. Please open a PR if you'd like to …

Disable non-conforming path tracers

---

packages/model-viewer/src/features/controls.ts
packages/model-viewer/src/three-components/SmoothControls.ts
packages/modelviewer.dev/examples/animation/index.html
packages/modelviewer.dev/examples/annotations/index.html
packages/modelviewer.dev/examples/augmentedreality/index.html
packages/modelviewer.dev/examples/lightingandenv/index.html
packages/modelviewer.dev/examples/loading/index.html
packages/modelviewer.dev/examples/scenegraph/index.html
packages/modelviewer.dev/examples/stagingandcameras/index.html
packages/modelviewer.dev/index.html

Fixes #3622 
I added `touch-action="pan-y"` to all our examples because they are set to nearly the full phone height on mobile, so this is a good example of when you would not want to swallow all scrolls, or the page becomes quite difficult to navigate.

default touch-action to none

---

packages/model-viewer/src/features/controls.ts
packages/model-viewer/src/test/features/controls-spec.ts
packages/model-viewer/src/test/three-components/SmoothControls-spec.ts
packages/model-viewer/src/three-components/SmoothControls.ts
packages/modelviewer.dev/data/docs.json
packages/modelviewer.dev/data/examples.json
packages/modelviewer.dev/examples/annotations/index.html
packages/modelviewer.dev/examples/color.html
packages/modelviewer.dev/examples/stagingandcameras/index.html
packages/modelviewer.dev/index.html
packages/space-opera/src/test/snippet_viewer/snippet_viewer_test.ts
packages/space-opera/src/types.ts

Fixes #3611 
Replaces `enable-pan` with `disable-pan` and adds `disable-tap`.

Enable pan by default

---

packages/model-viewer/src/test/three-components/Renderer-spec.ts
packages/model-viewer/src/three-components/Renderer.ts

I noticed an issue recently introduced by my render refactor, where when scrolling from one element to another (with only one visible at a time), the other one would end up blank until the scene was made dirty via e.g. interaction. It's because I was failing to copy the rendered pixels to the dedicated canvas when I switched to rendering a different element.

Fix render

---

packages/model-viewer/src/features/loading.ts
packages/modelviewer.dev/data/docs.json
packages/modelviewer.dev/examples/annotations/index.html

The dimensions example was getting incorrect placement of the labels when switching models in WebXR mode. This was because we were relying on `getCameraTarget` to find the center of the model, but that is in fact independent (especially since it can be set as an attribute). It's been fixed by adding `getBoundingBoxCenter()` right next to `getDimensions()`, as they should be used in concert.
I also updated the CSS in the annotations examples to be independent of each other, which makes them clearer and easier to copy.

Add getBoundingBoxCenter()

---

packages/model-viewer/src/three-components/ARRenderer.ts

Fixes an issue where the AR example was losing its lighting upon returning to 3D mode; it was a regression caused by #3606.

fixed AR scene cleanup

---

packages/model-viewer/src/three-components/PlacementBox.ts

Sometimes WebXR wall placement is not great and you can end up behind the model. Dragging and such was disabled in this case, so now it's double-sided.

make AR placement box double-sided

---

packages/model-viewer/src/three-components/ModelScene.ts
packages/model-viewer/src/three-components/Renderer.ts

Fixes #2502
Actually, I think most of #2502 was already fixed, but this is a significant refactor that I believe makes the renderer a lot less prone to bugs of this type. We had some occasional reports of the renderer scaling down and never coming back to full res even when the model stopped. I was never able to get a repro, but I'm betting the issue had to do with external factors (page performance, low-battery mode, etc) causing the page to not hit frame-rate, which then caused us to scale the render down even though it wasn't our fault. 
Now we only measure performance while we're rendering. We also immediately scale up to 100% when we stop rendering (model stops moving), so no need to wait for it to go through the steps. We also immediately scale back down to the previous steady-state …

Refactor render scaling

---

packages/model-viewer/src/three-components/PlacementBox.ts

In WebXR mode, the model had become difficult to drag around (before the floor is found) because when your finger went beyond the placement box, it would stop getting a hit result, and so stop moving. Must have been a change in three.js - just prodding the hit matrix to update was enough to solve it.

fix xr pre-placement

---

packages/model-viewer/src/test/features/loading-spec.ts
packages/model-viewer/src/three-components/ModelScene.ts

Fixes #3780 
Turns out that was a very longstanding error that was only recently triggered. It turns out that this loop is simply not going to do what it looks like:
```
for(const child of this.target.children){
this.target.remove(child);
}
```
It only worked before because there only happened to be one child; it fails to remove any of the others because `children` changes.

fixed src switching

---

packages/model-viewer/src/constants.ts

Fixes #3528
This contribution is gladly provided by the team at **Nvzn Augmented Reality** (https://www.nvzn.net/)
Recent updates to the new (soon to be released) iOS16 will change the behaviour of feature detection for AR QuickLook support.
In theory `a.relList.supports("ar")` can be used to test the browser for AR QuickLook support.
Prior to iOS16, an issue caused `a.relList.supports("ar")` to always return `true` for all WKWebView-based browsers, even though WKWebView itself does not, by default, support AR QuickLook.
Now in iOS16 `a.relList.supports("ar")` will always return `false` for all WKWebViews.
However, some WKWebView-based browsers, such as Chrome iOS, have implemented their own AR QuickLook handling. 
Prior to iOS16 ModelViewer would display the AR button for those WKWebView …

iOS16 ARQL compatibility checks

---

packages/model-viewer/src/three-components/Renderer.ts
packages/modelviewer.dev/examples/loading/index.html
packages/modelviewer.dev/examples/scenegraph/index.html
packages/modelviewer.dev/examples/stagingandcameras/index.html

I found a situation where when scrolling rapidly, causing switches between the multi-canvas and single canvas paths as well as render scale changes, we would sometimes get a blink of the wrong-sized canvas, and sometimes even get stuck in the single-canvas mode with the canvas scaled incorrectly. It's been fixed by removing some if statements to ensure the `canvas3d` is always rescaled whenever the other canvas is rescaled. I also refactored the code to make it more readable, but the change is actually quite small.
I also updated the frame rate targets to rescale between 15 and 25 fps, as this still feels pretty responsive and it doesn't seem worth sacrificing pixel density yet. This is partly because I found desktop Safari seems to target 40 fps when taxed instead of 60, which was …

Fixed render scale issue

---

packages/model-viewer/src/features/environment.ts
packages/model-viewer/src/model-viewer-base.ts
packages/model-viewer/src/test/features/loading-spec.ts
packages/model-viewer/src/test/three-components/ModelScene-spec.ts
packages/model-viewer/src/three-components/ARRenderer.ts
packages/model-viewer/src/three-components/ModelScene.ts
packages/modelviewer.dev/data/docs.json

Fixes #3800
This removes the `preload` event, as this is entirely duplicate of the `load` event now. It also refactors and further simplifies our internal loading logic, fixing some bugs like a black blink on first render with a custom environment map due to the poster being dismissed before the lighting was loaded. Also fixes the `load` event being dispatched multiple times for a given `src` and improves performance by ensuring everything is loaded before the first render happens so we don't have to compile the shaders two different ways.

Remove preload event

---

packages/model-viewer/src/features/ar.ts
packages/modelviewer.dev/data/docs.json
packages/modelviewer.dev/examples/animation/index.html
packages/modelviewer.dev/examples/annotations/index.html
packages/modelviewer.dev/examples/augmentedreality/index.html
packages/modelviewer.dev/examples/color.html
packages/modelviewer.dev/examples/lighthouse.html
packages/modelviewer.dev/examples/lighthouse2.html
packages/modelviewer.dev/examples/loading/index.html
packages/modelviewer.dev/examples/scenegraph/index.html
packages/modelviewer.dev/examples/stagingandcameras/index.html
packages/modelviewer.dev/examples/twitter/generator.html
packages/modelviewer.dev/examples/twitter/player.html
packages/modelviewer.dev/index.html
packages/modelviewer.dev/src/docs-and-examples/create-html.ts
packages/modelviewer.dev/styles/examples.css
packages/space-opera/src/test/snippet_viewer/snippet_viewer_test.ts

Fixes #3801 
Also removes the examples header from the mobile view of modelviewer.dev, which makes it more like the desktop version and makes the progress bar more visible.

Default to USDZ autogeneration on iOS AR

---

packages/model-viewer/src/three-components/GLTFInstance.ts

When we hit the modelCacheSize limit and start disposing of models, we were getting an error on iOS 14 because it doesn't support `ImageBitmap`. I didn't realize that `typeof` still requires the feature to be present in order to safely check.

fix iOS model dispose

---

packages/model-viewer/src/model-viewer-base.ts
packages/model-viewer/src/test/features/loading-spec.ts

The IntersectionObserver by default logs elements that are adjacent to the viewport (zero intersection) as intersecting: https://github.com/w3c/IntersectionObserver/issues/134#issuecomment-224365108
This is a problem for some carousels which have the element in view having the full width: it would cause the invisible neighboring carousel elements to render and steal frame budget. Just a one-line fix, but added tests to catch this subtlety.

fix adjacent visibility

---

packages/model-viewer/src/test/three-components/Renderer-spec.ts
packages/model-viewer/src/three-components/Renderer.ts

When a MV element was added to the tree after rendering had begun, its canvas size was not being synced to the renderer, causing strange model scales (often looked like a blank render). Added regression testing.

fixed canvas size on late registration

---

packages/model-viewer/src/features/annotation.ts
packages/model-viewer/src/test/features/annotation-spec.ts
packages/modelviewer.dev/data/docs.json
packages/modelviewer.dev/data/examples.json
packages/modelviewer.dev/examples/annotations/index.html

Discussion at https://github.com/google/model-viewer/discussions/3833
This is a first pass to add the ability to query a read-only snapshot of in-scene information about a hotspot by name, most crucially the screen space (canvas) position. 
Entirely open to suggestions about the API (in particular it does feel odd that the returned position Vector2D is `u` and `v`, though it makes sense where it's currently only used for UV lookups) and how on earth to test a screen space position given that it relies on so many model-viewer defaults...
The PR includes a working example to aid discussion, which may or may not be complete overkill for this 😅

Hotspot data query API

---

packages/model-viewer/src/features/ar.ts

Fixes https://github.com/google/model-viewer/discussions/2755
It appears Safari iOS16 is no longer propagating the `_apple_ar_quicklook_button_tapped` ARQL message event to the originating anchor element when the anchor is not attached to the DOM. This causes ModelViewer to never broadcast the `quick-look-button-tapped` event in iOS16. 
Changes have been made to `ar.ts` to append the ARQL anchor element to the shadow DOM and setting `display` to `none`.
With the anchor attached to the DOM, the `_apple_ar_quicklook_button_tapped` ARQL message is received and MV broadcasts the `quick-look-button-tapped` event now in iOS16. 
An example of ModelViewer compiled with this code change can be found here:
https://modelviewer-ios16-arql-banner-fix.glitch.me/
This has been tested in Safari iOS 16.0 …

iOS16 ARQL banner click fix

---

packages/model-viewer/src/features/scene-graph/nodes/primitive-node.ts
packages/model-viewer/src/three-components/gltf-instance/VariantMaterialExporterPlugin.ts
packages/model-viewer/src/three-components/gltf-instance/VariantMaterialLoaderPlugin.ts

Fixes #3814 
Turns out it was just missing a `null` check. Keep in mind, when you add a variant name only and export, that name will not be saved since it did not actually apply to any materials. Only when materials are changed is a new variant actually created.

Fix variant export

---

packages/model-viewer/src/features/scene-graph/api.ts
packages/model-viewer/src/features/scene-graph/material.ts
packages/model-viewer/src/features/scene-graph/pbr-metallic-roughness.ts
packages/modelviewer.dev/examples/scenegraph/index.html
packages/space-opera/src/components/materials_panel/materials_panel.ts
packages/space-opera/src/test/materials_panel/materials_panel_test.ts

Fixes #3906 
Expands the `setBaseColorFactor` and `setEmissiveFactor` APIs to allow CSS color strings in addition to linear RGBA arrays. For the CSS-style strings, the conversion from sRGB happens internally, making color picking more user-friendly.

Added color string support

---

packages/model-viewer/src/features/annotation.ts
packages/model-viewer/src/test/features/annotation-spec.ts
packages/modelviewer.dev/data/docs.json
packages/modelviewer.dev/examples/annotations/index.html

FYI @jukibom I changed `screenPosition` to `canvasPosition` in your new API, which I should have caught in code review, but at least it's before release.

rename screenPosition to canvasPosition

---

packages/model-viewer/src/three-components/Renderer.ts

Fixes #3876 
Issue: If we only have one visible scene we will call an appendChild of the 3D canvas at every frame. Apparently this was OK in most browsers but iOS 15 Safari doesn't like it. 
Note: that's why the model isn't visible if we move it but visible during idle since in that case the render loop not reaches this appendChild every frame
Issue was introduced here: #3704, that's why its not in v1.12.0 but already in v2.0.0
Tested with iOS Safari 15.2 and checked for regressions in MacOS Chrome
Implementation note:
The best solution I can think of would be to move this canvas selection logic upper in the render loop somewhere around the current `countVisibleScenes` but without lots of test devices I didn't wanted to mess around with the render loop too much (but open for suggestions)

Don't reappend the 3D canvas every frame

---

packages/model-viewer/src/three-components/SmoothControls.ts

Fixes #3999 
Camera perspective matrices don't like getting zero for the near or far plane! This fixes both skybox and the hotspots. Since the far plane is set arbitrarily to 2 when the scene is empty, just use normalized vectors for hotspot positions when camera radius is set to zero.

fixed near/far plane for empty GLB

---

packages/modelviewer.dev/examples/annotations/index.html

The dimension SVG lines are mysteriously missing from https://modelviewer.dev/examples/annotations/index.html#dimensions on Safari only. Stranger yet, when serving the same page locally, they work just fine (!). Makes debug hard. Setting width and height as attributes instead of style since some people reported that as a Safari bug.

Try to fix SVG on Safari

---

packages/space-opera/src/components/model_viewer_preview/model_viewer_preview.ts

We had a request to be able to view models in AR offline: https://twitter.com/modelviewer/status/1604596420660678659
Really this should have already been working via the editor, but I realized the AR button was not showing up on mobile, which is fixed here. This is another convenient way to test models in AR - instead of using mobile deploy, if you have the GLBs on your mobile file system, just load them up in the editor and test them all on a single device.

test AR directly in mobile editor

---

packages/model-viewer/src/test/features/controls-spec.ts
packages/model-viewer/src/three-components/SmoothControls.ts

There are two fixes here, one for the actual problem, and a second to act as a backstop against similar problems. Both were verified to independently fix the issue via the included test.
I also verified that no matter what nonsense you put into `camera-orbit` or `cameraOrbit`, it will never produce NaN, it instead falls back to the default initial values.

fixed NaN cameraOrbit

---

packages/model-viewer/src/model-viewer-base.ts

This is more for general robustness; when a MV element is detached from the DOM tree, it gets a resize event for zero size. There's no reason to make any changes for this, since as soon as it's reattached it will get a new size. We found some strange cases where it seems to not get updated size message (`ResizeObserver` bug?), but it was difficult to debug as the render was just blank (no size). Now it will keep working, at least if it came back at the same size.

don't resize to zero

---

packages/model-viewer/src/features/loading.ts
packages/model-viewer/src/model-viewer-base.ts

Fixes #3967 
Turns out the poster just got in the way. `dismissPoster()` is another workaround, but shouldn't be necessary now.

fix disconnect-reconnect showing poster on loaded model

---

packages/render-fidelity-tools/test/config.json
packages/render-fidelity-tools/test/results-viewer.html

- Swapped order of config files so "ground truth" Dassault renderer is last instead of being mixed in the middle.
- Changed "three-gpu-pathtracer" description to the project name so it's more clear which renderer is being used.
- Added links to the "three-gpu-pathtracer" and "gltf-sample-viewer" projects so they're more discoverable and it's more clear which renderers are being used in the comparison.

Update fidelity tests page copy, links

---

packages/model-viewer/src/three-components/Renderer.ts

When switching back and forth between models we could end up showing both the webGL canvas and the canvas 2D, one updating and the other stuck. This regression was caused by #4046 and fixed here.

fixed bug showing 2 canvases

---

packages/model-viewer/src/features/loading.ts
packages/model-viewer/src/model-viewer-base.ts
packages/model-viewer/src/three-components/TextureUtils.ts

Fixes #4083 
This is a pretty straight-forward fix, but I don't have a great way to test it. @robertsLando I'd appreciate it if you can verify this is working for you once it's in.

set withCredentials for other loaders

---

packages/space-opera/src/components/best_practices/constants.ts
packages/space-opera/src/components/best_practices/render_best_practices.ts
packages/space-opera/src/components/best_practices/styles.css.ts

Fixes #4082 
I did manage to repro this issue; the fact it happens only on certain tab reloads on Android makes it feel like more of a Chrome bug, honestly. But in the process I noticed some errors we introduced in our export and it's at least possible these somehow triggered the bug.

cleanup editor export

---

packages/model-viewer/src/three-components/TextureUtils.ts

Fixes https://github.com/google/model-viewer/pull/4085#issuecomment-1415653175

fix withCredentials

---

packages/modelviewer.dev/examples/scenegraph/index.html

Fixes #4102 
The example was not waiting for the MV library to load, causing errors like `createVideoTexture` is not a function.

fix video texture on Firefox

---

packages/model-viewer/src/features/scene-graph/texture-info.ts

Animated textures were slow to update on firefox because it doesn't support `requestVideoFrameCallback` and it sends the `timeupdate` event very slowly. Now it will just render all the time if a video texture is present.

fix firefox video framerate

---

packages/modelviewer.dev/examples/annotations/index.html

Fixes missing SVG pointers on animated hotspot example on iOS - same fix as before, but forgot to apply to the new example.

fix other SVG example

---

packages/model-viewer/src/features/scene-graph/api.ts
packages/model-viewer/src/features/scene-graph/image.ts

This issue was caused because the lottie-web is listed as a dev dep to use it's types, in this case `import` statement is wrong as it would import all the module on runtime, using `import type` will fix the issue and used to check the types only on compilation stage
Fixes #4090

fix: model-viewer@v3 uses lottie-web as a dev dependency

---

packages/modelviewer.dev/examples/scenegraph/index.html

Fixes Lottie example for Safari, where import maps are not supported.

Safari lottie

---

packages/model-viewer/src/features/scene-graph/texture-info.ts
packages/modelviewer.dev/examples/scenegraph/index.html

It turns out Lottie textures were pretty broken in the last release, but it wasn't clear because of a combination of bugs and examples. Most critically, Lottie textures were not triggering the scene to re-render, so they would only update when the camera moved. This wasn't noticed because of bug 2, in which video textures continue to re-render the scene even then they are removed from it. The example hid the problem because it always loaded the video texture before the Lottie texture, so everything appeared to be working. All of these are fixed here.

Fix lottie update

---

package-lock.json
packages/model-viewer/package-lock.json
packages/model-viewer/package.json
packages/model-viewer/src/features/scene-graph/api.ts
packages/model-viewer/src/features/scene-graph/image.ts
packages/render-fidelity-tools/package-lock.json
packages/space-opera/package-lock.json

Fixes #4090 
So, I attempted to include `lottie-web` just for types info on the `animation` object of a LottieTexture, but that does not seem to be how npm works. I've decided the simplest thing is just to remove it entirely and mark `animation` as type `any`. If you actually want to use it in TS, you can import `lottie-web` and cast it appropriately.

remove lottie-web dependency

---

README.md
package-lock.json
packages/model-viewer/README.md
packages/model-viewer/package-lock.json
packages/model-viewer/package.json
packages/modelviewer.dev/data/faq.json
packages/modelviewer.dev/examples/twitter/player.html
packages/modelviewer.dev/index.html
packages/modelviewer.dev/package-lock.json
packages/render-fidelity-tools/package-lock.json
packages/space-opera/package-lock.json
packages/space-opera/src/components/best_practices/constants.ts

Fixes #2747 
Technically a breaking change for our npm users, but should be pretty simple to update (install three) and will allow sharing of three.js. I'm going to sneak it in since we're so close after v3.0, and since it doesn't actually change our bundled code at all.

three.js -> peer dependency

---

packages/model-viewer/src/features/scene-graph.ts

The videoTexture would not automatically play on iOS - turns out to be a simple fix.

fix video texture on iOS

---

packages/modelviewer.dev/examples/loading/index.html
packages/space-opera/src/components/best_practices/constants.ts
packages/space-opera/src/components/model_viewer_preview/model_viewer_preview.ts

Fixes: Issue #4195 
The MeshOptimizer cannot be resolved due to unpkg.com being down. This changes where meshopt_decoder.js is pulled from to jsDelivr.com which is a more stable option for a CDN.

Remove references to unpkg.com and update to jsDelivr.com for stability

---

packages/model-viewer/src/three-components/GLTFInstance.ts
packages/model-viewer/src/three-components/ModelScene.ts
packages/model-viewer/src/three-components/gltf-instance/ModelViewerGLTFInstance.ts
packages/model-viewer/src/three-components/gltf-instance/VariantMaterialLoaderPlugin.ts
packages/model-viewer/src/three-components/gltf-instance/correlated-scene-graph.ts
packages/space-opera/src/components/hotspot_panel/types.ts
packages/space-opera/src/components/model_viewer_preview/model_viewer_preview.ts
packages/space-opera/src/components/model_viewer_snippet/parse_hotspot_config.ts
packages/space-opera/src/components/utils/hotspot/render_hotspots.ts
packages/space-opera/src/test/model_viewer_snippet/parse_hotspot_config_test.ts

Fixes #4217 
We had a bunch of code that was mesh-specific, when really it should apply equally well to point or line objects.
This also updates our editor to automatically create surface hotspots only for animated models and world-position hotspots otherwise, which allows this to work for point cloud models.

Point cloud improvements

---

packages/model-viewer/src/features/animation.ts
packages/model-viewer/src/three-components/ModelScene.ts

Fixes #4226 
Just a (almost) one-liner, along with ditching the useless warning. It's required to set `animation-name="0"` (or any other name) before setting `currentTime` will work. Otherwise the model stays at resting pose.

fixed setting currentTime

---

packages/model-viewer/src/features/controls.ts

Removes ending period from custom alt text if it exists.
Fixes #4236

fix: Remove doubled period from start of alt text.

---

packages/model-viewer/src/three-components/SmoothControls.ts

Once in a while I see our pointer get "stuck down", as in mouse moves with no button down continue to rotate the model. It's rare and usually only happens when dev tools is open. However, recently we found one older macbook that repros it semi-consistently on a particular page, so figured it's better safe than sorry. This should be a solid backstop to any weird situation where we fail to get a `pointerup` or `pointercancel` event.

robustify pointing

---

.eslintignore
packages/model-viewer-effects/README.md
packages/model-viewer/package-lock.json
packages/model-viewer/package.json
packages/modelviewer.dev/data/faq.json
packages/modelviewer.dev/examples/postprocessing/index.html
scripts/postinstall.js

Whenever npm install is run in `packages/model-viewer`, `packages/model-viewer-effects/README.md` and the examples in `packages/modelviewer.dev/examples/postprocessing/index.html` are automatically updated to be in sync with the three version in `package.json`.

Added postinstall script that updates the three importmap version

---

packages/model-viewer/src/features/scene-graph/api.ts
packages/model-viewer/src/features/scene-graph/image.ts
packages/model-viewer/src/features/scene-graph/material.ts
packages/model-viewer/src/features/scene-graph/model.ts
packages/model-viewer/src/features/scene-graph/pbr-metallic-roughness.ts
packages/model-viewer/src/features/scene-graph/sampler.ts
packages/model-viewer/src/features/scene-graph/texture-info.ts
packages/model-viewer/src/features/scene-graph/texture.ts
packages/model-viewer/src/features/scene-graph/three-dom-element.ts
packages/model-viewer/src/test/features/scene-graph/material-spec.ts
packages/model-viewer/src/test/features/scene-graph/model-spec.ts

Change from MeshStandardMaterial to MeshPhysicalMaterial
Feature: #4273

EmissiveStrength and Clearcoat extensions

---

packages/model-viewer/src/features/scene-graph/api.ts
packages/model-viewer/src/features/scene-graph/material.ts
packages/model-viewer/src/features/scene-graph/texture-info.ts

Missing:
iridescene, next commit
anisotropy, not supported by three.js yet.

Add PBR Next properties API

---

packages/model-viewer/src/features/ar.ts

Fixes #4404
The function `openIOSARQuickLook` is asynchronous and should be awaited.

await openIOSARQuickLook when activating AR

---

packages/model-viewer/src/features/controls.ts
packages/model-viewer/src/three-components/SmoothControls.ts
packages/modelviewer.dev/data/docs.json

Fixes https://github.com/google/model-viewer/discussions/4401
When the distance between the minimum radius and the maximum radius is big, the mousewheel zooms too much. Exposing the zoom-sensitivity and pan-sensitivity attributes would allow for better control.

Add zoom sensitivity and pan sensitivity attributes

---

packages/model-viewer/src/features/scene-graph/api.ts
packages/model-viewer/src/features/scene-graph/sampler.ts
packages/model-viewer/src/test/features/scene-graph/texture-info-spec.ts
packages/modelviewer.dev/examples/scenegraph/index.html

Convert to ThreeJS.Vector2 internally in public api.

---

packages/model-viewer/src/features/scene-graph/nodes/primitive-node.ts

Fixes #4443 
I don't love this solution, but anything better will require major surgery. This is related to the fact that we are still not properly handling the relatively rare situation where a single glTF material becomes several three.js materials because it is applied to meshes with different properties (e.g. tangents or none). This will still mostly work, but I'm sure there are some similar bugs lurking.

Variant normal flip

---

packages/model-viewer/src/features/scene-graph/sampler.ts
packages/model-viewer/src/three-components/gltf-instance/gltf-2.0.ts
packages/modelviewer.dev/examples/scenegraph/index.html

Add fix for Wrapping exposed

---

packages/model-viewer/src/features/scene-graph/sampler.ts
packages/model-viewer/src/three-components/gltf-instance/gltf-2.0.ts
packages/modelviewer.dev/examples/scenegraph/index.html

Removes ThreeJS' TextureFilter leak in our API

Fix API exposing threejs properties

---

packages/model-viewer/src/template.ts

Fixes #3545. Following the specs set out in  [ARIA in HTML - Document conformance requirements for use of ARIA attributes in HTML](https://www.w3.org/TR/html-aria/#docconformance) an anchor tag should ususally have an href and an anchor tag with href should also have a role. Since this anchor behaves like a button and launches AR, I believe the best solution would be a void href with a role of button.
Confirm the changes worked and all tests passed. Also since we like bigger numbers, the Lighthouse score for "Accessibility" went from 78 to 83 with this change!  
Please let me know if any changes need to be made and I will happily make them (especially if you would like to see tests added, wasn't quite sure where to start there)
I am participating in …

Add href to AR button, improve accessibility

---

packages/render-fidelity-tools/src/artifact-creator.ts
packages/render-fidelity-tools/src/workflows/test-fidelity.ts
packages/render-fidelity-tools/src/workflows/update-screenshots/renderer-screenshot.ts

These minor changes save a total of 50s out of the original 146s for each fidelity test run when run locally - thus a 32% savings.  I know of a few more ways to save time (render the next test while evaluating the results of the current one, and then run tests in parallel), but this is the low hanging fruit.
These timings are from a Mac mini M2 Pro:
```bash
% time npm run test
146.62s user 36.70s system 124% cpu 2:26.74 total
% time npm run test
60.20s user 4.59s system 61% cpu 1:44.97 total
% time npm run test
111.77s user 15.31s system 131% cpu 1:36.66 total
```
Also looking at this PR's CI time for the fidelity tests, it appears to have reduce the wall clock from 10m 36s to 8m 28s (2m 10s) for the test run.  I am comparing it to the CI time on this other PR: …

Reduce time for fidelity test CI locally by 50s, Github CI by 130s

---

packages/render-fidelity-tools/src/components/renderers/babylon-viewer.ts

See https://github.com/KhronosGroup/glTF-Sample-Assets/pull/34#issuecomment-1775665652

Enable transparencyAsCoverage in Babylon Viewer

---

packages/model-viewer/src/features/controls.ts
packages/model-viewer/src/features/loading.ts
packages/model-viewer/src/styles/deserializers.ts
packages/model-viewer/src/three-components/Hotspot.ts
packages/model-viewer/src/utilities.ts

While browsing through the code, I found some IE11-specific code. Since IE11 is not a supported browser anymore (by model-viewer's [README](https://github.com/google/model-viewer/tree/99fa9a8ba5c31ba161880f8b82248a196759dee4/packages/model-viewer#browser-support)), nor by [three.js](https://github.com/mrdoob/three.js/blob/4acb78002425969f7c0cf46423ea5f728c41dfbc/package.json#L40), I think this code can be refactored to more modern code. This change leads to a somewhat smaller bundle size.
File size after a `npm run build`:
| File name                          | Old size (byte) | New size (byte) | Size diff (byte) | Size difference (%) |
| ---------------------------------- | -------- | -------- | ----------------- | ------------------- |
| model-viewer-module-umd.js         | 811477   | …

Remove IE11-specific code

---

packages/modelviewer.dev/data/faq.json

Fixes #4566, by adding an FAQ to help guide others.

added another faq

---

packages/model-viewer/src/features/scene-graph.ts
packages/modelviewer.dev/data/docs.json

Fixes #4634
- Adds `option: CreateVideoTextureOptions` argument to `createVideoTexture`. Allowing to call it like `createVideoTexture(url, {crossOrigin: "anonymous"})`
Please let me know if there is any change needed if the solution is accepted (like updating documents, etc).

Add CreateVideoTextureOptions to support crossOrigin videos

---

README.md

This commit corrects a tiny typo in the capitalization of "GitHub".
N/A

fix: small typo in README

---

packages/model-viewer/src/features/loading.ts

Propagate event reason when firing progress events

---

packages/model-viewer-effects/src/effects/mixins/effect-base.ts
packages/model-viewer-effects/src/effects/utilities.ts
packages/model-viewer-effects/src/test/effects/color-grade-spec.ts
packages/model-viewer-effects/src/test/index.ts
packages/model-viewer-effects/src/test/utilities.ts
packages/model-viewer/src/decorators.ts
packages/model-viewer/src/features/scene-graph.ts
packages/model-viewer/src/styles/conversions.ts
packages/model-viewer/src/styles/evaluators.ts
packages/model-viewer/src/styles/style-effector.ts
packages/model-viewer/src/test/features/annotation-spec.ts
packages/model-viewer/src/test/features/scene-graph-spec.ts
packages/model-viewer/src/three-components/CachingGLTFLoader.ts
packages/model-viewer/src/three-components/Shadow.ts
packages/model-viewer/src/three-components/gltf-instance/VariantMaterialExporterPlugin.ts
packages/model-viewer/src/utilities/animation.ts
packages/model-viewer/src/utilities/debug.ts

Add explicit file extensions to relative imports of model-viewer and model-viewer-effects

---

packages/model-viewer/src/three-components/Renderer.ts
packages/modelviewer.dev/examples/lut-writer.mjs
packages/modelviewer.dev/examples/tone-mapping.html

Feedback from Autodesk was that the ability to analytically invert a tone mapping function has a lot of important use cases through the industry. It turns out my tone mapper was quite difficult to invert, but a very small and almost imperceptible change made it trivial to invert. The key is making the desaturation step not change the compressed brightness value, so instead of mixing toward pure white `[1, 1, 1]`, instead go toward `peak * [1, 1, 1]`. Anywhere the mix is significant, `peak` is already very close to 1, so this is a minor change, but it helps enormously with invertibility since these asymptotes become so sensitive when inverted. 
I've included an analytical inverse function in `lut-writer.mjs` and verified the round-trip relative error is less than `2e-10`.

Make Khronos PBR Neutral invertable

---

packages/model-viewer/src/utilities.ts

Turns out any `<model-viewer>` embedded in an `<iframe>` gets the capped DPR=1 (no high-res render) unless the iframe has a meta viewport tag in its own `<head>`. That's a bit weird, since meta viewport tags are ignored in iframes and only the top-level document counts. As such, we'll assume the top level document has a meta viewport tag (as that's more common) when the element is inside an iframe and can't query its parent's `<head>`.

fix DPR for iframes

---

packages/space-opera/src/components/model_viewer_snippet/parse_hotspot_config.ts

By using innerText, it will avoid the risk of HTML injection, as these properties automatically escape any HTML special characters in the provided text. This helps prevent cross-site scripting (XSS) vulnerabilities by treating the input as plain text rather than interpreted HTML. Always be cautious when dealing with user input or dynamic content to prevent security risks.

 parse_hotspot_config.ts DOM text reinterpreted as HTML 

---

package-lock.json
packages/model-viewer-effects/package.json
packages/modelviewer.dev/examples/postprocessing/index.html

Needed to bump the postprocessing version to keep up with the removal of deprecated encodings in Three.js. However, now we have a new problem: 
```
postprocessing.js:274 Uncaught TypeError: Cannot read properties of undefined (reading 'Camera')
```
At this example: https://modelviewer.dev/examples/postprocessing/index.html#custom-effects
@Beilinson would you mind taking a look? I'm guessing this is related to your comment, which might not be true anymore:
>`// The camera is set automatically when added to the <effect-composer>`

Fix Postprocessing for r163

---

packages/model-viewer/src/three-components/ModelScene.ts
packages/modelviewer.dev/examples/lightingandenv/index.html

Unlike the normal skybox, the grounded skybox was rotating with the model during `auto-rotate`, which is inconsistent and caused the background to be not in the same place as the applied environment lighting, since that was correctly not rotating. 
This now means the model moves relative to the ground when panning or changing the turntable rotation. I don't totally love that, but it's the only way to be consistent with our existing API.

fix grounded skybox rotation

---

packages/model-viewer/src/three-components/Renderer.ts

I'm building an online store and I'm using Swup.js to have animated page transitions. It uses ajax to replace the contents of the website without doing a full reload.
This store has 3D objects **only** in each product page.  Nonetheless, I have to load the script as a module in every page because of the way Swup.js works. I cannot have a <script> for the product page and get it to load manually at some point without touching the code of the source script. They have to be bundled with the rest of the site.
I've noticed a good amount of stuttering when any page loads from cold. Tracing and profiling the site, I've noticed `Renderer._singleton` gets called on every page load, even though there may not be any `<model-viewer>` present in the page at that moment.
`Renderer._singleton` …

Load the renderer only when <model-viewer> is present

---

packages/modelviewer.dev/data/docs.json
packages/modelviewer.dev/examples/annotations/index.html
packages/modelviewer.dev/examples/augmentedreality/index.html
packages/modelviewer.dev/examples/color.html
packages/modelviewer.dev/examples/lightingandenv/index.html
packages/modelviewer.dev/examples/loading/index.html
packages/modelviewer.dev/examples/scenegraph/index.html
packages/modelviewer.dev/examples/tone-mapping.html
packages/space-opera/src/components/ibl_selector/ibl_selector.ts
packages/space-opera/src/types.ts

Deprecating the old "commerce" tone mapping name in favor of "neutral" to align with the new Khronos PBR Neutral standard it has become: https://github.com/KhronosGroup/ToneMapping/tree/main
commerce is an alias for neutral to avoid breaking changes, but encouraging the use of neutral from now on.

update commerce to neutral

---

.github/workflows/deploy-documentation.yml
packages/modelviewer.dev/examples/fidelity.html
packages/modelviewer.dev/scripts/ci-before-deploy.sh

This should set our old modelviewer.dev/fidelity link to redirect to the new Khronos page. It also speeds up our deployment process, since we no longer have to generate goldens for that.

cleanup and redirect

---

package-lock.json
packages/model-viewer-effects/README.md
packages/model-viewer-effects/package.json
packages/model-viewer/package.json
packages/model-viewer/src/features/ar.ts
packages/modelviewer.dev/examples/postprocessing/index.html

Upgrade to latest threejs (r164)

---

packages/modelviewer.dev/examples/scenegraph/index.html

Fixed code example for pickMaterialExample to work in webXR
About #4847

Fixes code example

---

packages/model-viewer/src/features/annotation.ts
packages/model-viewer/src/test/features/annotation-spec.ts
packages/model-viewer/src/three-components/Hotspot.ts
packages/model-viewer/src/three-components/ModelScene.ts

fixed surface hotspot updates

---

packages/space-opera/src/components/ibl_selector/ibl_selector.ts

The “aces” option in the tone mapping selector of the editor is missing a specified value.

Set the aces value in the tone-mapping item

---

packages/model-viewer/src/features/controls.ts
packages/model-viewer/src/three-components/SmoothControls.ts
packages/modelviewer.dev/data/docs.json
packages/render-fidelity-tools/test/config.json

As this updates our defaults, it is technically a breaking change, though very minor. Our default camera limits used to not allow a pure top or bottom view - they had to be manually extended to get the full 0-180 range of camera elevation. Now that is our default, but you can always set them back to how they were if you desire the legacy behavior.

allow top and bottom view by default

---

packages/modelviewer.dev/examples/annotations/index.html
packages/modelviewer.dev/examples/postprocessing/index.html

Apparently the trick in WebXR is to remember that we don't fullscreen the whole MV element, but just the slot that carries its children. This means you can't ask about the size of MV - it's still hidden on the old page. But in AR mode, you know you're always full-screen, so use those dimensions instead.

fixed two examples bugs

---

packages/model-viewer/README.md
packages/modelviewer.dev/index.html

#4942
I believe these badges will better communicate to users that using model-viewer through NPM is a viable option.

Docs: Add NPM badges for <model-viewer>

---

packages/model-viewer/README.md

#4942
Show how to import the NPM package in a project. Added NPM and CDN headings for clarity.
There's still lots of information missing, when comparing the instructions to [those of three.js](https://threejs.org/docs/#manual/en/introduction/Installation). They have an entire page dedicated to every involved concept.
But I think this is a small improvement.
Let me know what you think.

Docs: Improve install instructions

---

packages/model-viewer/src/three-components/Shadow.ts

#4943
Make objects cast shadows from top facing geometry. Specifically, this improves the appearance of hard shadows cast from non-manifold geometry, which has holes on the bottom.
The softer shadows become, the less effect this change has.
Before, after:
~~I didn't actually manage to get the build setup on windows, so I have no idea if the code works. Let me know if there's an easy way to build/deploy so I can confirm functionality.~~

Improve shadow robustness

---

packages/model-viewer/src/three-components/ARRenderer.ts

Previous PR introduced a bug where the panel is added for all modes of AR, while the feature is intended only for XR

add xrmenupanel only in xr, avoid ar

---

packages/space-opera/src/components/mobile_view/components/mobile_modal.ts
packages/space-opera/src/components/mobile_view/utils.ts

#5061
This pull request updates the piping server URL used for mobile deployment in the `MobileModal` component and related utility functions. The changes ensure the application uses the new server hosted on Render instead of the previous one hosted on Glitch. 
Here is a demo video.
https://x.com/modelviewer/status/1352304331358236672
This describes the connection flow.
https://github.com/google/model-viewer/pull/1746#issuecomment-745631641

update Piping server instance

---

packages/space-opera/src/components/mobile_view/components/mobile_modal.ts
packages/space-opera/src/components/mobile_view/utils.ts

Addressing #5061 since glitch got deprecated and Render.com is not compatible with model-viewer. So switching to https://ppng.io/ (the most stable Piping Server hosting)
Here is the tested version. I also added the viewable link to the ux to streamline testing.
[editorexample.webm](https://github.com/user-attachments/assets/b65c66ab-0f46-4982-97e5-5ea38b383e66)

Switching to https://ppng.io from https://piping.onrender.com/
